### ISSUE TITLE
flutter_driver does not have visibility API. Need to get a hack

### ISSUE THREAD

**Issue by sahanaprasad** [appium-userland/appium-flutter-driver#103]
code:
assertTrue(find.byValueKey("counter").isDisplayed());

error: org.openqa.selenium.UnsupportedCommandException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 19 milliseconds

capabilities: "app": "/Users/sahanaprasad/development/flutterAutomationTrial/src/apps/android-real-debug.apk",
   "automationName": "Flutter",
   "platformName": "Android",
   "deviceName": "Honor 8 Lite"

appium logs:
[debug] [simctl] MJSONWP (ba47d004) Calling AppiumDriver.elementDisplayed() with args: ["eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiY291bnRlciJ9","ba47d004-8819-41e9-bda7-2d69cee47eeb"]
[debug] [simctl] FlutterDriver Executing Flutter driver command 'elementDisplayed'
[debug] [simctl] MJSONWP (ba47d004) Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[debug] [simctl] MJSONWP (ba47d004)     at FlutterDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/appium-base-driver/lib/basedriver/driver.js:323:13)
[debug] [simctl] MJSONWP (ba47d004)     at FlutterDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/driver.ts:123:22)
[debug] [simctl] MJSONWP (ba47d004)     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:534:36)
[debug] [simctl] MJSONWP (ba47d004)     at processTicksAndRejections (internal/process/task_queues.js:94:5)
[debug] [simctl] MJSONWP (ba47d004)     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
[simctl] HTTP <-- GET /wd/hub/ses

**Comment by shibupanda** [comment]
@sahanaprasad isDisplayed() is not available in flutter driver.
For a work around you can use waitFor inside try..catch block.

**Comment by KazuCocoa** [comment]
No API by Flutter. As a workaround in this driver, waitFor in Flutter context or native's visibility might help...

**Comment by Tumist76** [comment]
> No API by Flutter. As a workaround in this driver, waitFor in Flutter context or native's visibility might help...

If I need to check that element doesn't exist on screen, how can I do this? As I understand, `waitFor` will wait for widget to appear.

I'm now trying to check it like this, but `is_displayed` is always true.

```python
pin_radio_button = FlutterElement(driver, finder.by_text('some text'))
    if not pin_radio_button.is_displayed:
        # do something
```

**Comment by oligazar** [comment]
@Tumist76 it should be 
`if not pin_radio_button.is_displayed():`
But this still will give you "Method has not yet been implemented"
