### ISSUE TITLE
Cannot set security flags when switching context to NATIVE_APP

### ISSUE THREAD

**Issue by ajschwieterman** [appium-userland/appium-flutter-driver#106]
I have the `--relaxed-security` flag enabled in my Appium server to send ADB commands to my Android phone.  This works fine when the automationName is set to UiAutomator2, but when the automationName is set to Flutter, it doesn't work.  I even changed the context to NATIVE_APP, and I get an error.

```
driver.context("NATIVE_APP");
(String)driver.executeScript("mobile:shell", ImmutableMap.of("command", "settings", "args", {"put", "secure", "autofill_service", "null"}));
driver.context("FLUTTER");
```

I've attached the Appium logs
[appium-log.txt](https://github.com/truongsinh/appium-flutter-driver/files/5387584/appium-log.txt)

**Comment by shibupanda** [comment]
@ajschwieterman This option is not there in flutter driver yet.

**Comment by KazuCocoa** [comment]
https://github.com/appium-userland/appium-flutter-driver/pull/178/files#diff-b0b60a27bcae55f51aed5fe23588c5bcee3c7c9493853d3ac5ede07659d5448b will have this change.
So, `--allow-insecure`, `--deny-insecure` and `--relaxed-security` will pass to UIA2/XCUITest as well.

**Comment by KazuCocoa** [comment]
I've pushed the change as https://www.npmjs.com/package/appium-flutter-driver/v/0.0.32 
You can apply the change on your local, or you could try the version with `appium@beta` (then, please make sure to re-install appium)
