### ISSUE TITLE
Is there a way to switch the capabilities between "Flutter" and  "UiAutomator2" in a single app while running tests ?

### ISSUE THREAD

**Issue by chughrahul** [appium-userland/appium-flutter-driver#109]
I've my application with embedded flutter views and the tests are written in java(appium). I want to add tests for the flutter views but it says that it needs capability "automationName" set to "Flutter". But my "automationName" capability is set to "UiAutomator2". Is there a way to dynamically change the capability to Flutter when my application reaches the flutter views ?

**Comment by jemishgopani** [comment]
Did you try to change the context?

**Comment by chughrahul** [comment]
@jemishgopani  When I changed 'UIAutomator2' to 'Flutter', my native tests stopped working.

**Comment by jemishgopani** [comment]
@chughrahul Use the below line before you want to use NATIVE commands.
`driver.context("NATIVE_APP"); // This line change your current FLUTTER context to NATIVE context`

**Comment by AutomationNext** [comment]
> driver.context("NATIVE_APP"); // This line change your current FLUTTER context to NATIVE context
This line worked for me but how do you switch it back to using flutter driver? 

I tried using 
>driver.context("Flutter"); 
but appium was still stuck using UiAutomator2 to locate elements. 
Thanks.

**Comment by dtonge2** [comment]
While switching context from flutter to Native app is working for me(using switchContext("NATIVE_APP")), but getting back to the Flutter context again is not working(using switchContext("FLUTTER"))

**Comment by KazuCocoa** [comment]
Could you create a new issue with the full server log (as GIST)?
I wonder the flutter context disconnected the websocket session.
