### ISSUE TITLE
python can't use waitFor or other execute command?

### ISSUE THREAD

**Issue by WangLiRu** [appium-userland/appium-flutter-driver#113]
When we use python to develop automation test with Flutter, I see that there are many wait methods or execute methods for nodejs in the sample, but it seems that they can't work in Python because they haven't been implemented yet?

When i run the command for below:   
 ```
try:
            finder = FlutterFinder()
            self.driver.execute('flutter:waitFor', finder.by_text('text'))
        except BaseException as ex:
            print(ex)
```
I will received this message : 'str' object does not support item assignment...
Is the syntax of Python different?

**Comment by sentrybottale** [comment]
Yes, the example for python is very limited onto the actions, and I can't find examples anywhere :(

**Comment by joyBymin** [comment]
my example for python like this, work well:

 def  waitFor_by_type(driver, locator):
        return driver.execute_script("flutter:waitFor", self.finder.by_type(locator), 30)

button_finder = waitFor_by_type(driver, locator)
button_element = FlutterElement(self.driver, button_finder)

**Comment by shr-avi** [comment]
Can we use this waitFor to check whether a element is displayed or not?

**Comment by alexborelli** [comment]
How do I use waitFor in Java? 
Didn't work for me

**Comment by KazuCocoa** [comment]
As https://github.com/appium-userland/appium-flutter-driver#commands , it seems this `flutter` command follows https://appium.io/docs/en/commands/mobile-command/
So, all appium clients can send `flutter:waitFor` as the execute_script command like the mobile-command. (theoretically)
