### ISSUE TITLE
Cannot launch debug apps on iOS 14 real devices

### ISSUE THREAD

**Issue by ajschwieterman** [appium-userland/appium-flutter-driver#115]
With the release of iOS 14, it has become impossible to test debug apps using the appium-flutter-driver.  When I launch my Flutter app on my iPhone, I get the following screenshot:

![IMG_5F87EAB178C3-1](https://user-images.githubusercontent.com/50152740/99112973-7e6bb780-25bc-11eb-981a-c5deb321dcd2.JPEG)

[Reference](https://flutter.dev/docs/development/ios-14)
appium-flutter-driver v0.0.26-1

**Comment by hex0cter** [comment]
I have the same problem. Please help! 😢

**Comment by ajschwieterman** [comment]
@hex0cter are you able to get a profile build of the app?  That has worked for me.

**Comment by hex0cter** [comment]
Hi @ajschwieterman! Could you please elaborate a bit more? I am new to both Appium and flutter. What is **a profile build of the app** and where am I supposed to get it? Any help is appreciated.

**Comment by ajschwieterman** [comment]
Hi @hex0cter Ask the developer who built the Flutter app your testing to build it in profile mode instead of debug mode.

https://flutter.dev/docs/testing/build-modes

**Comment by hex0cter** [comment]
@ajschwieterman I see what you mean now. Just tried `flutter build ios --flavor=firebase --profile`. The app can launch now on the phone now, but Appium is hanging with errors like this:
```
2021-01-15 11:18:09:160 - [debug] [BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
2021-01-15 11:18:09:160 - [debug] [BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
2021-01-15 11:18:09:169 - [FlutterDriver] Attempt #1
2021-01-15 11:18:09:169 - [FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:49188/z9m-jhVNBsY=/ws
2021-01-15 11:18:09:173 - [FlutterDriver] [object Object]
2021-01-15 11:18:09:173 - [FlutterDriver] Check Dart Observatory URI ws://127.0.0.1:49188/z9m-jhVNBsY=/ws
2021-01-15 11:18:09:174 - [FlutterDriver] Waiting 300 seconds before trying...
```
I saw some discussion on https://github.com/truongsinh/appium-flutter-driver/issues, but still haven't figured out any workaround yet.

**Comment by Reppinger** [comment]
@hex0cter Your build will still need the flutter driver extension for appium-flutter-driver to work.
```
void main() {
  // This line enables the extension
  enableFlutterDriverExtension();

  // Call the `main()` function of your app or call `runApp` with any widget you
  // are interested in testing.
  app.main();
}

```

**Comment by hex0cter** [comment]
Yes I had that enabled before building the app.

**Comment by ajschwieterman** [comment]
@hex0cter Have a look at this issue.

**Comment by hex0cter** [comment]
@ajschwieterman I tried the patch from now on with minor changes in it:

![image](https://user-images.githubusercontent.com/9008480/104775305-6a893100-5778-11eb-8538-f94366555b6b.png)

I tested two apps including the example app from https://github.com/truongsinh/appium-flutter-driver/tree/master/example/flutter_app_under_test (both built with --profile).  This error has gone now:
```
[FlutterDriver] Check Dart Observatory URI ws://127.0.0.1:49188/z9m-jhVNBsY=/ws
[FlutterDriver] Waiting 300 seconds before trying...
```
but the test was hanging for both apps. And Appium stalls here:
```
2021-01-15 21:24:18:685 - [FlutterDriver] DANIEL HAN: Running on iOS real device, doing "iproxy" now
2021-01-15 21:24:18:685 - [debug] [FlutterDriver] iproxy 57665:57665 -u 00008020-001D0D1C0E880***
```
It seems the `iproxy` command never returns. Maybe it should run in the background?

**Comment by hex0cter** [comment]
Removing `-u udid` generated the same result. However I managed to make it work after running `iproxy` in the background:
```
    spawn('iproxy', [`${urlObject.port}:${urlObject.port}`, '-u', udid], {detached: true})
```
The might be a small delay needed to make it more stable. I will try to make a Pull Request later.

The python library is also a little broken for Python3.  I had to add the following line into https://github.com/truongsinh/appium-flutter-driver/blob/master/finder/python/appium_flutter_finder/__init__.py
```python
from .flutter_finder import FlutterElement, FlutterFinder
```

Last thing worthy mentioning is the normal methods for `appium.webdriver` such as `find_element_by_accessibility_id` does not work any more. Appium complains:
```python
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'accessibility id' is not supported for this session
```
so I might have to rewrite all selectors using `flutter_finder`.

Thanks for all the help @ajschwieterman!

**Comment by ajschwieterman** [comment]
@hex0cter No problem!  I'll update my local copy of the repo with your suggested changes.  And I support you submitting the pull request!

If you switch your context using `driver.context("NATIVE_APP");`, then you can use the traditional Appium finders.  When you launch a Flutter app in Appium, the context is set to `FLUTTER`.

**Comment by hex0cter** [comment]
That is a super helpful tip! Thanks again for that. It would save me a lot of time.

I did notice one thing though. Now I set the context to **Native** by `driver.switch_to.context('NATIVE_APP')`, and am able to use Appium inspector to check the element. However in the inspector I cannot really locate any element. Here is a screenshot of what I get:

![image](https://user-images.githubusercontent.com/9008480/104783477-6532e300-5786-11eb-8320-695d168a71fd.png)

I found this issue with both the [example app](https://github.com/truongsinh/appium-flutter-driver/tree/master/example/flutter_app_under_test) and my own app. It makes the traditional selectors useless. Do you have hints for that? 🙏

**Comment by shibupanda** [comment]
HI @hex0cter 
Please have look on this PR and if possible build locally. I am not able to work much because there is no volunteer I get who can test for us. @ajschwieterman put some comments please have a look.
https://github.com/truongsinh/appium-flutter-driver/pull/92

And yes for flutter the finders are different compare to traditional selectors so no make sense to add those.

**Comment by hex0cter** [comment]
@shibupanda I am trying to test it now.

One more question regarding the selectors, as the traditional selectors do not work any more, are there any other inspectors/tools available to check the element tree when developing tests?

**Comment by shibupanda** [comment]
@hex0cter there is a plugin available in intellij I guess to inspect flutter related finder. There is no such tool created externally to inspect let's have a plan to do that but I need more collaborate who can do some RnD on it I can only guide due to time constraints.

**Comment by hex0cter** [comment]
Thanks @shibupanda! Could you please let me know the name of the plugin? Are there any instructions on how to use it? I am not a flutter developer. Any tips on this would be appreciated.

**Comment by ahmer-hash** [comment]
@hex0cter did you managed to resolve the issue by creating --profile build? I tried the same but it seems that ext.flutter.driver not recognized. However, I included the flutter_driver dependency under dev_dependencies in pubsec.yaml file. 
Any lead will be much appreciated.

Note: I am calling enableFlutterDriverExtension() into main() method.

**Comment by hex0cter** [comment]
@ahmer-hash It worked for me. This is how I did it:

* Add flutter_driver into the dev dependencies, my pubspec.yaml looks like this
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  flutter_driver:
    sdk: flutter
```
* In `lib/main.dart`, add
```
+ import 'package:flutter_driver/driver_extension.dart';
```
and 
```
 void main() async {
+  enableFlutterDriverExtension();
   WidgetsFlutterBinding.ensureInitialized();
```
* flutter build ios --profile. 

Then the app can be loaded to the phone. 

There is a flutter app example here: https://github.com/truongsinh/appium-flutter-driver/tree/master/example/flutter_app_under_test. I suggest you try it out if your own app still doesn't work.

**Comment by hex0cter** [comment]
> @hex0cter there is a plugin available in intellij I guess to inspect flutter related finder. There is no such tool created externally to inspect let's have a plan to do that but I need more collaborate who can do some RnD on it I can only guide due to time constraints.

Just in case anyone else is looking for the flutter inspector, in IntelliJ when the app is started in debugging more, there is a button called `Open DevTools`. Clicking on it will display the widget tree.

![image](https://user-images.githubusercontent.com/9008480/106811487-aecc6a80-666e-11eb-99d8-f7badf5bc939.png)

**Comment by ajschwieterman** [comment]
@hex0cter @shibupanda If I execute `ios-deploy --noinstall --justlaunch --bundle <your Flutter project root>/ios/Debug-iphoneos/Runner.app` with the debug Flutter app installed, I can launch a debug Flutter app on iOS 14+.  Is there a way this can somehow be added to the appium-flutter-driver?

https://github.com/flutter/flutter/issues/60657#issuecomment-688478590

**Comment by hex0cter** [comment]
@ajschwieterman I was trying to play with what you mentioned, but I cannot copy the app to the device using `ios-deploy`:

```
[21:36:47]  /Volumes/case-sensitive/tmp/demo  $ flutter build ios --debug
Building dev.danielhan.demo.halting-krypton-cast-pinch for device (ios)...
Automatically signing iOS for device deployment using specified development team in Xcode project: G5597LS73V
Running Xcode build...
 └─Compiling, linking and signing...                        13.2s
Xcode build done.                                           27.1s
Built /Volumes/case-sensitive/tmp/demo/build/ios/iphoneos/Runner.app.
[21:37:25]  /Volumes/case-sensitive/tmp/demo  $ ios-deploy --noinstall --justlaunch --bundle /Volumes/case-sensitive/tmp/demo/build/ios/iphoneos/Runner.app
[....] Waiting for iOS device to be connected
[....] Using 00008020-001D0D1C0E88003A (D321AP, iPhone XS, iphoneos, arm64e) a.k.a. 'd4n13l h4n'.
------ Debug phase ------
Starting debug of 00008020-001D0D1C0E88003A (D321AP, iPhone XS, iphoneos, arm64e) a.k.a. 'd4n13l h4n' connected through USB...
[  0%] Looking up developer disk image
[ 95%] Developer disk image mounted successfully
[1]    18210 segmentation fault  ios-deploy --noinstall --justlaunch --bundle
[21:37:45]  /Volumes/case-sensitive/tmp/demo  $ ios-deploy --version
1.11.3
```
I did notice that the build path on my machine is different than yours. On my machine it is `build/ios/iphoneos/Runner.app` instead of `ios/Debug-iphoneos/Runner.app`. How did you build the app?

**Comment by ajschwieterman** [comment]
@hex0cter Here are the steps I took.

1. Build the iOS debug build `flutter build ios --debug`
2. Install the app manually to the iPhone `ideviceinstaller -i build/ios/iphoneos/Runner.app`
2. Launch the app on the phone `ios-deploy --noinstall  --bundle build/ios/Debug-iphoneos/Runner.app`

**Comment by hex0cter** [comment]
Thanks @ajschwieterman. That helps! Now I am able to install the app to the phone with these commands. However if I launch it, it still get this `In iOS 14+, debug mode Flutter apps can only...." error. Not sure if I missed anything.

**Comment by ajschwieterman** [comment]
@hex0cter did you try to launch the app with `ios-deploy --noinstall --bundle build/ios/Debug-iphoneos/Runner.app`?

**Comment by hex0cter** [comment]
Thanks @ajschwieterman. 

So `ios-deploy --noinstall --bundle build/ios/Debug-iphoneos/Runner.app` works. Not super stable as it is failing sometimes.

If I run `ios-deploy --justlaunch --noinstall --bundle build/ios/Debug-iphoneos/Runner.app` I always get the error of `In iOS 14+, debug mode Flutter apps can only....`.

I remember appium is using ios-deploy internally, so maybe there is something we can do about it.

**Comment by ajschwieterman** [comment]
Thanks @hex0cter 

If you can lead me to where Appium uses `ios-deploy`, I can make some changes to my local repo and test them out.

**Comment by hex0cter** [comment]
@ajschwieterman Please check this log and search ios-deploy in it. It is a fallback for installation. You just need to give the `appPushTimeout` a very small value to trigger it.

[appium1.log](https://github.com/truongsinh/appium-flutter-driver/files/6156980/appium1.log)

Hope this helps.

**Comment by ajschwieterman** [comment]
@hex0cter I think I found where the driver launches the app; it's within the WebDriverAgent.

https://github.com/appium/WebDriverAgent/blob/fe56167ae0d7df3a9631432e4c3e39e689e4272f/WebDriverAgentLib/Commands/FBSessionCommands.m#L120

**Comment by hex0cter** [comment]
@ajschwieterman thanks for sharing. I also had a look earlier today at this, but ended up here: https://github.com/truongsinh/appium-flutter-driver/blob/5b5d9e826d000692222be67015f7ee4fbc413029/driver/lib/sessions/ios.ts#L20-L22 and here: https://github.com/appium/appium-xcuitest-driver/blob/8632cc98e2eee7c5875d79f92ecf38cfdd42acf5/lib/ios-deploy.js#L51-L53. Not sure if it is the right path but just wanted to share in case useful.

**Comment by ajschwieterman** [comment]
@hex0cter What files are contained in `/Volumes/case-sensitive/git/scrive_app_test/utils/../builds/ios-physical.zip`?

**Comment by hex0cter** [comment]
It’s a flutter app we are testing.  A zipped Runner.app.

**Comment by ajschwieterman** [comment]
@hex0cter I can't seem to reproduce the logs you attached earlier.

**Comment by hex0cter** [comment]
That’s odd. I can always trigger the fallback for installation. But I have some problems using ios-deploy to install my app. Nothing happens on the phone when I run the command from the terminal. (The demo app works though)

**Comment by ajschwieterman** [comment]
If I add the `--debug` option to the `ios-deploy` command in the appium-flutter-driver repo, I can get the app to launch, but it stays stuck and doesn't proceed.

The issue at hand is a debugger/host computer isn't being associated/attached to the session, which I have no clue how to do.

**Comment by hex0cter** [comment]
Me neither. Theoretically if an IDE or “flutter run” can do it, appium should also be able to do it. But I have no idea how it is done.

**Comment by ajschwieterman** [comment]
> Me neither. Theoretically if an IDE or “flutter run” can do it, appium should also be able to do it. But I have no idea how it is done.

@Reppinger @shibupanda @ahmer-hash @KazuCocoa Any idea on how to do this?

**Comment by KazuCocoa** [comment]
No for now since I don't know what `flutter run` does behind the command.
The first step should be to track what the command does.

If their requirement is attaching to a running process, I guess it is difficult to guarantee via XCTest framework since the XCTest's launch method tries to restart the app under test's process (according to Apple's documentation)

**Comment by ajschwieterman** [comment]
@hex0cter Here are the steps I took to achieve consistent app launches:

1. In the root directory of `appium-flutter-driver` go to file `node_modules/appium-xcuitest-driver/build/lib/ios-deploy.js`.
2. Add `let proc;` global variable.
3. Change `await exec(IOS_DEPLOY, [
          '--id', this.udid,
          '--bundle', app,
        ]);` to 
 ```
proc = new _teen_process.SubProcess(IOS_DEPLOY, ['--id', this.udid, '--bundle', app, '--debug']);
proc.start();
``` 
4. Add the following code to the `remove(bundleId)` method
```
try {
  await proc.stop();
} catch (err1) {

}
```
5. In your Appium tests, add `desiredCapabilities.setCapability("appPushTimeout", 50);` to your setup.
6. In your Appium tests, add `driver.removeApp(<app_package_name>);` to your cleanup.

I needed a way to stop the `ios-deploy` process when I was finished with my tests, so I added step 4's code to the `remove` method knowing that I will more than likely remove an app from the phone after a test.  I know this is changing the code of the `appium-xcuitest-driver` code and not the `appium-flutter-driver` code, but this is a work-around.

Let me know if you have any improvements or suggestions.   :)

**Comment by hex0cter** [comment]
@ajschwieterman Sorry I haven't been able to test it so far. Will have a look as soon as I can.

**Comment by KazuCocoa** [comment]
Close this issue as nothing might not do by this driver.

**Comment by marceloadsj** [comment]
Following a discussion on the Flutter repo: https://github.com/flutter/flutter/issues/120789
I guess the work would need to be done on Appium side (maybe not on this driver, but on main Appium tooling?!).

@KazuCocoa I would appreciate your opinion on this topic, please? :)

**Comment by KazuCocoa** [comment]
Theoretically, it could. Appium XCUITest driver launches the app under test via XCTest API to follow how iOS launches the app as a black-box testing tool.

Maybe there are two options. Adding the possibility in https://github.com/appium/appium-ios-device, or use https://github.com/ios-control/ios-deploy or other tools like https://github.com/danielpaulus/go-ios to launch the app with a debugger for this driver specific. The appium-ios-device already has an ability to launch an app process via instrument, so potentially it could achieve with a few changes, or it needs more implementation.



By using an existing method, you also could manage the starting app part on your test code and gives the observatory URL with `appium:observatoryWsUri` capability. Then, this driver attempts to attach the websocekt against the given URL. In this case, you also could launch the app under test with flutter command as same.
