### ISSUE TITLE
Not taking into consideration of options passed to base driver while setting up of new ios driver for appium-flutter-driver

### ISSUE THREAD

**Issue by rishav-csenitjsr** [appium-userland/appium-flutter-driver#124]
I was passing `wdaLocalPort` to appium while running flutter session but only `javascriptEnabled` is passed in `iosArgs` while setting up of new Ios driver [here](https://github.com/truongsinh/appium-flutter-driver/blob/master/driver/lib/sessions/ios.ts#L7-L12) 
Ideally, we should pass this `[this.proxydriver, this.socket] = await startIOSSession(caps, this.opts);` instead of [this.proxydriver, this.socket] = await startIOSSession(caps); [here](https://github.com/truongsinh/appium-flutter-driver/blob/master/driver/lib/sessions/session.ts#L15)

**Comment by shibupanda** [comment]
@rishav-csenitjsr 
Please create a PR will review.

**Comment by KazuCocoa** [comment]
i guess this is already fixed since I've previously fixed W3C spec update...

**Comment by rishav-csenitjsr** [comment]
Thanks @KazuCocoa. This has been fixed.
