### ISSUE TITLE
How to get one of the elements if the finder matched more than one?

### ISSUE THREAD

**Issue by hex0cter** [appium-userland/appium-flutter-driver#140]
With the finder from appium-flutter-driver, sometimes I got more than one element returned. Then if I do another API call, it returns `Bad state: Too many elements`. For example, in the code below, if there are more than one widgets with the same text:
```python
from appium_flutter_finder import FlutterElement, FlutterFinder

finder = FlutterFinder()
text_finder = finder.by_text(text)
element = FlutterElement(driver, text_finder)
   
print(element.text)
```
the last line will raise:
```python
(<class 'selenium.common.exceptions.WebDriverException'>, WebDriverException('An unknown server-side error occurred while processing the command. Original error: Cannot execute command get_text, server reponse {\n  "isError": true,\n  "response": "Uncaught extension error while executing get_text: Bad state: Too many elements\\n#0      Iterable.single (dart:core/iterable.dart:560)\\n#1      FlutterDriverExtension._getText (package:flutter_driver/src/extension/extension.dart:625)\\n<asynchronous suspension>\\n#2      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:273)\\n<asynchronous suspension>\\n#3      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:547)\\n<asynchronous suspension>\\n",\n  "type": "_extensionType",\n  "method": "ext.flutter.driver"\n}', None, None), <traceback object at 0x102059180>)
```

If I call `element[0].text`, I will get `(<class 'TypeError'>, TypeError("'FlutterElement' object is not subscriptable"), <traceback object at 0x10d001600>)`.

So my question is, how can I get one of the elements if the finder matched several widgets? Any help is appreciated. 🙏

**Comment by shibupanda** [comment]
@hex0cter 
Below link may help I guess flutter community has not yet exposed finders to find elements and perform action in the basis of index. Work around to assign different key.

https://github.com/flutter/flutter/issues/22868

**Comment by hex0cter** [comment]
Thanks for confirming this @shibupanda. One more question, is there any nice way to check the number of matched elements without getting the exception?

In the example above, before calling `element.text`, we don't know if the element exists at all, or if more than one elements are matched. In either case, when I call `element.text`, I only get exceptions.

**Comment by GowthamReddyAmbati** [comment]
@hex0cter  I'm also looking for a solution to the same issue.

**Comment by litan1984** [comment]
Facing same issue, while identifying dynamic list view widget with same type.

**Comment by Abhi011999** [comment]
Same here, it seems like `find_elements()` could work in this case but it's not supported yet.
If we could somehow get a list of the elements, we can do many things, like checking if the number of items matches the expected number or individually clicking on any element.

**Comment by KazuCocoa** [comment]
Perhaps currently this is a flutter (or flutter_driver by Flutter team) limitation.

**Comment by ehabibov** [comment]
+1, it is annoying not having option to get list of elements. I also received "Bad state: Too many elements" recently and was looking for possible solutions.

There are Finders that could return multiple items but it is very hard (imo) to interact with if exposed. _flutter_test_ has such one abstract class - [Finder](https://api.flutter.dev/flutter/flutter_test/Finder-class.html).

> Finder class
>
> Searches a widget tree and returns nodes that match a particular pattern.
> 
> [allCandidates](https://api.flutter.dev/flutter/flutter_test/Finder/allCandidates.html) → [Iterable](https://api.flutter.dev/flutter/dart-core/Iterable-class.html)<[Element](https://api.flutter.dev/flutter/widgets/Element-class.html)>
> Returns all the Elements that will be considered by this finder.

Well, as I already spent time on that, here are some obvious things:

Some traces how client <->driver_extension commands work:
* waitFor method: https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/driver/driver.dart#L224
* WaitFor subclass: https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/common/find.dart#L50
* sendCommand method: https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/driver/vmservice_driver.dart#L317
* send/receive: https://github.com/flutter/flutter/blob/7d85a585da7572a495960d93324cbe1f8ac0be13/packages/flutter_driver/lib/src/driver/vmservice_driver.dart#L327

Additionally command handler on extension side: https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/extension/extension.dart#L367

It is not clear how search is done under hood as we can only log client<->driver_extension interaction, but not driver_extension<->app. And here some examples of outgoing/incoming payloads:
```
[debug] [FlutterDriver] >>> {"command":"waitFor","finderType":"ByText","text":"Skip for now","timeout":10000}
[debug] [FlutterDriver] <<< {"isError":false,"response":{},"type":"_extensionType","method":"ext.flutter.driver"} | previous command waitFor

[debug] [FlutterDriver] >>> {"command":"get_text","finderType":"ByText","text":"Skip for now"}
[debug] [FlutterDriver] <<< {"isError":false,"response":{"text":"Skip for now"},"type":"_extensionType","method":"ext.flutter.driver"} | previous command get_text

[debug] [FlutterDriver] >>> {"command":"tap","finderType":"ByText","text":"Skip for now"}
[debug] [FlutterDriver] <<< {"isError":false,"response":{},"type":"_extensionType","method":"ext.flutter.driver"} | previous command tap
```

**Comment by martin-braun** [comment]
@ehabibov Tell me something, without telling me something.

Anyways, you can approach this problem by using `descendant` with `firstMatchOnly`:

```dart
  SerializableFinder findFirst({required SerializableFinder of}) =>
      find.descendant(
          of: find.byType("MaterialApp"), matching: of, firstMatchOnly: true);
```
