### ISSUE TITLE
How I verify is the switch is checked?

### ISSUE THREAD

**Issue by alexborelli1** [appium-userland/appium-flutter-driver#160]
Hello

I need help. 

How I verify is the switch is checked with Appium Flutter Driver?

**Comment by sanneabhilash** [comment]
Could not find a direct approach to this yet with flutter_driver. Possible workarounds I can think of:

- Use element coordinates to take a screenshot and compare the images of the switch to identify if it is selected or not (OR)
- Switch to native context and use the IsSelected or IsChecked attributes

**Comment by KazuCocoa** [comment]
The workaround was addressed as possible ways as this driver
