### ISSUE TITLE
used set_value("key_username") can't set value successfully

### ISSUE THREAD

**Issue by hellonkm** [appium-userland/appium-flutter-driver#179]

**Comment by KazuCocoa** [comment]
Please attach the full log.

---

If  you meant `enterText` in Flutterr, you should do as:
> driver.elementSendKeys(find.byType('TextField'), 'I can enter text') (no focus required)
driver.elementClick(find.byType('TextField')); driver.execute('flutter:enterText', 'I can enter text') (focus required by tap/click first)

https://github.com/appium-userland/appium-flutter-driver
