### ISSUE TITLE
Appium-flutter-driver is compatible with flutter v2 ?

### ISSUE THREAD

**Issue by dvyAb** [appium-userland/appium-flutter-driver#180]
appium-flutter-driver : 0.0.29
appium : 1.21.0

Hello,

We have an application with flutter V2, when we try to connect with appium-flutter-driver.
The driver cannot connect and does not recognize objects.

Do you have any idea?, thanks
It's compatible ?

**Comment by KazuCocoa** [comment]
When I tried Flutter 2.2.0 (https://github.com/KazuCocoa/my_flutter_app3 ) sample project, this driver worked.
This project depends on `flutter_driver` package, so this should work during the package works.

**Comment by KazuCocoa** [comment]
Let us know (create issues) when you have any issues and they work via flutter_driver https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html package by Flutter team.
This driver repository does not work on environment that does not with the flutter_driver.
