### ISSUE TITLE
 Calling from not trusted UID

### ISSUE THREAD

**Issue by ichanmrg** [appium-userland/appium-flutter-driver#194]
I am having this issue too (Appium v 1.21.0 is causing UIAutomator to crash):

`09-14 12:26:25.263: W/Binder(20531):java.lang.SecurityException: Calling from not trusted UID! 09-14 12:26:25.263: W/Binder(20531): at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:413) 09-14 12:26:25.263: W/Binder(20531): at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:317) 09-14 12:26:25.263: W/Binder(20531): at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:209) 09-14 12:26:25.263: W/Binder(20531): at android.os.Binder.execTransact(Binder.java:565) 09-14 12:26:25.274: E/HsmCoreServiceImpl(1276):onTransact in code is: 102 09-14 12:26:25.274: I/MediaProcessHandler(1276):processOp opType: 1, uid: 12708, pid: 20548 09-14 12:26:25.274: W/MediaProcessHandler(1276):remove target not exist, maybe the UI process: uid: 12708, pid: 20548 09-14 12:26:25.291: I/BrcmNfcNfa(2580):nfa_ee_api_get_max_aid_config_length: 660 09-14 12:26:25.988: I/EventHub(1276):EventHub monitor: no key events in the past 125947s, no motion events in the past 93632s 09-14 12:26:26.815: I/XmlParser(21489):startElement itemName:resource user:1159282728`

**Comment by KazuCocoa** [comment]
It seems the error is by OS level (and some specific devices(?)).
https://stackoverflow.com/questions/51360801/calling-from-not-trusted-uid

Then, nothing can do in Appium layer, unfortunately.
