### ISSUE TITLE
Does Appium flutter driver has implementation for below methods?

### ISSUE THREAD

**Issue by GowthamReddyAmbati** [appium-userland/appium-flutter-driver#196]
find_all_elements (to find a list of elements which are having some common attribute/locator)
 is_displayed()
is_selected()
is_enabled()
driver.open_notifications()
driver.press_keycode(66)
driver.toggle_wifi()
driver.back()
driver.hide_keyboard()
driver.press_keycode()
driver.background_app()

**Comment by KazuCocoa** [comment]
I think you can do the below in `NATIVE_APP` context. Then, this driver sends commands to UIA2/XCUITest driver.

```
driver.open_notifications()
driver.press_keycode(66)
driver.toggle_wifi()
driver.back()
driver.hide_keyboard()
driver.press_keycode()
driver.background_app()
```

Do you know of if flutter_driver package provide visibility attribute etc?
Afaik, probably the don't. Then, this driver also cannot add it in flutter context.
https://api.flutter.dev/flutter/flutter_driver/FlutterDriver-class.html#instance-methods

**Comment by GowthamReddyAmbati** [comment]
Thank you for your reply @KazuCocoa ,

would you please let me know the alternative for the find_elements?
find_all_elements (to find a list of elements which are having some common attribute/locator)

**Comment by KazuCocoa** [comment]
Probably nothing.
https://api.flutter.dev/flutter/flutter_driver/FlutterDriver-class.html#instance-methods is everything we can do.

**Comment by KazuCocoa** [comment]
We're welcome PRs to achieve `find_all_elements` if anyone found the way.

**Comment by ktnishide** [comment]
did anyone found the way? :P
