### ISSUE TITLE
Flutter Driver will be deprecated 

### ISSUE THREAD

**Issue by shammi-priyaadrshi** [appium-userland/appium-flutter-driver#210]
The current Flutter Driver tests will be deprecated and it’s recommended to move to the new Integration Tests.
We know Appium is using flutter driver under the hood, what will happen if flutter driver is deprecated? 
Any plan for Appium flutter automation?

**Comment by KazuCocoa** [comment]
Then, this driver will not work when no longer Flutter team's flutter_driver package will not work.

> Any plan for Appium flutter automation?

If this meant alternative of this flutter-driver, I do not have any plans for now.
Perhaps we can replace flutter_driver package with integeration_test package and replace methods properly, some automation to DartVM may work in debug build. (PRs will be welcome to try this if someone have interested in this)


So far, Flutter exposes their elements to accessibility features in Android/iOS. Then, UIA2/XCUITest drivers can work for Flutter app via the accessibility features. Some automations should work with this. (This way is the same as current methods to test a release build)

**Comment by neillfontes-klar** [comment]
@shammi-priyaadrshi 

> The current Flutter Driver tests will be deprecated and it is recommended to move to the new Integration Tests.

Do you have a source on this?

**Comment by tpberntsen** [comment]
@neillfontes-klar: I found the official documentation page "Migrating from flutter_driver" (https://docs.flutter.dev/testing/integration-tests/migration) to reflect @shammi-priyaadrshi's description, although I cannot read from the page contents when it is expected to be deprecated.

**Comment by neillfontes-klar** [comment]
Hi @tpberntsen, thanks, I have read that already. 

It just talks about a migration but not deprecation, so would be good to have a reliable source on it, since it is a bit subjective at this point.
