### ISSUE TITLE
Appium Flutter not working for iOS device (TypeError: Cannot read property 'match' of undefined)

### ISSUE THREAD

**Issue by surendra-savita-30060677** [appium-userland/appium-flutter-driver#211]
While running Java unit code in Android device, its working fine.But in case of iOS its not working, always getting below exception:

 Encountered internal error running command**: **TypeError: Cannot read property 'match' of undefined****
[debug] [35m[W3C][39m     at Object.exports.processLogToGetobservatory (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/build/driver/lib/sessions/observatory.js:118:9)
[debug] [35m[W3C][39m     at Object.exports.getObservatoryWsUri (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:77:21)
[debug] [35m[W3C][39m     at Object.exports.startIOSSession (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:31:30)
[debug] [35m[W3C][39m     at runMicrotasks (<anonymous>)
[debug] [35m[W3C][39m     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[debug] [35m[W3C][39m     at FlutterDriver.exports.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/session.ts:15:47)
[debug] [35m[W3C][39m     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:387:35)

IDE : Eclipse
Programming language : Java
appium-flutter-driver - 0.0.33
Appium Version : 1.21
Code : 
 DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability("platformVersion", "15.1");
    capabilities.setCapability("retryBackoffTime", "500");
    capabilities.setCapability("maxRetryCount", "20");
    capabilities.setCapability("deviceName", "iPhone 12 Pro");
    capabilities.setCapability("noReset", true);
    capabilities.setCapability("udid", "00008101-001A6564XXXXX");
    capabilities.setCapability("app", "path of ipa");
    capabilities.setCapability("automationName", "flutter");

Could you please resolve above issue........... or did i miss something......

**Comment by KazuCocoa** [comment]
Please attach the full appium log to see the detail.

Possibly https://github.com/appium-userland/appium-flutter-driver/issues/115 is related.

**Comment by surendra-savita-30060677** [comment]
[info] [35m[HTTP][39m Waiting until the server is closed
[info] [35m[HTTP][39m Received server close event
[info] [35m[Appium][39m Welcome to Appium v1.21.0
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   address: 127.0.0.1
[info] [35m[Appium][39m   relaxedSecurityEnabled: true
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m Appium REST http interface listener started on 127.0.0.1:4723[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"agentPathx":"usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj","app":"/Users/xxxxxxxxxx/Downloads/hello_world.ipa","automationName":"flutter","bootstrapPath":"/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent","deviceName":"iPhone 12 Pro","includeSafariInWebviews":true,"platformName":"iOS","platformVersion":"15.1","udid":"00008101-001A6XXXXXXXXXX","xcodeOrgId":"2XXXXXXXXX","xcodeSigninId":"iPhone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{"agentPathx":"usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj","app":"/Users/XXXXXXXXXX/Downloads/hello_world.ipa","automationName":"flutter","bootstrapPath":"/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent","deviceName":"iPhone 12 Pro","includeSafariInWebviews":true,"platformName":"iOS","platformVersion":"15.1","udid":"00008101-001A65640C2A001E","xcodeOrgId":"XXXXXXXXX","xcodeSigninId":"iPhone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1639022792366 (09:36:32 GMT+0530 (India Standard Time))
[info] [35m[Appium][39m Appium v1.21.0 creating new FlutterDriver (v0.0.28) session
[info] [35m[Appium][39m Applying relaxed security to 'FlutterDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {
[debug] [35m[BaseDriver][39m   "agentPathx": "usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj",
[debug] [35m[BaseDriver][39m   "app": "/Users/surendrakumarsavita/Downloads/hello_world.ipa",
[debug] [35m[BaseDriver][39m   "automationName": "flutter",
[debug] [35m[BaseDriver][39m   "bootstrapPath": "/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent",
[debug] [35m[BaseDriver][39m   "deviceName": "iPhone 12 Pro",
[debug] [35m[BaseDriver][39m   "includeSafariInWebviews": true,
[debug] [35m[BaseDriver][39m   "platformName": "iOS",
[debug] [35m[BaseDriver][39m   "platformVersion": "15.1",
[debug] [35m[BaseDriver][39m   "udid": "00008101-001AXXXXXXXXXXX",
[debug] [35m[BaseDriver][39m   "xcodeOrgId": "2S54AFLBFB",
[debug] [35m[BaseDriver][39m   "xcodeSigninId": "iPhone Developer",
[debug] [35m[BaseDriver][39m   "newCommandTimeout": 0,
[debug] [35m[BaseDriver][39m   "connectHardwareKeyboard": true
[debug] [35m[BaseDriver][39m }
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
[warn] [35m[BaseDriver][39m   agentPathx
[warn] [35m[BaseDriver][39m   bootstrapPath
[warn] [35m[BaseDriver][39m   includeSafariInWebviews
[warn] [35m[BaseDriver][39m   xcodeOrgId
[warn] [35m[BaseDriver][39m   xcodeSigninId
[warn] [35m[BaseDriver][39m   connectHardwareKeyboard
[info] [35m[BaseDriver][39m Session created with session id: a39a0de8-7480-42bb-af8d-f8137198b52a
[info] [35m[FlutterDriver][39m Starting an IOS proxy session
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {
[debug] [35m[BaseDriver][39m   "agentPathx": "usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj",
[debug] [35m[BaseDriver][39m   "app": "/Users/XXXXXXXXXXXX/Downloads/hello_world.ipa",
[debug] [35m[BaseDriver][39m   "automationName": "flutter",
[debug] [35m[BaseDriver][39m   "bootstrapPath": "/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent",
[debug] [35m[BaseDriver][39m   "deviceName": "iPhone 12 Pro",
[debug] [35m[BaseDriver][39m   "includeSafariInWebviews": true,
[debug] [35m[BaseDriver][39m   "platformName": "iOS",
[debug] [35m[BaseDriver][39m   "platformVersion": "15.1",
[debug] [35m[BaseDriver][39m   "udid": "00008101-001A6564XXXXXXXXX",
[debug] [35m[BaseDriver][39m   "xcodeOrgId": "2S54AFLBFB",
[debug] [35m[BaseDriver][39m   "xcodeSigninId": "iPhone Developer",
[debug] [35m[BaseDriver][39m   "newCommandTimeout": 0,
[debug] [35m[BaseDriver][39m   "connectHardwareKeyboard": true
[debug] [35m[BaseDriver][39m }
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
[warn] [35m[BaseDriver][39m   agentPathx
[warn] [35m[BaseDriver][39m   xcodeSigninId
[info] [35m[BaseDriver][39m Session created with session id: 6bcb3c7a-5016-4669-9f39-43616b0ebfed
[debug] [35m[XCUITest][39m Current user: 'XXXXXXX'
[debug] [35m[XCUITest][39m Available devices: 00008101-001A65640C2XXXXXX
[debug] [35m[XCUITest][39m Creating iDevice object with udid '00008101-001A65640XXXXXXXX'
[info] [35m[XCUITest][39m Determining device to run tests on: udid: '00008101-001A65640XXXXX', real device: true
[debug] [35m[BaseDriver][39m Event 'xcodeDetailsRetrieved' logged at 1639022792409 (09:36:32 GMT+0530 (India Standard Time))
[info] [35m[BaseDriver][39m Using local app '/Users/XXXXXXXXX/Downloads/hello_world.ipa'
[info] [35m[BaseDriver][39m Will reuse previously cached application at '/var/folders/g7/684gknm13hsdk_gr_vq68t540000gp/T/2021117-90747-1f68hi.8hmgc/Runner.app'
[debug] [35m[BaseDriver][39m Event 'appConfigured' logged at 1639022792452 (09:36:32 GMT+0530 (India Standard Time))
[debug] [35m[XCUITest][39m Checking whether app '/var/folders/g7/684gknm13hsdk_gr_vq68t540000gp/T/2021117-90747-1f68hi.8hmgc/Runner.app' is actually present on file system
[debug] [35m[XCUITest][39m App is present
[debug] [35m[iOS][39m Getting bundle ID from app '/var/folders/g7/684gknm13hsdk_gr_vq68t540000gp/T/2021117-90747-1f68hi.8hmgc/Runner.app': 'com.XXXXX.testApp'
[debug] [35m[BaseDriver][39m Event 'resetStarted' logged at 1639022792452 (09:36:32 GMT+0530 (India Standard Time))
[debug] [35m[XCUITest][39m Reset: running ios real device reset flow
[debug] [35m[BaseDriver][39m Event 'resetComplete' logged at 1639022792452 (09:36:32 GMT+0530 (India Standard Time))
[info] [35m[WebDriverAgent][39m Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent'
[info] [35m[WebDriverAgent][39m Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'[debug] [35m[XCUITest][39m Crash reports root '/Users/XXXXXXXXXXXX/Library/Logs/CrashReporter/MobileDevice/iPhone 12 Pro Max' does not exist. Got nothing to gather.
[debug] [35m[BaseDriver][39m Event 'logCaptureStarted' logged at 1639022792681 (09:36:32 GMT+0530 (India Standard Time))
[info] [35m[XCUITest][39m Setting up real device
[debug] [35m[XCUITest][39m Verifying application platform
[debug] [35m[XCUITest][39m CFBundleSupportedPlatforms: ["iPhoneOS"][debug] [35m[XCUITest][39m Reset requested. Removing app with id 'com.AdaniKell.superApp' from the device[debug] [35m[XCUITest][39m Installing '/var/folders/g7/684gknm13hsdk_gr_vq68t540000gp/T/2021117-90747-1f68hi.8hmgc/Runner.app' on device with UUID '00008101-001A65640C2A001E'...[debug] [35m[Support][39m Traversed 14 directories and 60 files in 1768ms
[debug] [35m[XCUITest][39m Pushed the app files successfully after 1900ms[info] [35m[XCUITest][39m App installation succeeded after 2393ms
[debug] [35m[XCUITest][39m The app has been installed successfully.
[debug] [35m[BaseDriver][39m Event 'appInstalled' logged at 1639022795877 (09:36:35 GMT+0530 (India Standard Time))[debug] [35m[WebDriverAgent][39m No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[info] [35m[DevCon Factory][39m Requesting connection for device 00008101-001A6564XXXXXX on local port 8100, device port 8100
[debug] [35m[DevCon Factory][39m Cached connections count: 1
[info] [35m[DevCon Factory][39m Found cached connections on port #8100: ["00008101-001A6564XXXXXXX:8100"]
[warn] [35m[DevCon Factory][39m Port #8100 is busy. Did you quit the previous driver session(s) properly?
[info] [35m[DevCon Factory][39m Trying to release the port
[info] [35m[DevCon Factory][39m Releasing the listener for '00008101-001A65640CXXXXXXXX:8100'
[debug] [35m[iProxy@00008101:8100][39m Closing the connection
[info] [35m[iProxy@00008101:8100][39m The connection has been closed
[info] [35m[DevCon Factory][39m Port #8100 has been successfully released after 2ms
[info] [35m[DevCon Factory][39m Successfully requested the connection for 00008101-001A65640XXXXXXX:8100[debug] [35m[WebDriverAgent][39m Parsed BUILD_DIR configuration value: '/Users/XXXXXXXXXXX/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Build/Products'
[debug] [35m[WebDriverAgent][39m Got derived data root: '/Users/XXXXXXXXXX/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu'
[debug] [35m[XCUITest][39m Starting WebDriverAgent initialization with the synchronization key '/Users/XXXXXXXXXX/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu'
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"15.0","version":"15.1"},"ios":{"ip":"169.254.197.XX"},"ready":true,"build":{"upgradedAt":"1632042036000","time":"Dec  8 2021 16:05:34","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":"DAC50D82-4E1A-415C-8A11-XXXXXXXXXX"}
[debug] [35m[WebDriverAgent][39m Upgrade timestamp of the currently bundled WDA: 1632042036000
[debug] [35m[WebDriverAgent][39m Upgrade timestamp of the WDA on the device: 1632042036000
[info] [35m[WebDriverAgent][39m Will reuse previously cached WDA instance at 'http://127.0.0.1:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[debug] [35m[XCUITest][39m Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [35m[XCUITest][39m These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [35m[BaseDriver][39m Event 'wdaStartAttempted' logged at 1639022798224 (09:36:38 GMT+0530 (India Standard Time))
[info] [35m[WebDriverAgent][39m Using provided WebdriverAgent at 'http://127.0.0.1:8100/'
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"15.0","version":"15.1"},"ios":{"ip":"169.254.197.66"},"ready":true,"build":{"upgradedAt":"1632042036000","time":"Dec  8 2021 16:05:34","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":"DAC50D82-4E1A-415C-8A11-4C673427A820"}
[debug] [35m[BaseDriver][39m Event 'wdaSessionAttempted' logged at 1639022798232 (09:36:38 GMT+0530 (India Standard Time))
[debug] [35m[XCUITest][39m Sending createSession command to WDA
[debug] [35m[WD Proxy][39m Matched '/session' to command name 'createSession'
[debug] [35m[WD Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.XXXXXXXX.testApp","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":true}],"alwaysMatch":{}}}[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"sessionId":"9A75694F-49EA-437F-97CF-99C335996D9A","capabilities":{"device":"iphone","browserName":"hello_world","sdkVersion":"15.1","CFBundleIdentifier":"com.XXXXXX.testApp"}},"sessionId":"9A75694F-49EA-437F-97CF-99XXXXXXXXX"}
[info] [35m[WD Proxy][39m Determined the downstream protocol as 'W3C'
[debug] [35m[BaseDriver][39m Event 'wdaSessionStarted' logged at 1639022799788 (09:36:39 GMT+0530 (India Standard Time))
[debug] [35m[BaseDriver][39m Event 'wdaStarted' logged at 1639022799788 (09:36:39 GMT+0530 (India Standard Time))
[info] [35m[XCUITest][39m Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [35m[BaseDriver][39m Event 'orientationSet' logged at 1639022799788 (09:36:39 GMT+0530 (India Standard Time))
[debug] [35m[BaseDriver][39m The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[debug] [35m[BaseDriver][39m The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[debug] [35m[FlutterDriver][39m Deleting Flutter Driver session
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1639022799827 (09:36:39 GMT+0530 (India Standard Time))
[debug] [35m[MJSONWP][39m Encountered internal error running command: TypeError: Cannot read property 'match' of undefined
[debug] [35m[MJSONWP][39m     at Object.exports.processLogToGetobservatory (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/build/driver/lib/sessions/observatory.js:118:9)
[debug] [35m[MJSONWP][39m     at Object.exports.getObservatoryWsUri (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:31:21)
[debug] [35m[MJSONWP][39m     at Object.exports.startIOSSession (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:23:34)
[debug] [35m[MJSONWP][39m     at runMicrotasks (<anonymous>)
[debug] [35m[MJSONWP][39m     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[debug] [35m[MJSONWP][39m     at FlutterDriver.exports.createSession (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/session.ts:15:47)
[debug] [35m[MJSONWP][39m     at AppiumDriver.createSession (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:387:35)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m7465 ms - 178[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mDELETE[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[HTTP][39m No route found for /wd/hub/session
[info] [35m[HTTP][39m [37m<-- DELETE /wd/hub/session [39m[33m404[39m [90m9 ms - 211[39m
[info] [35m[HTTP][39m [90m[39m

**Comment by KazuCocoa** [comment]
Could you try out appium 1.22? (flutter driver is 0.0.32)

**Comment by jamesvanhorn** [comment]
I found a workaround by uninstall the app manually between launches. The call to driver.quit() (im in java) was not actually closing the app. After I close and uninstall manually, I saw in my console the message that FlutterDriver had closed the connection.

Next app startup / session worked fine then. Not sure how to fix though, as I can't do anything aside from calling driver.quit().

**Comment by dvyAb** [comment]
Hello, 

Do you have any news for the error ? [(TypeError: Cannot read property 'match' of undefined)](https://github.com/appium-userland/appium-flutter-driver/issues/211#.
I have the same error when I physically connect the phone to the computer, I use Appium 1.22.2, iOS 15.3.1 and Xcode 13.2.1

thanks.

@KazuCocoa

**Comment by KazuCocoa** [comment]
https://github.com/appium-userland/appium-flutter-driver/issues/115 might be related for ios real devices if you still have an issue. It has more restrictions in iOS 14+ by Flutter.

**Comment by agpdl** [comment]
Is there a workaround for this issue? its a blocker for anyone running iOS 14+ (Almost all iPhones now...)

**Comment by KazuCocoa** [comment]
`profile` app as https://github.com/appium-userland/appium-flutter-driver/issues/115 ?
