### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by DevDengChao** [appium-userland/appium-flutter-driver#212]
The project depend on some outdated dependencies, such as rpc-websockets ^5.1.1, which depend on a problematic uuid package, and rpc-websockets fixed it on release 7.3.1.

Consider apply bots like dependabot ?

**Comment by KazuCocoa** [comment]
I thought already https://github.com/appium-userland/appium-flutter-driver/tree/master/.dependabot worked...
Let me check this weekend
