### ISSUE TITLE
Is posible get location for a element?

### ISSUE THREAD

**Issue by alexis9205110** [appium-userland/appium-flutter-driver#232]
Good Morning... 

I need you help please!!! I try to automated a seek bar using flutter appium driver but I can't have success. 

My first idea was get location for element, after try to use TouchAction with the coordinates

element = FlutterElement(self.driver, key_finder)
element.location 

element.location raise the exception "Message: Method has not yet been implemented" 

Get location is posible in flutter appium driver?

I also try to send keys for element but not working. I use python

**Comment by KazuCocoa** [comment]
Afaik, flutter context only supports commands listed in https://github.com/appium-userland/appium-flutter-driver#commands. So you cannot do other commands in `FLUTTER` contexts.

It seems https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html does not provide any apis to get an element coordinate. I guess flutter_driver by Flutter team does not have such APIs. (then, this driver cannot do anything)

In `NATIVE_APP` context like https://github.com/appium-userland/appium-flutter-driver#desired-capabilities-for-flutter-driver-only , you can call appium apis. Then, you can interact with elements that are available via OS's accessibility feature.

**Comment by KazuCocoa** [comment]
As the above comment, probably it is not available in Flutter context. Possibly NATIVE context in this driver is available. (Then, the element should be available via OS's accessibility feature.)

**Comment by sanneabhilash** [comment]
@alexis9205110  did you try any of the below methods?

- driver.execute('flutter:getBottomLeft', buttonFinder)
- driver.execute('flutter:getBottomRight', buttonFinder)
- driver.execute('flutter:getCenter', buttonFinder)
- driver.execute('flutter:getTopLeft', buttonFinder)
- driver.execute('flutter:getTopRight', buttonFinder)
