### ISSUE TITLE
Python waitFor Timeout not working properly

### ISSUE THREAD

**Issue by marcosmko** [appium-userland/appium-flutter-driver#244]
Hello all!

I'm having some troubles with the [python version](https://pypi.org/project/Appium-Flutter-Finder/) of this lib when using the following command:

`execute_script('flutter:waitFor', element.id, 0)`

When I define a timeout, it should wait **until** time expires, returning immediately if element is found. Instead, it wait the seconds defined and then return the result.

I also tested using a js test, which works properly, but I'm having this issue with the python library.

Am I doing something wrong?

**Comment by KazuCocoa** [comment]
Could you share the appium server log in both languages to compare issued requests between them?

**Comment by marcosmko** [comment]
Sorry, I think I have found the error!
Thanks anyway.

**Comment by canibal1** [comment]
Calling AppiumDriver.execute() with args: ["flutter:waitFor",["eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiaW50cm9QYWdlRGVzY3JpcHRpb25LZXkxIiwia2V5VmFsdWVUeXBlIjoiU3RyaW5nIn0=",10],"fce1da5a-b345-4e4e-b481-610d5d6d1d52"]
[FlutterDriver] Executing Flutter driver command 'execute'
[FlutterDriver] >>> {"command":"waitFor","finderType":"ByValueKey","keyValueString":"introPageDescriptionKey1","keyValueType":"String","timeout":10}
[FlutterDriver] <<< {"isError":true,"response":"Timeout while executing waitFor: TimeoutException after 0:00:00.010000: Future not completed\n","type":"_extensionType","method":"ext.flutter.driver"} | previous command waitFor
[FlutterDriver@a60b (fce1da5a)] Encountered internal error running command: Error: Cannot execute command waitFor, server response {
[FlutterDriver@a60b (fce1da5a)]   "isError": true,
[FlutterDriver@a60b (fce1da5a)]   "response": "Timeout while executing waitFor: TimeoutException after 0:00:00.010000: Future not completed\n",
[FlutterDriver@a60b (fce1da5a)]   "type": "_extensionType",
[FlutterDriver@a60b (fce1da5a)]   "method": "ext.flutter.driver"
[FlutterDriver@a60b (fce1da5a)] }


this is my server log, @KazuCocoa can you check it?
@marcosmko what was the error?

**Comment by KazuCocoa** [comment]
The error came from Flutter/Dart VM internal. Was your timeout too short? (guessed from the error message)
