### ISSUE TITLE
Original error: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by Muratoi** [appium-userland/appium-flutter-driver#248]
![image](https://user-images.githubusercontent.com/71320532/154118813-c53ccaa9-7745-4fad-80e0-4f7344bd4019.png)

![image](https://user-images.githubusercontent.com/71320532/154118891-46408d33-a37f-4bc8-bfba-65bb2f645e23.png)

Can somebody help me with that? 

Appium Version: 1.22.0

Same at Appium 2.0

**Comment by camillomurcia** [comment]
You already tried it by sending the ID obtained with the `adb devices` command and you place that ID in `deviceName`

**Comment by Muratoi** [comment]
@camillomurcia I have same error with your instruction :(    without the r, in python backslashes are treated as escape characters

**Comment by Muratoi** [comment]
![image](https://user-images.githubusercontent.com/71320532/154124500-95f45001-b270-4cf6-bc40-d0858a38e939.png)

**Comment by camillomurcia** [comment]
@Muratoi `Cannot read property 'match' of undefined` occurs when appium-flutter-driver failed to find a device.  restarting the device under test fixes some cases.

**Comment by Muratoi** [comment]
Same problem after restart, anyway thanks for trying to help!

**Comment by Muratoi** [comment]
logs at Appium V2 
![image](https://user-images.githubusercontent.com/71320532/154127225-69e16cad-c0e5-4ac3-b7f9-22210adfc12b.png)

**Comment by camillomurcia** [comment]
Can you upload the complete appium log of the execution?

**Comment by lorenacimpean** [comment]
Hi,

I've been redirected here from this issue: https://github.com/KazuCocoa/appium_dart/issues/39 
I'm having the same problem when setting the capability to Flutter.

I am able to create sessions, use appium inspector and even drive tests with uiautomator2, but when I switch capabilites to flutter I'm getting this error. So it seems like it's not an appium/app/project config issue.

I'm currently using Appium v1.22.0.
I've tried with Appium 2.0 as well, but moved to an older versions because of project dependencies. 
Either way, I get the same error with Appium 2.0. So it looks like it's not an Appium issue.

enableFlutterDriverExtension() is added to the main.dart file of the app.

So far it seems like it might be an issue with appium flutter driver:

Encountered internal error running command: TypeError: Cannot read property 'match' of undefined
[2022-02-19 03:10:16][W3C]     at Object.exports.processLogToGetobservatory (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/build/driver/lib/sessions/observatory.js:118:9)
[2022-02-19 03:10:16][W3C]     at Object.exports.getObservatoryWsUri (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/android.ts:39:21)
[2022-02-19 03:10:16][W3C]     at Object.exports.startAndroidSession (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/android.ts:26:30)
[2022-02-19 03:10:16][W3C]     at runMicrotasks ()
[2022-02-19 03:10:16][W3C]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2022-02-19 03:10:16][W3C]     at FlutterDriver.exports.createSession (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/session.ts:21:47)
[2022-02-19 03:10:16][W3C]     at AppiumDriver.createSession (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/lib/appium.js:387:35)
[2022-02-19 03:10:16][HTTP] <-- POST /wd/hub/session 500 8464 ms - 667

I'm attaching the complete appium logs from the most recent attempt.

This is pretty much a blocker, can you please prioritize it accordingly?

[appium-server-logs.txt](https://github.com/appium-userland/appium-flutter-driver/files/8102259/appium-server-logs.txt)

**Comment by KazuCocoa** [comment]
Basically, the error occurs when this driver cannot find logs (logcat in android, system log in iOS) https://github.com/appium-userland/appium-flutter-driver/blob/3eac68ffc7bf6f27cff0eeea11a6ceadfb2b9a81/driver/lib/sessions/observatory.ts#L142-L145 in the new session steps. So, logcat may help to see the cause.
For example, the logcat log appears before the flutter driver starts. (I don't know such case could happen though)

**Comment by lorenacimpean** [comment]
Could it work if you launch with uiAutomator/xcui and then switch to flutter ?

**Comment by KazuCocoa** [comment]
Perhaps no, since Flutter driver does it in its new session. e.g. https://github.com/appium-userland/appium-flutter-driver/blob/3eac68ffc7bf6f27cff0eeea11a6ceadfb2b9a81/driver/lib/sessions/android.ts#L22


You could try out newer flutter driver versions such as 0.0.35 that have a few improvements for the observatory method and so. It is available via `appium 2` (available via `appium@next` + `appium driver install flutter`) or `appium@beta` for now.

**Comment by aprilahijriyan** [comment]
I tried the latest version of appium, found at `appium@next`. And it seems it's still an issue, here's the appium log: https://pastebin.com/HKfGz9qf.

Tested on version:

* Appium 2.0.0-beta.25
* appium-flutter-driver@1.0.1

**Comment by aprilahijriyan** [comment]
cc @KazuCocoa

**Comment by KazuCocoa** [comment]
Generally it means this driver could not find https://github.com/appium-userland/appium-flutter-driver/issues/248#issuecomment-1046078089 in the logcat.
What's the logact?

**Comment by aprilahijriyan** [comment]
Logcat:

```
03-21 13:30:07.106  6113  6140 I appium  : Created the new session with id 246bb470-c3f6-441e-9e30-a3c9476650ed and capabilities {appPackage=com.pkg, noReset=true, ensureWebviewsHavePages=true, connectHardwareKeyboard=true, deviceName=emulator-5554, fullReset=false, platform=LINUX, deviceUDID=emulator-5554, desired={platformName=Android, deviceName=Android API 32, udid=emulator-5554, noReset=true, automationName=Flutter, appWaitDuration=70000.0, adbExecTimeout=40000.0, app=/Users/uwuw/Projects/headache/data/app/app-release.apk, appPackage=com.pkg, appActivity=.MainActivity, fullReset=false, ensureWebviewsHavePages=true, nativeWebScreenshot=true, newCommandTimeout=3600.0, connectHardwareKeyboard=true}, nativeWebScreenshot=true, newCommandTimeout=3600.0, webStorageEnabled=false, automationName=Flutter, takesScreenshot=true, javascriptEnabled=true, platformName=Android, udid=emulator-5554, app=/Users/uwuw/Projects/headache/data/app/app-release.apk, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, appWaitDuration=70000.0, appActivity=.MainActivity, adbExecTimeout=40000.0, locationContextEnabled=false}
03-21 13:30:07.226   540  1556 I ActivityManager: Force stopping com.pkg appid=10229 user=0: from pid 6146
03-21 13:30:07.487   540  1556 I ActivityTaskManager: START u0 {flg=0x10000000 cmp=com.pkg/.MainActivity} from uid 2000
03-21 13:30:07.532   540   587 I ActivityManager: Start proc 6149:com.pkg/u0a229 for pre-top-activity {com.pkg/com.pkg.MainActivity}
03-21 13:30:07.584  6149  6149 V GraphicsEnvironment: ANGLE Developer option for 'com.pkg' set to: 'default'
03-21 13:30:07.585  6149  6149 V GraphicsEnvironment: ANGLE GameManagerService for com.pkg: false
03-21 13:30:07.659  6149  6149 W ime.skinmystery: type=1400 audit(0.0:1446): avc: denied { read } for name="max_map_count" dev="proc" ino=953817 scontext=u:r:untrusted_app:s0:c229,c256,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=com.pkg
03-21 13:30:07.703   540   604 E VerityUtils: Failed to measure fs-verity, errno 1: /data/app/~~xxx==/com.pkg-xxx==/base.apk
03-21 13:30:07.831   540   575 I ActivityTaskManager: Displayed com.pkg/.MainActivity: +343ms
03-21 13:30:07.887   540  1556 I ActivityManager: Force stopping com.pkg appid=10229 user=0: from pid 6229
03-21 13:30:07.888   540  1556 I ActivityManager: Killing 6149:com.pkg/u0a229 (adj 0): stop com.pkg due to from pid 6229
03-21 13:30:07.889   540  1556 W ActivityTaskManager: Force removing ActivityRecord{a3e7570 u0 com.pkg/.MainActivity t149 f}}: app died, no saved state
03-21 13:30:07.892   540  1556 W InputManager-JNI: Input channel object '3a67046 Splash Screen com.pkg (client)' was disposed without first being removed with the input manager!
03-21 13:30:07.892   540  1556 W InputManager-JNI: Input channel object '4d2152c com.pkg/com.pkg.MainActivity (client)' was disposed without first being removed with the input manager!
03-21 13:30:07.898   540   776 V ActivityManager: Got obituary of 6149:com.pkg
03-21 13:30:08.620   540   575 D CompanionDeviceManagerService: onPackageModified(packageName = com.pkg)
03-21 13:30:08.634   781   781 D MediaPlayerList: Name of package changed: com.pkg
03-21 13:30:08.657   999   999 D ImsResolver: maybeAddedImsService, packageName: com.pkg
03-21 13:30:08.657  4014  6074 I Fitness : OnPackageChangedOperation got intent: Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:com.pkg flg=0x45000010 pkg=com.google.android.gms cmp=com.google.android.gms/.chimera.PersistentIntentOperationService (has extras) } [CONTEXT service_id=17 ]
```

**Comment by KazuCocoa** [comment]
This driver tries to find a line as https://github.com/appium-userland/appium-flutter-driver/issues/248#issuecomment-1046078089 to get websocket connection to the Dart VM. If no the line, this driver does not work.
Afaik, such a case could happen if the app was not debuggable. https://github.com/appium-userland/appium-flutter-driver#usage

**Comment by aprilahijriyan** [comment]
I tried reviewing the app with the appium inspector, can't seem to open the app. This is the output of logcat, when I open the app with the inspector.

```
03-21 13:44:21.694  6511  6538 I appium  : Created the new session with id 2b90db58-72cc-4493-92e2-f6b05da4c15e and capabilities {appPackage=com.pkg, noReset=true, ensureWebviewsHavePages=true, connectHardwareKeyboard=true, deviceName=emulator-5554, fullReset=false, platform=LINUX, deviceUDID=emulator-5554, desired={platformName=Android, deviceName=Android API 32, udid=emulator-5554, noReset=true, automationName=Flutter, appWaitDuration=70000.0, adbExecTimeout=40000.0, app=/Users/uwuw/Projects/headache/data/app/app-release.apk, appPackage=com.pkg, appActivity=.MainActivity, fullReset=false, ensureWebviewsHavePages=true, nativeWebScreenshot=true, newCommandTimeout=3600.0, connectHardwareKeyboard=true}, nativeWebScreenshot=true, newCommandTimeout=3600.0, webStorageEnabled=false, automationName=Flutter, takesScreenshot=true, javascriptEnabled=true, platformName=Android, udid=emulator-5554, app=/Users/uwuw/Projects/headache/data/app/app-release.apk, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, appWaitDuration=70000.0, appActivity=.MainActivity, adbExecTimeout=40000.0, locationContextEnabled=false}
03-21 13:44:21.796   540   886 I ActivityManager: Force stopping com.pkg appid=10229 user=0: from pid 6544
03-21 13:44:22.054   540   886 I ActivityTaskManager: START u0 {flg=0x10000000 cmp=com.pkg/.MainActivity} from uid 2000
03-21 13:44:22.074   540   587 I ActivityManager: Start proc 6547:com.pkg/u0a229 for pre-top-activity {com.pkg/com.pkg.MainActivity}
03-21 13:44:22.105  6547  6547 V GraphicsEnvironment: ANGLE Developer option for 'com.pkg' set to: 'default'
03-21 13:44:22.105  6547  6547 V GraphicsEnvironment: ANGLE GameManagerService for com.pkg: false
03-21 13:44:22.183  6547  6547 W ime.pkg: type=1400 audit(0.0:1455): avc: denied { read } for name="max_map_count" dev="proc" ino=959546 scontext=u:r:untrusted_app:s0:c229,c256,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=com.pkg
03-21 13:44:22.224   540   604 E VerityUtils: Failed to measure fs-verity, errno 1: /data/app/~~xxx==/com.pkg-xxx==/base.apk
03-21 13:44:22.355   540   575 I ActivityTaskManager: Displayed com.pkg/.MainActivity: +299ms
03-21 13:44:22.421   540  1686 I ActivityManager: Force stopping com.pkg appid=10229 user=0: from pid 6625
03-21 13:44:22.421   540  1686 I ActivityManager: Killing 6547:com.pkg/u0a229 (adj 0): stop com.pkg due to from pid 6625
03-21 13:44:22.425   540  1686 W ActivityTaskManager: Force removing ActivityRecord{c3c0e8a u0 com.pkg/.MainActivity t150 f}}: app died, no saved state
03-21 13:44:22.427   540  1686 W InputManager-JNI: Input channel object 'e1226c4 Splash Screen com.pkg (client)' was disposed without first being removed with the input manager!
03-21 13:44:22.428   540  1686 W InputManager-JNI: Input channel object '70dc190 com.pkg/com.pkg.MainActivity (client)' was disposed without first being removed with the input manager!
03-21 13:44:22.468   540  3302 V ActivityManager: Got obituary of 6547:com.pkg
```

The configuration I use:

```json
{
     "platformName": "Android",
     "appium:devicename": "Android API 32",
     "appium:udid": "emulator-5554",
     "appium:noReset": true,
     "appium:automationName": "Flutter",
     "appium:appWaitDuration": 70000,
     "appium:adbExecTimeout": 40000
     "appium:app": "/Users/uwuw/Projects/headache/data/app/app-release.apk",
     "appium:appPackage": "com.pkg",
     "appium:appActivity": ".MainActivity",
     "appium:fullReset": false
}
```

<img width="627" alt="image" src="https://user-images.githubusercontent.com/37798612/159221283-d44ce12e-9bbf-4340-ad64-baafde2ae567.png">

**Comment by aprilahijriyan** [comment]
If I use `appium:automationName` = `UiAutomator2` it works through the appium inspector.

<img width="496" alt="image" src="https://user-images.githubusercontent.com/37798612/159222050-8c98171c-e869-4222-a0c5-394c14f0c4ad.png">

**Comment by KazuCocoa** [comment]
Did you have configured https://github.com/appium-userland/appium-flutter-driver#usage?

> Your Flutter app-under-test (AUT) must be compiled in debug or profile mode, because Flutter Driver does not support running in release mode.. Also, ensure that your Flutter AUT has enableFlutterDriverExtension() before runApp. Then, please make sure your app imported [flutter_driver](https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html) package as well.

**Comment by mrqws** [comment]
Has this problem been solved? I have the same problem

**Comment by Alpaca00** [comment]
I also have the same problem if flutter version > 2.10.5

**Comment by Alpaca00** [comment]
Thanks KazuCocoa, solved this issue by adding a prefix to the capabilities, updating appium flutter driver 1.2.0 with appium 2.0 and installing plugin `relaxed-caps` to appium 2.0.
Run CLI:
`appium --use-plugins=relaxed-caps -pa /wd/hub --session-override`

**Comment by KazuCocoa** [comment]
close as current issue we may face this `match` issue is:

- need a newer appium-flutter-driver (e.g. 1.2.0) with Appium 2
- profile/debug build
