### ISSUE TITLE
Add to app example

### ISSUE THREAD

**Issue by prolificcoder** [appium-userland/appium-flutter-driver#251]
At my work we are converting our existing android and iOS apps to flutter slowly by [Add to App](https://docs.flutter.dev/development/add-to-app) strategy. 

Even though we have tests are various lower levels Unit, Widget and on Android side with espresso, we currently have a need to automate interactions from Native <-> Flutter and vice versa. In some cases we route multiple times from Native -> flutter -> Native -> flutter. 

Using native frameworks like espresso/XCUITests isn't feasible because flutter screens are opaque to espresso (even though [this](https://pub.dev/packages/espresso) exists it won't work for iOS). And similar flutters integration tests can't look into android/iOS screens. 

This framework looks like a good candidate because appium treats entire mobile app as a blackbox and has functionality to switch contexts from NATIVE_APP to FLUTTER. 

**Requesting** for an example project that can demonstrate this working. The current [example app](https://github.com/appium-userland/appium-flutter-driver/tree/main/example/flutter_app_under_test) in this project is a pure flutter app and other than a [screenshot](https://github.com/appium-userland/appium-flutter-driver/blob/main/example/nodejs/src/index.js#L66) didn't execute other commands. 

Also this app looks very old.

**Comment by prolificcoder** [comment]
https://github.com/flutter/samples/tree/master/add_to_app/fullscreen this would a good sample app to demonstrate switching contexts

**Comment by KazuCocoa** [comment]
Thanks for the suggestion. I heard some persons use this for Native/WebView/Flutter combinations as well.

Let me take a look at the attached sample app.

**Comment by KazuCocoa** [comment]
https://github.com/appium-userland/appium-flutter-driver/pull/252 is for Ruby example but it adds the fullscreen android app as another example.

**Comment by prolificcoder** [comment]
Since this is also merged https://github.com/appium-userland/appium-flutter-driver/pull/256 i think we can close this as resolved.
