### ISSUE TITLE
How to get the Flutter log print

### ISSUE THREAD

**Issue by elementlo** [appium-userland/appium-flutter-driver#254]
Is there a mehod which can get log with ```log(String)```  or other logging Dart packages in dart enviroment? I tried driver.get_log(), but only the logs that use ```print()``` function can be shown in appium in NATIVE_CONTEXT.

I need this because I want  to track the app http traffic and for now this is the only convenient way I've found.

**Comment by KazuCocoa** [comment]
Basically, this driver can get logs in logcat(Android) and device log (iOS) in native context. We probably can add an endpoint to get logs in Flutter if [`flutter_driver`](https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html) provide such method. (I don't know if it could, but theoretically can.)

**Comment by elementlo** [comment]
> Basically, this driver can get logs in logcat(Android) and device log (iOS) in native context. We probably can add an endpoint to get logs in Flutter if [`flutter_driver`](https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html) provide such method. (I don't know if it could, but theoretically can.)

Yeah, I've tried to get native logs which succeeded. Just wonder why there not a  method to fetch the Dart one. I think it is common requirement in all. Will close this issue. Maybe I should try another strategy. Thanks!
