### ISSUE TITLE
Can't integrate applitools eye validation with flutter automation name .

### ISSUE THREAD

**Issue by MayadaAhmed1** [appium-userland/appium-flutter-driver#255]
am trying to make visual test by adding applitools dependencies but i got error "method not implemented yet " when i used flutter automation name .....
for more details programming language :java 
and below is the capability used :
       flutterCapabilities.setCapability( "deviceName", deviceName );
        flutterCapabilities.setCapability( "platformName", Android );
        flutterCapabilities.setCapability( "platformVersion", platformVersion);
        flutterCapabilities.setCapability("udid",udid);
        flutterCapabilities.setCapability("app",appPtah);
        flutterCapabilities.setCapability("automationName", "Flutter");

**Note:** when i replace the automation name with "automator2 "instead of "flutter" it works fine but the script failed due to key value i used ,,,,any help for visual testing in flutter apps?

**Comment by KazuCocoa** [comment]
i haven't used their tool, but i guess some methods that are not in flutter driver is used by them.
I would ask their support team first rather than here.

So far, I don't see applitools persons around this community based flutter driver implementation. So not sure if they can work with this.
