### ISSUE TITLE
Scroll on ListView on ruby

### ISSUE THREAD

**Issue by anda01** [appium-userland/appium-flutter-driver#257]
Could you help to provide an example for scrolling? I've tried to call like this : 

$driver.execute_script('flutter:scroll', by_type('ListView'), dx: 50, dy: -100)

but still not working. 
thanks

**Comment by wsfcsk** [comment]
in python way :

 FlutterDriver.execute_script('flutter:scroll', scrollFinder.by_type("ListView"), {"dx": 50, "dy": -100, "durationMilliseconds": 200, "frequency": 30})

it should be a dic

**Comment by KazuCocoa** [comment]
```
driver.execute_script('flutter:scroll', by_type('ListView'), {dx: 50, dy: -100})
```
may work.
