### ISSUE TITLE
[FlutterDriver] stuck on executing command 'click' using finder

### ISSUE THREAD

**Issue by ihorvoitkiv** [appium-userland/appium-flutter-driver#261]
Hi, I'm working on an app that is being converted from native iOS and Android apps to Flutter using the Add-to-App approach - however, with the [multiple Flutter engines approach] (https://docs.flutter.dev/development/add-to-app/multiple-flutters). Currently, as I'm trying to set test automation using Appium Flutter Driver with Python client library, and looks like the connection is established:

[FlutterDriver] Attempt #1
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:43903/0cRhhIWOjU0=/ws
[FlutterDriver] Connected to ws://127.0.0.1:43903/0cRhhIWOjU0=/ws
[FlutterDriver] Listing all isolates: [{"type":"@Isolate","id":"isolates/3707433459146791","name":"main","number":"3707433459146791","isSystemIsolate":false}]
[Appium] New FlutterDriver session created successfully, session 7eee9e8a-a252-49a6-9a3a-da8772af3643 added to master session list

BUT, faced the issue that [FlutterDriver] stuck on executing command 'click', when switched from NATIVE to FLUTTER context:

[debug] [W3C (7eee9e8a)] Responding to client with driver.getContexts() result: ["NATIVE_APP","FLUTTER"]
[HTTP] <-- GET /wd/hub/session/7eee9e8a-a252-49a6-9a3a-da8772af3643/contexts 200 33 ms - 34
[HTTP] 
[HTTP] --> GET /wd/hub/session/7eee9e8a-a252-49a6-9a3a-da8772af3643/context
[HTTP] {}
[debug] [W3C (7eee9e8a)] Calling AppiumDriver.getCurrentContext() with args: ["7eee9e8a-a252-49a6-9a3a-da8772af3643"]
[debug] [FlutterDriver] Executing Flutter driver command 'getCurrentContext'
[debug] [W3C (7eee9e8a)] Responding to client with driver.getCurrentContext() result: "FLUTTER"
[HTTP] <-- GET /wd/hub/session/7eee9e8a-a252-49a6-9a3a-da8772af3643/context 200 2 ms - 19
[HTTP] 
[HTTP] --> POST /wd/hub/session/7eee9e8a-a252-49a6-9a3a-da8772af3643/element/eyJmaW5kZXJUeXBlIjoiQnlUZXh0IiwidGV4dCI6IlRyYWNrIE5vdyJ9/click
[HTTP] {"id":"eyJmaW5kZXJUeXBlIjoiQnlUZXh0IiwidGV4dCI6IlRyYWNrIE5vdyJ9"}
[debug] [W3C (7eee9e8a)] Calling AppiumDriver.click() with args: ["eyJmaW5kZXJUeXBlIjoiQnlUZXh0IiwidGV4dCI6IlRyYWNrIE5vdyJ9","7eee9e8a-a252-49a6-9a3a-da8772af3643"]
[debug] [FlutterDriver] Executing Flutter driver command 'click'
[debug] [FlutterDriver] >>> {"command":"tap","finderType":"ByText","text":"Track Now"}

ALREADY done with:
1. imported 'package:flutter_driver/driver_extension.dart and added enableFlutterDriverExtension() in main.dart file
2. dev_dependencies in pubspec.yaml:
  test: any
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
3. added uses-permission android:name="android.permission.INTERNET to AndroidManifest.xml
4. debug build

This is caps and a test script:
caps = {
            'app': '/src/app/app-universal-debug.apk',
            'platformName': 'Android',
            'platformVersion': '10',
            'deviceName': 'Pixel_4_API_29',
            'automationName': 'Flutter',
            'noReset': False,
            'fullReset': False,
            'autoGrantPermissions': True,
            # disable keyboard appearance
            'unicodeKeyboard': True,
            'resetKeyboard': True,
            'isHeadless': True,
            'skipLogcatCapture': False,
            'adbExecTimeout': 30000,
            'logcatFormat': 'process',
            'clearDeviceLogsOnStart': True,
            'ignoreHiddenApiPolicyError': True
        }
        driver = Remote('http://localhost:4723/wd/hub', caps)

       NATIVE TEST FLOW...

        driver.switch_to.context('FLUTTER')
        contexts = driver.contexts
        current_context = driver.current_context
        finder = FlutterFinder()
        track_finder = finder.by_text("Track Now")
        track_element = FlutterElement(driver, track_finder)
        track_element.click()

P.S. i don't get this issue with purely flutter build. Repro only on native + flutter
@KazuCocoa
Thanks in advance

**Comment by KazuCocoa** [comment]
Did other flutter commands work?
If it occurred only the command, probably something occurred in the Dart VM internal on the app under test.


appium-flutter-driver simply sends the below commands, and wait for the response by the Dart VM. It seems like the above description indicates no-response by the Dart VM. Then, probably something occurred in the Dart VM/flutter_driver https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html internal.
```
[debug] [FlutterDriver] >>> {"command":"tap","finderType":"ByText","text":"Track Now"}
```

If so, perhaps nothing can do in this driver layer.

**Comment by ihorvoitkiv** [comment]
I've added:
driver.execute_script('flutter:waitFor', track_finder, 10) 
before 
track_element = FlutterElement(driver, track_finder)
track_element.click()
and got an issue:

self = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x10d4d6490>
response = {'status': 500, 'value': '{"value":{"error":"unknown error","message":"An unknown server-side error occurred while pro... asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)"}}'}

    def check_response(self, response: Dict[str, Any]) -> None:
        """
        Checks that a JSON response from the WebDriver does not have an error.
    
        :Args:
         - response - The JSON response from the WebDriver server as a dictionary
           object.
    
        :Raises: If the response contains an error message.
        """
        status = response.get('status', None)
        if not status or status == ErrorCode.SUCCESS:
            return
        value = None
        message = response.get("message", "")
        screen: str = response.get("screen", "")
        stacktrace = None
        if isinstance(status, int):
            value_json = response.get('value', None)
            if value_json and isinstance(value_json, str):
                import json
                try:
                    value = json.loads(value_json)
                    if len(value.keys()) == 1:
                        value = value['value']
                    status = value.get('error', None)
                    if not status:
                        status = value.get("status", ErrorCode.UNKNOWN_ERROR)
                        message = value.get("value") or value.get("message")
                        if not isinstance(message, str):
                            value = message
                            message = message.get('message')
                    else:
                        message = value.get('message', None)
                except ValueError:
                    pass
    
        exception_class: Type[WebDriverException]
        if status in ErrorCode.NO_SUCH_ELEMENT:
            exception_class = NoSuchElementException
        elif status in ErrorCode.NO_SUCH_FRAME:
            exception_class = NoSuchFrameException
        elif status in ErrorCode.NO_SUCH_WINDOW:
            exception_class = NoSuchWindowException
        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:
            exception_class = StaleElementReferenceException
        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:
            exception_class = ElementNotVisibleException
        elif status in ErrorCode.INVALID_ELEMENT_STATE:
            exception_class = InvalidElementStateException
        elif status in ErrorCode.INVALID_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:
            exception_class = InvalidSelectorException
        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:
            exception_class = ElementNotSelectableException
        elif status in ErrorCode.ELEMENT_NOT_INTERACTABLE:
            exception_class = ElementNotInteractableException
        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:
            exception_class = InvalidCookieDomainException
        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:
            exception_class = UnableToSetCookieException
        elif status in ErrorCode.TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.SCRIPT_TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.UNKNOWN_ERROR:
            exception_class = WebDriverException
        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:
            exception_class = UnexpectedAlertPresentException
        elif status in ErrorCode.NO_ALERT_OPEN:
            exception_class = NoAlertPresentException
        elif status in ErrorCode.IME_NOT_AVAILABLE:
            exception_class = ImeNotAvailableException
        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:
            exception_class = ImeActivationFailedException
        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:
            exception_class = MoveTargetOutOfBoundsException
        elif status in ErrorCode.JAVASCRIPT_ERROR:
            exception_class = JavascriptException
        elif status in ErrorCode.SESSION_NOT_CREATED:
            exception_class = SessionNotCreatedException
        elif status in ErrorCode.INVALID_ARGUMENT:
            exception_class = InvalidArgumentException
        elif status in ErrorCode.NO_SUCH_COOKIE:
            exception_class = NoSuchCookieException
        elif status in ErrorCode.UNABLE_TO_CAPTURE_SCREEN:
            exception_class = ScreenshotException
        elif status in ErrorCode.ELEMENT_CLICK_INTERCEPTED:
            exception_class = ElementClickInterceptedException
        elif status in ErrorCode.INSECURE_CERTIFICATE:
            exception_class = InsecureCertificateException
        elif status in ErrorCode.INVALID_COORDINATES:
            exception_class = InvalidCoordinatesException
        elif status in ErrorCode.INVALID_SESSION_ID:
            exception_class = InvalidSessionIdException
        elif status in ErrorCode.UNKNOWN_METHOD:
            exception_class = UnknownMethodException
        else:
            exception_class = WebDriverException
        if not value:
            value = response['value']
        if isinstance(value, str):
            raise exception_class(value)
        if message == "" and 'message' in value:
            message = value['message']
    
        screen = None  # type: ignore[assignment]
        if 'screen' in value:
            screen = value['screen']
    
        stacktrace = None
        st_value = value.get('stackTrace') or value.get('stacktrace')
        if st_value:
            if isinstance(st_value, str):
                stacktrace = st_value.split('\n')
            else:
                stacktrace = []
                try:
                    for frame in st_value:
                        line = self._value_or_default(frame, 'lineNumber', '')
                        file = self._value_or_default(frame, 'fileName', '<anonymous>')
                        if line:
                            file = "%s:%s" % (file, line)
                        meth = self._value_or_default(frame, 'methodName', '<anonymous>')
                        if 'className' in frame:
                            meth = "%s.%s" % (frame['className'], meth)
                        msg = "    at %s (%s)"
                        msg = msg % (meth, file)
                        stacktrace.append(msg)
                except TypeError:
                    pass
        if exception_class == UnexpectedAlertPresentException:
            alert_text = None
            if 'data' in value:
                alert_text = value['data'].get('text')
            elif 'alert' in value:
                alert_text = value['alert'].get('text')
            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
>       raise exception_class(message, screen, stacktrace)
E       **selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot execute command waitFor, server reponse {
E         "isError": true,
E         "response": "Timeout while executing waitFor: TimeoutException after 0:00:10.000000: Future not completed\n",
E         "type": "_extensionType",
E         "method": "ext.flutter.driver"
E       }
E       Stacktrace:
E       UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot execute command waitFor, server reponse {
E         "isError": true,
E         "response": "Timeout while executing waitFor: TimeoutException after 0:00:10.000000: Future not completed\n",
E         "type": "_extensionType",
E         "method": "ext.flutter.driver"
E       }**
E           at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
E           at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)

../../.virtualenvs/aqa_flutter/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:243: WebDriverException
@KazuCocoa

**Comment by ihorvoitkiv** [comment]
for the other commands, i get source tree by:
flutter_source = driver.execute_script('flutter: getRenderTree')
