### ISSUE TITLE
not compatible anymore with appium java-client 8.0

### ISSUE THREAD

**Issue by StephanB75** [appium-userland/appium-flutter-driver#265]
My testsuite is running with the latest appium java client and i came up to a problem that the flutter finder seems to use mobileElement which is not supported anymore.

Anyone a workaround instead of going back with the java client version ?

**Comment by KazuCocoa** [comment]
Perhaps https://github.com/appium-userland/appium-flutter-driver/tree/main/finder needs some update.

**Comment by hai-ha** [comment]
@StephanB75 I made some workarounds [here](https://github.com/hai-ha/appium-flutter-driver) on the Kotlin project to made it work with java-client 8.0, hope it helps.

**Comment by StephanB75** [comment]
@hai-ha THANKS for your help !
Maybe i'm doing something wrong but i after building the FlutterFinder.class with "gradle clean assemble" and importing it into my project i get this errors
![image](https://user-images.githubusercontent.com/90029825/160065357-a66aafa4-7e58-4ecf-9c36-d30ceadc1ae8.png)

**Comment by StephanB75** [comment]
@hai-ha Thank you looks better now :)
Do you have only replaced MobielElement with RemoteWebElement ?
If yes i had also tried that yesterday myself but most probably i have done something wrong on importing the compiled class to my project ;)
Again Thank you for our help.
@KazuCocoa Will this change come into the master ?

**Comment by hai-ha** [comment]
@StephanB75 Mostly so, you may see the code changes here: https://github.com/appium-userland/appium-flutter-driver/compare/main...hai-ha:main

**Comment by hai-ha** [comment]
Hi @KazuCocoa,
I'm new to this project. Not sure how I can submit the code changes for kotlin finder project?

Thanks,
Hai

**Comment by KazuCocoa** [comment]
You could just create a pr

**Comment by KazuCocoa** [comment]
https://github.com/appium-userland/appium-flutter-driver/pull/266
