### ISSUE TITLE
Can't switch to WEBVIEW context, only FLUTTER and NATIVE_APP visible

### ISSUE THREAD

**Issue by Abhi011999** [appium-userland/appium-flutter-driver#272]
I am using the python appium library and appium flutter finder library [here](https://pypi.org/project/Appium-Flutter-Finder/).

Here is a sample code
```python
# Health Check
assert driver.execute_script("flutter:checkHealth") == "ok", "Health check failed!"

# Clear timeline and force garbage collection
driver.execute_script("flutter:clearTimeline")
driver.execute_script("flutter:forceGC")

finder = FlutterFinder()

# Authentication Test
SIGN_IN_BUTTON_TEXT = 'Sign in with Microsoft'
driver.execute_script('flutter:waitFor', finder.by_text(SIGN_IN_BUTTON_TEXT))

sign_in_button_finder = finder.by_text(SIGN_IN_BUTTON_TEXT)
sign_in_button_element = FlutterElement(driver, sign_in_button_finder)
sign_in_button_element.click()

INPUT_BOX_TEXT = 'Email, phone, or Skype'
driver.execute_script('flutter:waitFor', finder.by_text(INPUT_BOX_TEXT))

input_box_finder = finder.by_text(INPUT_BOX_TEXT)
input_box_element = FlutterElement(driver, input_box_finder)
input_box_element.click()

driver.execute_script('flutter:enterText', 'email_id@gmail.com')
driver.press_keycode(66) # Press 'Enter' key
```

Sample Video of the process
> https://user-images.githubusercontent.com/27683952/165884000-9b8788cc-f3f5-49b0-b0a3-fb167ea36309.mp4

After the Webview is triggered by clicking the sign-in button, it doesn't show up in the contexts list. So we can't switch to it for further testing.

Is this a python-only issue or it's happening in all the libraries ?

PS. I read all the issues related to Webview and looked at the PRs and none of them were helpful.

**Comment by KazuCocoa** [comment]
Perhaps it is not client library specific.

Is the app debuggable?
https://appium.io/docs/en/writing-running-appium/web/hybrid/

**Comment by elizajasin** [comment]
got the same problem on java script, i've been tried to debug the app and see the list of the context available but the result is `INFO webdriver: RESULT [ 'NATIVE_APP', 'FLUTTER' ]` can't find the webview context. @Abhi011999 have you find the solution?

**Comment by Abhi011999** [comment]
@elizajasin
No, sill stuck and looking into this.

**Comment by KazuCocoa** [comment]
Please attach the full appium server log as GIST. Then, please try to get available contexts in the NATIVE_APP context once.

**Comment by KazuCocoa** [comment]
Please attach the full log as GIST as my previous comment to assume the situation. Close at this time as no one attached any logs
