### ISSUE TITLE
No throwable exception if element is exist but i can't interact with it  like click or enterText

### ISSUE THREAD

**Issue by ahmadhamedd** [appium-userland/appium-flutter-driver#279]
I am using `appium-flutter-driver` with java and testNG.
in our application, there is an unexpected popup message over a button so if I need to click it the driver find the button but can't click it because of the popUp message, and the driver is still waiting forever.

so the driver **should throw an exception if an element exists but can't interact with it (Not clickable ... )**

I found this way to give a timeout for finding 

`driver.executeScript("flutter:waitFor", find.byValueKey(locator), 40);`

but it's only working when an element does not exist, so in my case the element exists but I can't click it.

**is there any way that gives me if the element is clickable or not?**

Appium server still showing this :
> [debug] [FlutterDriver] Executing Flutter driver command 'click'
> [debug] [FlutterDriver] >>> {"command":"tap","finderType":"ByValueKey","keyValueType":"String","keyValueString":"MoreNav"}

**Comment by KazuCocoa** [comment]
This driver depends on https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html , so if the library can provide such a clickable attribute, this driver can handle it.

Probably https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/waitForTappable.html ?

Similar implementation;
https://github.com/appium-userland/appium-flutter-driver/blob/3eac68ffc7bf6f27cff0eeea11a6ceadfb2b9a81/driver/lib/commands/execute.ts#L41-L44

**Comment by ahmadhamedd** [comment]
@KazuCocoa  how can i use `waitForTappable` in `appium-flutter-driver` by java ?

**Comment by KazuCocoa** [comment]
The function needs to be implemented in the appium-flutter-driver first to call it via clients in around https://github.com/appium-userland/appium-flutter-driver/blob/3eac68ffc7bf6f27cff0eeea11a6ceadfb2b9a81/driver/lib/commands/execute.ts#L41-L44

**Comment by KazuCocoa** [comment]
https://github.com/appium-userland/appium-flutter-driver/pull/289 Maybe this branch can use to check tappable.

**Comment by ahmadhamedd** [comment]
@KazuCocoa Thanks for your support.

 How can I use this branch? Should I upgrade `appium-futter-driver `   by npm command?

**Comment by KazuCocoa** [comment]
You could try out the latest appium-flutter-driver package. (The branch has been pushed)

**Comment by thuonglai** [comment]
@KazuCocoa . I updated new version of appium flutter driver. But it still has error 
"org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Command not support: "flutter:waitForTappable".

**Comment by KazuCocoa** [comment]
Could you share the full appium log? The flutter driver should be 1.2.0.

**Comment by thuonglai** [comment]
@KazuCocoa  Yes. I check it is 1.2.0. Here is appium log:
`--> POST /wd/hub/session/efc40c0f-68bc-47e3-b723-e53fb33251c5/execute/sync
[HTTP] {"script":"flutter:waitForTappable","args":[{"ELEMENT":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiX19sb2dpbl9zY3JlZW4uZm9ybS5idXR0b24uc2lnbmluIn0","element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiX19sb2dpbl9zY3JlZW4uZm9ybS5idXR0b24uc2lnbmluIn0"},10]}
[debug] [W3C (efc40c0f)] Calling AppiumDriver.execute() with args: ["flutter:waitForTappable",[{"ELEMENT":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiX19sb2dpbl9zY3JlZW4uZm9ybS5idXR0b24uc2lnbmluIn0","element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiX19sb2dpbl9zY3JlZW4uZm9ybS5idXR0b24uc2lnbmluIn0"},10],"efc40c0f-68bc-47e3-b723-e53fb33251c5"]
[debug] [FlutterDriver] Executing Flutter driver command 'execute'
[debug] [W3C (efc40c0f)] Encountered internal error running command: Error: Command not support: "flutter:waitForTappable"
[debug] [W3C (efc40c0f)]     at FlutterDriver.exports.execute (/Users/axlehire/.nvm/versions/node/v18.2.0/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/commands/execute.ts:62:13)
[debug] [W3C (efc40c0f)]     at commandExecutor (/Users/axlehire/.nvm/versions/node/v18.2.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
[debug] [W3C (efc40c0f)]     at /Users/axlehire/.nvm/versions/node/v18.2.0/lib/node_modules/appium/node_modules/async-lock/lib/index.js:146:12
[debug] [W3C (efc40c0f)]     at AsyncLock._promiseTry (/Users/axlehire/.nvm/versions/node/v18.2.0/lib/node_modules/appium/node_modules/async-lock/lib/index.js:280:31)
[debug] [W3C (efc40c0f)]     at exec (/Users/axlehire/.nvm/versions/node/v18.2.0/lib/node_modules/appium/node_modules/async-lock/lib/index.js:145:9)
[debug] [W3C (efc40c0f)]     at AsyncLock.acquire (/Users/axlehire/.nvm/versions/node/v18.2.0/lib/node_modules/appium/node_modules/async-lock/lib/index.js:162:3)
[debug] [W3C (efc40c0f)]     at FlutterDriver.executeCommand (/Users/axlehire/.nvm/versions/node/v18.2.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:348:39)
[debug] [W3C (efc40c0f)]     at FlutterDriver.executeCommand (/Users/axlehire/.nvm/versions/node/v18.2.0/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/driver.ts:132:22)
[debug] [W3C (efc40c0f)]     at AppiumDriver.executeCommand (/Users/axlehire/.nvm/versions/node/v18.2.0/lib/node_modules/appium/lib/appium.js:563:36)
[debug] [W3C (efc40c0f)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [W3C (efc40c0f)]     at asyncHandler (/Users/axlehire/.nvm/versions/node/v18.2.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
[HTTP] <-- POST /wd/hub/session/efc40c0f-68bc-47e3-b723-e53fb33251c5/execute/sync 500 37 ms - 657
[HTTP] 

`

**Comment by KazuCocoa** [comment]
Could you share the full appium server log as GIST?

```
[debug] [W3C (efc40c0f)] Encountered internal error running command: Error: Command not support: "flutter:waitForTappable"
[debug] [W3C (efc40c0f)] at FlutterDriver.exports.execute (/Users/axlehire/.nvm/versions/node/v18.2.0/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/commands/execute.ts:62:13)
```

This error should be L66 in latest code:

https://github.com/appium-userland/appium-flutter-driver/blob/d849499f73ae0394400117065e189614e3d14cb4/driver/lib/commands/execute.ts#L66

**Comment by thuonglai** [comment]
Here is full appium server log 
https://gist.github.com/thuonglai/895ae9588ebac97b484845b7ddf9ec80

**Comment by thuonglai** [comment]
Thanks @KazuCocoa . It worked.
