### ISSUE TITLE
Could not connect the IOS simulator An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by wsfcsk** [appium-userland/appium-flutter-driver#280]
[debug] [WD Proxy] Proxying [DELETE /session/da09b5f9-f1da-4d3d-8712-42cde672efe4] to [DELETE http://127.0.0.1:8100/session/FCD26ABE-6DFE-4EB5-9F06-90C690D55890] with no body
[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":null}
[DevCon Factory] Releasing connections for 724B356C-137A-4F69-A0A4-B42DB923E517 device on any port number
[DevCon Factory] Found cached connections to release: ["724B356C-137A-4F69-A0A4-B42DB923E517:8100"]
[debug] [DevCon Factory] Cached connections count: 0
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [IOSSimulatorLog] Stopping iOS log capture
[debug] [FlutterDriver] Deleting Flutter Driver session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1654507396888 (17:23:16 GMT+0800 (中国标准时间))
[debug] [W3C] Encountered internal error running command: TypeError: Cannot read properties of undefined (reading 'match')
[debug] [W3C]     at Object.exports.processLogToGetobservatory (/opt/homebrew/lib/node_modules/appium/node_modules/appium-flutter-driver/build/driver/lib/sessions/observatory.js:118:9)
[debug] [W3C]     at Object.exports.getObservatoryWsUri (/opt/homebrew/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:77:21)
[debug] [W3C]     at Object.exports.startIOSSession (/opt/homebrew/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:31:30)
[debug] [W3C]     at runMicrotasks (<anonymous>)
[debug] [W3C]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [W3C]     at FlutterDriver.exports.createSession (/opt/homebrew/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/session.ts:15:47)
[debug] [W3C]     at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:387:35)
[HTTP] <-- POST /wd/hub/session 500 1196 ms - 609
[HTTP]

**Comment by wsfcsk** [comment]
could you help check this ???

thanks !

**Comment by KazuCocoa** [comment]
What observatory url appeared in the system log?
This driver gets the URL matched with https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/lib/sessions/observatory.ts#L159-L165

**Comment by hudson-pierce** [comment]
I am encountering the same issue as well. I took a look at my iOS simulators system log and this is all I see:

**Comment by KazuCocoa** [comment]
`appium:showIOSLog: true` prints the system log as part of appium. You also can check the capability if the log has the expected line. If still no observatory URL did not exist, probably the app does not expose the Dart VM.

**Comment by wsfcsk** [comment]
Hi 
It's solved by change the pack way , has nothing to do with the appium flutter driver 
thanks
