### ISSUE TITLE
Failed to create session. An unknown server-side error occurred while processing the command. Original error: Command failed: C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -s OFX8LVT4OB7L69T8 forward tcp:42103 tcp:42103 'C:\Program' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by RajasekharDotNet** [appium-userland/appium-flutter-driver#281]
I am in learning stage and trying to open simple  flutter app provided in this repository using Appium inspector. 

I have provided below capabilities and getting error:
{
  "appium:Device": "Android",
  "appium:platformName": "Android",
  "appium:AppActivity": "com.example.MainActivity",
  "appium:androidSDKPath": "C:\\Users\\____\\AppData\\Local\\Android\\Sdk",
  "appium:automationName": "Flutter",
  "appium:PlatformVersion": "12",
  "appium:app": "D:\\Learning\\Flutter\\GitHub\\appium-flutter-driver\\example\\sample2\\app-debug.apk",
  "appium:deviceName": "vivo 1901",
  "appium:retryBackoffTime": "5000",
  "appium:observatoryWsUri": "'ws://127.0.0.1:60992/aaaaaaaaaaa=/ws'"
}

Failed to create session. An unknown server-side error occurred while processing the command. Original error: Command failed: C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -s OFX8LVT4OB7L69T8 forward tcp:42103 tcp:42103 
**'C:\Program'** is not recognized as an internal or external command, operable program or batch file.

I think original command is not correctly enclosed in between "'"

Please let me know how can I solve this.

**Comment by AhmedBahgat** [comment]
Did you try to remove this line `"appium:androidSDKPath": "C:\Users\____\AppData\Local\Android\Sdk",
` ?

**Comment by RajasekharDotNet** [comment]
> Did you try to remove this line `"appium:androidSDKPath": "C:\Users\____\AppData\Local\Android\Sdk", ` ?

Its present in Capabilities. but still getting error as "Failed to create session. An unknown server-side error occurred while processing the command. Original error: Command failed: C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -s OFX8LVT4OB7L69T8 forward tcp:42103 tcp:42103
'C:\Program' is not recognized as an internal or external command, operable program or batch file."

I tried removing this path and kept "C:\\Program Files (x86)\\Android\\android-sdk", still same error.
I even tried removing capability "appium:androidSDKPath", still getting this error.

Please suggest how to solve this.

**Comment by RajasekharDotNet** [comment]
Fixed issue. Updated Andorid SDK path in Appium server to point to C:\Users\<----->\AppData\Local\Android\Sdk

**Comment by RajasekharDotNet** [comment]
> > Did you try to remove this line `"appium:androidSDKPath": "C:\Users\____\AppData\Local\Android\Sdk", ` ?
> 
> Its present in Capabilities. but still getting error as "Failed to create session. An unknown server-side error occurred while processing the command. Original error: Command failed: C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -s OFX8LVT4OB7L69T8 forward tcp:42103 tcp:42103 'C:\Program' is not recognized as an internal or external command, operable program or batch file."
> 
> I tried removing this path and kept "C:\Program Files (x86)\Android\android-sdk", still same error. I even tried removing capability "appium:androidSDKPath", still getting this error.
> 
> Please suggest how to solve this.

**Comment by RajasekharDotNet** [comment]
Fixed issue. Updated Andorid SDK path in Appium server to point to C:\Users\<----->\AppData\Local\Android\Sdk
