### ISSUE TITLE
waitFor only take 2 args , but example give 3 

### ISSUE THREAD

**Issue by wsfcsk** [appium-userland/appium-flutter-driver#282]
driver.execute('flutter:waitFor', buttonFinder, {durationMilliseconds: 100})

and execute only take 2 args , so I used if failed , could you check ????

   def execute(self, driver_command: str, params: dict = None) -> dict:

**Comment by KazuCocoa** [comment]
In python?
Then, please try out `execute_script` like https://github.com/appium-userland/appium-flutter-driver/blob/3eac68ffc7bf6f27cff0eeea11a6ceadfb2b9a81/example/python/example.py#L33

**Comment by wsfcsk** [comment]
thanks , it's working now
