### ISSUE TITLE
A peer dependency on `^appium@2.0.0-beta.40` is needed

### ISSUE THREAD

**Issue by YanaYankee** [appium-userland/appium-flutter-driver#293]
When running tests on Appium logs a warning is displayed:
Please ask the developer of `appium-flutter-driver` to add a peer dependency on `^appium@2.0.0-beta.40`.
May it be the blocking issue some day please? 

Installed: 
Appium v2.0.0-beta.40
flutter@1.2.0 (automationName 'Flutter')
relaxed-caps@1.0.0-beta.9

<img width="885" alt="image" src="https://user-images.githubusercontent.com/34415065/175289465-38982f72-ab90-43ce-9bb6-5cc61bb77b10.png">

**Comment by KazuCocoa** [comment]
Not yet, but this driver will need it to fully work with newer appium 2 beta. https://github.com/appium-userland/appium-flutter-driver/issues/268 is a PR to update this driver for newer appium 2 beta modules.

**Comment by KazuCocoa** [comment]
Let me keep working this update work in https://github.com/appium-userland/appium-flutter-driver/issues/268
