### ISSUE TITLE
scrollUntilVisible uses `waitFor` that ignores interaction

### ISSUE THREAD

**Issue by mateuszwojtczak** [appium-userland/appium-flutter-driver#301]
Hi!
Current implementation of `scrollUntilVisible` uses `waitFor` for making sure that a widget is visible. The issue is that `waitFor` doesn't ensure us about that, because it only waits for the widget to be available in the widget tree. The result is that the scroll stops, the widget can be out of the viewport and we can't tap on it.

So my suggestion is why don't we use `waitForTappable` in this context?

**Comment by KazuCocoa** [comment]
I don't know the original intention, but perhaps no special reason for it. It just used `waitFor`.
Feel free to create a PR to support the case.
