### ISSUE TITLE
Cannot find module 'appium/driver'

### ISSUE THREAD

**Issue by utpal-maersk** [appium-userland/appium-flutter-driver#302]
**I have all the driver install as below :**

appium driver list --installed                 
WARN Appium Appium encountered 2 warnings while validating drivers found in manifest /Users/###/.appium/node_modules/.cache/appium/extensions.yaml
WARN Appium Driver "flutter" has 1 potential problem: 
WARN Appium   - Driver "flutter" (package `appium-flutter-driver`) may be incompatible with the current version of Appium (v2.0.0-beta.40) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-flutter-driver` to add a peer dependency on `^appium@2.0.0-beta.40`.
✔ Listing installed drivers
- uiautomator2@2.4.1 [installed (NPM)]
- flutter@1.4.0 [installed (NPM)]
- mac2@1.3.0 [installed (NPM)]
- xcuitest@4.7.1 [installed (NPM)]

**After i start the appium server it throws below error :**

[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - uiautomator2@2.4.1 (automationName 'UiAutomator2')
[Appium]   - flutter@1.4.0 (automationName 'Flutter')
[Appium]   - mac2@1.3.0 (automationName 'Mac2')
[Appium]   - xcuitest@4.7.1 (automationName 'XCUITest')

[debug] [Appium] Requiring driver at /Users/#####/.appium/node_modules/appium-flutter-driver
[Appium] Could not load driver 'flutter', so it will not be available. Error in loading the driver was: Cannot find module 'appium/driver'

Appium] Attempting to load driver xcuitest...
[debug] [Appium] Requiring driver at /Users/maersk-55/.appium/node_modules/appium-xcuitest-driver
[Appium] Could not load driver 'xcuitest', so it will not be available. Error in loading the driver was: Cannot find module 'appium/driver'

[Appium] Welcome to Appium v2.0.0-beta.40
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at /Users/maersk-55/.appium/node_modules/appium-uiautomator2-driver
[Appium] Could not load driver 'uiautomator2', so it will not be available. Error in loading the driver was: Cannot find module 'appium/driver'
[Appium] Require stack:

**Comment by utpal-maersk** [comment]
Could you please give me a solution as it blocking for me .
The same was running for earlier apk, where the flutter sdk version  was 2.X and appium-flutter version was 1.2x with appium server 1.7, 
Now after upgrading to Flutter 3.0.3, all the apk are not running , I upgrade the appium to beta 2.0 and flutter-appium to 1.4,

**Comment by KazuCocoa** [comment]
Clean installed appium 2 and flutter driver:
What about removing `.appium` once?
```
kazu $ appium driver install flutter
✔ Installing 'flutter' using NPM install spec 'appium-flutter-driver'
⚠ Driver "flutter" has 1 potential problem:
  - Driver "flutter" (package `appium-flutter-driver`) may be incompatible with the current version of Appium (v2.0.0-beta.40) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-flutter-driver` to add a peer dependency on `^appium@2.0.0-beta.40`.
ℹ Driver flutter@1.4.0 successfully installed
- automationName: Flutter
- platformNames: ["iOS","Android"]
kazu $ appium
WARN Appium Appium encountered 2 warnings while validating drivers found in manifest /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/.cache/appium/extensions.yaml
WARN Appium Driver "flutter" has 1 potential problem:
WARN Appium   - Driver "flutter" (package `appium-flutter-driver`) may be incompatible with the current version of Appium (v2.0.0-beta.40) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-flutter-driver` to add a peer dependency on `^appium@2.0.0-beta.40`.
[Appium] Welcome to Appium v2.0.0-beta.40
[Appium] Attempting to load driver flutter...
[debug] [Appium] Requiring driver at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/appium-flutter-driver
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - flutter@1.4.0 (automationName 'Flutter')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
```

So far, appium 2 has an issue with npm v6, so please use npm v8. (NodeJS v16 has the npm v8 by default, NodeJS v14 needs a new npm version)

**Comment by utpal-maersk** [comment]
> Clean installed appium 2 and flutter driver: What about removing `.appium` once?
> 
> ```
> kazu $ appium driver install flutter
> ✔ Installing 'flutter' using NPM install spec 'appium-flutter-driver'
> ⚠ Driver "flutter" has 1 potential problem:
>   - Driver "flutter" (package `appium-flutter-driver`) may be incompatible with the current version of Appium (v2.0.0-beta.40) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-flutter-driver` to add a peer dependency on `^appium@2.0.0-beta.40`.
> ℹ Driver flutter@1.4.0 successfully installed
> - automationName: Flutter
> - platformNames: ["iOS","Android"]
> kazu $ appium
> WARN Appium Appium encountered 2 warnings while validating drivers found in manifest /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/.cache/appium/extensions.yaml
> WARN Appium Driver "flutter" has 1 potential problem:
> WARN Appium   - Driver "flutter" (package `appium-flutter-driver`) may be incompatible with the current version of Appium (v2.0.0-beta.40) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-flutter-driver` to add a peer dependency on `^appium@2.0.0-beta.40`.
> [Appium] Welcome to Appium v2.0.0-beta.40
> [Appium] Attempting to load driver flutter...
> [debug] [Appium] Requiring driver at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/appium-flutter-driver
> [Appium] Appium REST http interface listener started on 0.0.0.0:4723
> [Appium] Available drivers:
> [Appium]   - flutter@1.4.0 (automationName 'Flutter')
> [Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
> ```
> 
> So far, appium 2 has an issue with npm v6, so please use npm v8. (NodeJS v16 has the npm v8 by default, NodeJS v14 needs a new npm version)

**Comment by utpal-maersk** [comment]
Great :) Thanks a lot ,Problem is resolved by upgrading the npm to v8.
Steps to resolve :
1. Removed ./android folder ->rm -rf ./Android
2. Uninstall appium globally ->npm uninstall -g appium
3. clear npm cache->npm cache clean –force
4. install the latest appium beta 2.0 ->npm install -g appium@next
5. install the drivers ->
-     appium driver install xcuitest
-     appium driver install uiautomator2
-     appium driver install flutter
6 Install plugin ->appium plugin install relaxed-caps
7.Run appium Server ->appium --use-plugins=relaxed-caps -pa /wd/hub --session-override 

[Appium] Attempting to load plugin relaxed-caps...
[debug] [Appium] Requiring plugin at /Users/#####/.appium/node_modules/@appium/relaxed-caps-plugin
[Appium] Welcome to Appium v2.0.0-beta.40
[Appium] Non-default server args:
[Appium] {
[Appium]   basePath: '/wd/hub',
[Appium]   sessionOverride: true,
[Appium]   usePlugins: [
[Appium]     'relaxed-caps'
[Appium]   ]
[Appium] }
[Appium] Attempting to load driver xcuitest...
[debug] [Appium] Requiring driver at /Users/#####/.appium/node_modules/appium-xcuitest-driver
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at /Users/#####/.appium/node_modules/appium-uiautomator2-driver
[Appium] Attempting to load driver flutter...
[debug] [Appium] Requiring driver at /Users/#####/.appium/node_modules/appium-flutter-driver
(node:23548) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - xcuitest@4.7.1 (automationName 'XCUITest')
[Appium]   - uiautomator2@2.4.2 (automationName 'UiAutomator2')
[Appium]   - flutter@1.4.0 (automationName 'Flutter')
[Appium] Available plugins:
[Appium]   - relaxed-caps@1.0.0-beta.9 (ACTIVE)

**Comment by utpal-maersk** [comment]
Closing the issue now
