### ISSUE TITLE
Connection to flutter driver close

### ISSUE THREAD

**Issue by thuonglai** [appium-userland/appium-flutter-driver#310]
Some time i have error :
debug] [FlutterDriver] Executing Flutter driver command 'execute'
[debug] [FlutterDriver] >>> {"command":"waitForTappable","finderType":"ByValueKey","keyValueType":"String","keyValueString":"__screen_manual_scan__shipment_id","timeout":10000}
[FlutterDriver] Connection to ws://127.0.0.1:33581/8NDz6mE0fwk=/ws closed
[FlutterDriver] Connection to ws://127.0.0.1:33581/8NDz6mE0fwk=/ws closed

Appium hangs. I don't know why it happen.

Any help will be appreciated.

**Comment by KazuCocoa** [comment]
I guess the DartVM closed the session for some reason.

When it occurs, could you access to the `ws://127.0.0.1:33581/8NDz6mE0fwk=/ws`, or was the websocket closed?
If closed, maybe DartVM itself closed the websocket port by their internal issue or something.

**Comment by KazuCocoa** [comment]
Please try to access to the `ws://127.0.0.1:33581/8NDz6mE0fwk=/ws`. If the connection got refused, something occurred inside the DartVM. Then, nothing could do on the Appium side.
