### ISSUE TITLE
"Unable to create a new remote session and the app does not exist or is not accessible" error appears when try to run the second BDD scenario 

### ISSUE THREAD

**Issue by MayadaAbdelsalam** [appium-userland/appium-flutter-driver#311]
Issue:
unable to create new remote session for the second BDD scenario running ( app is not exist)  although its installed at the first scenario running successfully .
the capabilities are set to uninstall the app after each scenario

**Environment :**

java : 17.0.2
Appium/ appium flutter :1.22.2
platform : Android
Framework : java +TestNG+ Cucumber 

**Capabilities:**
public AndroidDriver<MobileElement> setup() throws MalformedURLException {
        File rootFile = new File("");
        File appFile = new File(rootFile.getAbsolutePath() + appPtah);
        appPtah = appFile.getAbsolutePath();

        DesiredCapabilities flutterCapabilities = new DesiredCapabilities();
        flutterCapabilities.setCapability( "deviceName", deviceName );
        flutterCapabilities.setCapability( "platformName", platformName );
        flutterCapabilities.setCapability( "platformVersion", platformVersion);
        flutterCapabilities.setCapability("udid",udid);
        flutterCapabilities.setCapability("app",appPtah);
        flutterCapabilities.setCapability("automationName", "Flutter");
        flutterCapabilities.setCapability("skipUnlock","true");
        flutterCapabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "com.rabbit.mart.staging");
        flutterCapabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, "com.rabbit.mart.MainActivity");
        flutterCapabilities.setCapability("noReset", false); 
        flutterCapabilities.setCapability("fullReset", true); 
        flutterCapabilities.setCapability("autoDismissAlerts", true);
        flutterCapabilities.setCapability("autoGrantPermissions", "true");
        flutterCapabilities.setCapability("newCommandTimeout", "45000");
        driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), flutterCapabilities);

**Hooks**
 @Before
    public void setUp() throws MalformedURLException {
        baseObject=new BaseClass();
        baseObject.setup();
        System.out.println("Before all step check");
    }

    @After
    public void tearDown() throws MalformedURLException {
        baseObject=new BaseClass();
        driver.quit();
        System.out.println("After all step check");
    }

**Comment by MayadaAbdelsalam** [comment]
**Appium Error**
[UiAutomator2] Capability 'fullReset' set to 'true', Uninstalling 'com.rabbit.mart.staging'
[ADB] Uninstalling com.rabbit.mart.staging
[ADB] Getting install status for com.rabbit.mart.staging
[ADB] Running '/Users/mayadaabdelsalam/Library/Android/sdk/platform-tools/adb -P 5037 -s 8ABY0HBCZ shell dumpsys package com.rabbit.mart.staging'
[FlutterDriver] Connection to ws://127.0.0.1:38941/IbWgrhTEYzE=/ws closed
[ADB] 'com.rabbit.mart.staging' is installed
[ADB] Running '/Users/mayadaabdelsalam/Library/Android/sdk/platform-tools/adb -P 5037 -s 8ABY0HBCZ shell am force-stop com.rabbit.mart.staging'
[ADB] Running '/Users/mayadaabdelsalam/Library/Android/sdk/platform-tools/adb -P 5037 -s 8ABY0HBCZ uninstall com.rabbit.mart.staging'
[Instrumentation] The process has exited with code 0
[ADB] 'adb uninstall com.rabbit.mart.staging' command output: Success
[ADB] com.rabbit.mart.staging was successfully uninstalled
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running '/Users/mayadaabdelsalam/Library/Android/sdk/platform-tools/adb -P 5037 -s 8ABY0HBCZ forward --remove tcp:8200'
[UiAutomator2] Restoring hidden api policy to the device default configuration
[ADB] Running '/Users/mayadaabdelsalam/Library/Android/sdk/platform-tools/adb -P 5037 -s 8ABY0HBCZ shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[BaseDriver] Event 'quitSessionFinished' logged at 1657795055192 (12:37:35 GMT+0200 (Eastern European Standard Time))
[W3C (897cc5bc)] Received response: null
[W3C (897cc5bc)] But deleting session, so not returning
[W3C (897cc5bc)] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/897cc5bc-d4b4-462b-998b-11d2f090e8e2 200 1745 ms - 14
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/mayadaabdelsalam/Desktop/Apollo-framework-Israa/Users/mayadaabdelsalam/Desktop/Apollo-framework-Israa/AppBuild/app-staging-debug-5.apk","appPackage":"com.rabbit.mart.staging","noReset":false,"autoDismissAlerts":true,"deviceName":"Pixel3XL","fullReset":true,"appActivity":"com.rabbit.mart.MainActivity","newCommandTimeout":"45000","platformVersion":"11","automationName":"Flutter","autoGrantPermissions":"true","skipUnlock":"true","platformName":"Android","udid":"8ABY0HBCZ"},"capabilities":{"firstMatch":[{"appium:app":"/Users/mayadaabdelsalam/Desktop/Apollo-framework-Israa/Users/mayadaabdelsalam/Desktop/Apollo-framework-Israa/AppBuild/app-staging-debug-5.apk","appium:appActivity":"com.rabbit.mart.MainActivity","appium:appPackage":"com.rabbit.mart.staging","appium:autoDismissAlerts":true,"appium:autoGrantPermissions":"true","appium:automationName":"Flutter","appium:deviceName":"Pixel3XL","appium:fullReset":true,"appium:newCommandTimeout":"45000","appium:noReset":false,"platf...
[W3C] Calling AppiumDriver.createSession() with args: [{"app":"/Users/mayadaabdelsalam/Desktop/Apollo-framework-Israa/Users/mayadaabdelsalam/Desktop/Apollo-framework-Israa/AppBuild/app-staging-debug-5.apk","appPackage":"com.rabbit.mart.staging","noReset":false,"autoDismissAlerts":true,"deviceName":"Pixel3XL","fullReset":true,"appActivity":"com.rabbit.mart.MainActivity","newCommandTimeout":"45000","platformVersion":"11","automationName":"Flutter","autoGrantPermissions":"true","skipUnlock":"true","platformName":"Android","udid":"8ABY0HBCZ"},null,{"firstMatch":[{"appium:app":"/Users/mayadaabdelsalam/Desktop/Apollo-framework-Israa/Users/mayadaabdelsalam/Desktop/Apollo-framework-Israa/AppBuild/app-staging-debug-5.apk","appium:appActivity":"com.rabbit.mart.MainActivity","appium:appPackage":"com.rabbit.mart.staging","appium:autoDismissAlerts":true,"appium:autoGrantPermissions":"true","appium:automationName":"Flutter","appium:deviceName":"Pixel3XL","appium:fullReset":true,"appium:newCommandTimeout":"45000","appium:noReset":false,"platformName":"android","appium:platf...
[BaseDriver] Event 'newSessionRequested' logged at 1657795055357 (12:37:35 GMT+0200 (Eastern European Standard Time))
[BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
[BaseDriver]   skipUnlock
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[Appium] Appium v1.22.0 creating new FlutterDriver (v0.0.32) session
[Appium] Applying relaxed security to 'FlutterDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[BaseDriver] Creating session with W3C capabilities: {
[BaseDriver]   "alwaysMatch": {
[BaseDriver]     "platformName": "android",
[BaseDriver]     "appium:skipUnlock": "true",
[BaseDriver]     "appium:app": "/Users/mayadaabdelsalam/Desktop/Apollo-framework-Israa/Users/mayadaabdelsalam/Desktop/Apollo-framework-Israa/AppBuild/app-staging-debug-5.apk",
[BaseDriver]     "appium:appActivity": "com.rabbit.mart.MainActivity",
[BaseDriver]     "appium:appPackage": "com.rabbit.mart.staging",
[BaseDriver]     "appium:autoDismissAlerts": true,
[BaseDriver]     "appium:autoGrantPermissions": "true",
[BaseDriver]     "appium:automationName": "Flutter",
[BaseDriver]     "appium:deviceName": "Pixel3XL",
[BaseDriver]     "appium:fullReset": true,
[BaseDriver]     "appium:newCommandTimeout": "45000",
[BaseDriver]     "appium:noReset": false,
[BaseDriver]     "appium:platformVersion": "11",
[BaseDriver]     "appium:udid": "8ABY0HBCZ"
[BaseDriver]   },
[BaseDriver]   "firstMatch": [
[BaseDriver]     {}
[BaseDriver]   ]
[BaseDriver] }
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[BaseDriver] Capability 'newCommandTimeout' changed from string ('45000') to integer (45000). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   skipUnlock
[BaseDriver]   app
[BaseDriver]   appActivity
[BaseDriver]   appPackage
[BaseDriver]   autoDismissAlerts
[BaseDriver]   autoGrantPermissions
[BaseDriver] Session created with session id: 57877637-d961-411a-bdd5-ba270b3f2b30
[FlutterDriver] Starting an Android proxy session
[BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[BaseDriver] Creating session with W3C capabilities: {
[BaseDriver]   "alwaysMatch": {
[BaseDriver]     "platformName": "android",
[BaseDriver]     "appium:skipUnlock": "true",
[BaseDriver]     "appium:app": "/Users/mayadaabdelsalam/Desktop/Apollo-framework-Israa/Users/mayadaabdelsalam/Desktop/Apollo-framework-Israa/AppBuild/app-staging-debug-5.apk",
[BaseDriver]     "appium:appActivity": "com.rabbit.mart.MainActivity",
[BaseDriver]     "appium:appPackage": "com.rabbit.mart.staging",
[BaseDriver]     "appium:autoDismissAlerts": true,
[BaseDriver]     "appium:autoGrantPermissions": "true",
[BaseDriver]     "appium:automationName": "Flutter",
[BaseDriver]     "appium:deviceName": "Pixel3XL",
[BaseDriver]     "appium:fullReset": true,
[BaseDriver]     "appium:newCommandTimeout": "45000",
[BaseDriver]     "appium:noReset": false,
[BaseDriver]     "appium:platformVersion": "11",
[BaseDriver]     "appium:udid": "8ABY0HBCZ"
[BaseDriver]   },
[BaseDriver]   "firstMatch": [
[BaseDriver]     {}
[BaseDriver]   ]
[BaseDriver] }
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[BaseDriver] Capability 'skipUnlock' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'autoGrantPermissions' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'newCommandTimeout' changed from string ('45000') to integer (45000). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   autoDismissAlerts
[BaseDriver] Session created with session id: 8d1c4788-ca2a-4391-9f2e-27432afda3a0
[UiAutomator2] Deleting UiAutomator2 session
[FlutterDriver] Deleting Flutter Driver session
[BaseDriver] Event 'newSessionStarted' logged at 1657795055384 (12:37:35 GMT+0200 (Eastern European Standard Time))
[W3C] Encountered internal error running command: Error: The application at '/Users/mayadaabdelsalam/Desktop/Apollo-framework-Israa/Users/mayadaabdelsalam/Desktop/Apollo-framework-Israa/AppBuild/app-staging-debug-5.apk' does not exist or is not accessible
[W3C]     at /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/helpers.js:234:13
[HTTP] <-- POST /wd/hub/session 500 28 ms - 981
[HTTP]

**Comment by KazuCocoa** [comment]
Could you try out the latest flutter driver with Appium 2?
They have some improvements related to the initial connection.

**Comment by KazuCocoa** [comment]
Please try out Appium 2 and latest appium-flutter-driver
