### ISSUE TITLE
Compatibility chart between flutter and appium-flutter-driver

### ISSUE THREAD

**Issue by dvyAb** [appium-userland/appium-flutter-driver#314]
Hello @KazuCocoa,

Thank you for your work, is there a way to know if flutter V3 is compatible with the latest appium-flutter-driver(Appium) , do you have a compatibility chart between flutter and appium-flutter-driver versions ?

Thanks

**Comment by KazuCocoa** [comment]
I only try to update https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/CHANGELOG.md
