### ISSUE TITLE
When trying to use "set_clipboard_text" method in native context got error

### ISSUE THREAD

**Issue by jbtech123** [appium-userland/appium-flutter-driver#316]
hi, I got an issue when trying to use "set_clipboard_text" capability in test scripts, app is written in flutter so I need to run FlutterDriver but after change context to native and trying to execute mentioned method I got following error:

[HTTP] {"name":"NATIVE_APP"}
[debug] [W3C (c59b5945)] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","c59b5945-a7c4-4219-8c23-46f829aac262"]
[debug] [FlutterDriver] Executing Flutter driver command 'setContext'
[debug] [W3C (c59b5945)] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/c59b5945-a7c4-4219-8c23-46f829aac262/context 200 8 ms - 14
[HTTP] 
[HTTP] --> POST /wd/hub/session/c59b5945-a7c4-4219-8c23-46f829aac262/appium/device/set_clipboard
[HTTP] {"content":"ZGRkZA==","contentType":"plaintext"}
[debug] [W3C (c59b5945)] Calling AppiumDriver.setClipboard() with args: ["ZGRkZA==","plaintext",null,null,null,"c59b5945-a7c4-4219-8c23-46f829aac262"]
[debug] [FlutterDriver] Executing proxied driver command 'setClipboard'
[debug] [W3C (c59b5945)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[debug] [W3C (c59b5945)]     at AndroidUiautomator2Driver.executeCommand (/Users/j/.nvm/versions/node/v14.18.1/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:328:13)
[debug] [W3C (c59b5945)]     at FlutterDriver.executeCommand (/Users/j/.nvm/versions/node/v14.18.1/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/driver.ts:127:41)
[debug] [W3C (c59b5945)]     at AppiumDriver.executeCommand (/Users/j/.nvm/versions/node/v14.18.1/lib/node_modules/appium/lib/appium.js:563:36)
[debug] [W3C (c59b5945)]     at runMicrotasks (<anonymous>)
[debug] [W3C (c59b5945)]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[debug] [W3C (c59b5945)]     at asyncHandler (/Users/j/.nvm/versions/node/v14.18.1/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
[HTTP] <-- POST /wd/hub/session/c59b5945-a7c4-4219-8c23-46f829aac262/appium/device/set_clipboard 405 49 ms - 904
[HTTP] 

Is there any workaround for that?

**Comment by KazuCocoa** [comment]
Could you share the full log as GIST?

**Comment by jbtech123** [comment]
@KazuCocoa 
https://gist.github.com/jbtech123/2fc52db5dcdbda07be7925d04f964754

**Comment by KazuCocoa** [comment]
Thank you. Could you try out latest appium flutter driver with Appium 2? Newer versions have better context handling.

**Comment by jbtech123** [comment]
on Appium 2 there is the same issue

**Comment by KazuCocoa** [comment]
Could you share the full log as GIST?
