### ISSUE TITLE
keep getting "Original error: Cannot read properties of undefined (reading 'match')" when i try to use flutter driver

### ISSUE THREAD

**Issue by Ben171717** [appium-userland/appium-flutter-driver#317]
Hi!
I am able to run appium with uiautomator2 driver, but when i change to flutter driver i get this error and the apk (AUT) is not open on the emulator. 
I want to use the flutter driver so i will be able to communicate with all the elements. 
this is the JSON created from the Desired Capabilities in appium:

{
  "platformName": "Android",
  "appium:platformVersion": "12.0",
  "appium:deviceName": "Pixel 5",
  "appium:automationName": "flutter",
  "appium:app": "C:\\Users\\**************************************.apk",
  "appium:noReset": "false",
  "appium:maxRetryCount": "20",
  "appium:retryBackoffTime": "500"
}

this is the error i get:
"Failed to create session. An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'match')"

Thanks for any help!

**Comment by KazuCocoa** [comment]
Could you share the full server log as GIST?
I'd use the latest one out if you haven't tried it yet. Please use Appium 2 to use the latest one.

**Comment by Ben171717** [comment]
https://gist.github.com/Ben171717/78ff132069183487858b387edea0f135

and yes, i use appium 2.
Thanks!

**Comment by KazuCocoa** [comment]
Could you try out the latest flutter driver?

**Comment by hai-ha** [comment]
Thanks @KazuCocoa 
I had the same issue with Flutter driver version `1.0.1` while the app side uses Flutter framework 3.0.
When I upgrade to latest Flutter driver, it worked well.
```
appium driver update flutter
✔ Checking if driver 'flutter' is updatable
✔ Checking if driver 'flutter' needs an update
✔ Installing 'flutter' using NPM install spec 'appium-flutter-driver@1.6.0'
✔ Updating driver 'flutter' from 1.0.1 to 1.6.0
```

**Comment by Ben171717** [comment]
im using appium flutter driver version 1.5.0
![Screenshot 2022-08-08 100138](https://user-images.githubusercontent.com/101514884/183358806-a8ea6ec0-b9bf-468e-9e0d-4167f7fccd66.png)

**Comment by KazuCocoa** [comment]
It seems no, your local env used 1.0.1.
```
C:\Users\msbit>appium -p 4723
[Appium] Welcome to Appium v2.0.0-beta.35
[Appium] Attempting to load driver xcuitest...
[debug] [Appium] Requiring driver at C:\Users\msbit\.appium\node_modules\appium-xcuitest-driver
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at C:\Users\msbit\.appium\node_modules\appium-uiautomator2-driver
[Appium] Attempting to load driver flutter...
[debug] [Appium] Requiring driver at C:\Users\msbit\.appium\node_modules\appium-flutter-driver
(node:18660) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - xcuitest@4.4.2 (automationName 'XCUITest')
[Appium]   - uiautomator2@2.1.2 (automationName 'UiAutomator2')
[Appium]   - flutter@1.0.1 (automationName 'Flutter')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] --> POST /session
```

**Comment by Ben171717** [comment]
maybe this is the reason.
when i run appium server it says that flutter is 1.0.1 version.
but in my packege.json i see 1.5.0.
should i downgrade to 1.0.1?

**Comment by Ben171717** [comment]
so i updated flutter driver to 1.6.0 but still get the same error.
[Appium] Available drivers:
[Appium]   - xcuitest@4.4.2 (automationName 'XCUITest')
[Appium]   - uiautomator2@2.1.2 (automationName 'UiAutomator2')
[Appium]   - **flutter@1.6.0 (automationName 'Flutter')**
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.

**Comment by Ben171717** [comment]
ok we are making some progress. now i see this in cmd:
[FlutterDriver] "ext.flutter.driver" is not found in "extensionRPCs" ["ext.ui.window.scheduleFrame","ext.dart.io.getHttpEnableTimelineLogging","ext.dart.io.setHttpEnableTimelineLogging","ext.dart.io.httpEnableTimelineLogging","ext.dart.io.getSocketProfile","ext.dart.io.startSocketProfiling","ext.dart.io.pauseSocketProfiling","ext.dart.io.socketProfilingEnabled","ext.dart.io.clearSocketProfile","ext.dart.io.getVersion","ext.dart.io.getHttpProfile","ext.dart.io.getHttpProfileRequest","ext.dart.io.clearHttpProfile","ext.flutter.reassemble","ext.flutter.exit","ext.flutter.connectedVmServiceUri","ext.flutter.activeDevToolsServerAddress","ext.flutter.platformOverride","ext.flutter.brightnessOverride","ext.flutter.timeDilation","ext.flutter.evict","ext.flutter.invertOversizedImages","ext.flutter.debugPaint","ext.flutter.debugPaintBaselinesEnabled","ext.flutter.repaintRainbow","ext.flutter.debugDumpLayerTree","ext.flutter.debugDisableClipLayers","ext.flutter.debugDisablePhysicalShapeLayers","ext.flutter.debugDisableOpacityLayers","ext.flutter.debugDumpRenderTree","ext.flutter.debugDumpSemanticsTreeInTraversalOrder","ext.flutter.debugDumpSemanticsTreeInInverseHitTestOrder","ext.flutter.profileRenderObjectPaints","ext.flutter.profileRenderObjectLayouts","ext.flutter.debugDumpApp","ext.flutter.showPerformanceOverlay","ext.flutter.didSendFirstFrameEvent","ext.flutter.didSendFirstFrameRasterizedEvent","ext.flutter.fastReassemble","ext.flutter.profileWidgetBuilds","ext.flutter.debugAllowBanner","ext.flutter.debugWidgetInspector","ext.flutter.inspector.structuredErrors","ext.flutter.inspector.show","ext.flutter.inspector.trackRebuildDirtyWidgets","ext.flutter.inspector.trackRepaintWidgets","ext.flutter.inspector.disposeAllGroups","ext.flutter.inspector.disposeGroup","ext.flutter.inspector.isWidgetTreeReady","ext.flutter.inspector.disposeId","ext.flutter.inspector.setPubRootDirectories","ext.flutter.inspector.setSelectionById","ext.flutter.inspector.getParentChain","ext.flutter.inspector.getProperties","ext.flutter.inspector.getChildren","ext.flutter.inspector.getChildrenSummaryTree","ext.flutter.inspector.getChildrenDetailsSubtree","ext.flutter.inspector.getRootWidget","ext.flutter.inspector.getRootRenderObject","ext.flutter.inspector.getRootWidgetSummaryTree","ext.flutter.inspector.getDetailsSubtree","ext.flutter.inspector.getSelectedRenderObject","ext.flutter.inspector.getSelectedWidget","ext.flutter.inspector.getSelectedSummaryWidget","ext.flutter.inspector.isWidgetCreationTracked","ext.flutter.inspector.screenshot"]
[FlutterDriver] Waiting 3 seconds before trying...

**Comment by hai-ha** [comment]
@Ben171717 PLease check this: https://github.com/appium-userland/appium-flutter-driver#usage
- Your Flutter app-under-test (AUT) must be compiled in `debug` or `profile` mode
- Your app should have `enableFlutterDriverExtension()` before `runApp`

**Comment by KazuCocoa** [comment]
Potentially your project does not have flutter_driver dependency in the dev dependencies, too.
```
  flutter_driver:
    sdk: flutter
```

**Comment by Ben171717** [comment]
i already ask the dev to do those actions and the sent me the following screenshots:

![image](https://user-images.githubusercontent.com/101514884/183601279-9a4a2ca2-5e6f-4045-b5b6-b604432f23c2.png)
![image](https://user-images.githubusercontent.com/101514884/183601354-fdf8c035-eb7f-4075-ae83-c06705fc25ea.png)

is there something wrong?

**Comment by KazuCocoa** [comment]
hm, then I have no good idea for now.. The app under test package did not load the `ext.flutter.driver`. I observed the loading took a few seconds on my env sometimes, but then the module load completed a few retry in current logic.

**Comment by Ben171717** [comment]
![image](https://user-images.githubusercontent.com/101514884/183894530-825f97c5-4944-46b0-a5e4-0efcdd0ac008.png)
now i get this error.
after i updated flutter driver in both CMD and VSCode(package.json) to 1.6.0

**Comment by KazuCocoa** [comment]
No idea right now. We should figure out why `ext.flutter.driver` is not in your package. The typical reason is https://github.com/appium-userland/appium-flutter-driver/issues/317#issuecomment-1208877630, but your case succeeded in attaching to the `ws://127.0.0.1:44409/Ql8v3pcZceE=/ws`. It means the comment thing should be ok.

**Comment by DeanPack** [comment]
I get this error if the app isn't closed. The reason this happened to me is because driver.deleteSession() doesn't actually close the app for some reason. I have to close the app manually between each test run or else I get this .match error

**Comment by igortavtib** [comment]
Hey! Having the same issue yesterday, just updated to appium 2 and now it works

**Comment by treeG0** [comment]
face the same issue with appium 2 and the latest flutter driver 1.9
![image](https://user-images.githubusercontent.com/76545539/199871012-46fbbb02-3b72-43c0-aad5-199ebd9ee6a4.png)
![image](https://user-images.githubusercontent.com/76545539/199871883-c498782e-2c5f-47a8-932f-a534ab705649.png)

**Comment by KazuCocoa** [comment]
Did your logcat (Android) or sytemlog (iOS) have observatory URL matched with https://github.com/appium-userland/appium-flutter-driver/blob/338765cfe4786f233ef83692100eaf982fffafb8/driver/lib/sessions/observatory.ts#L178-L184 ?

**Comment by KazuCocoa** [comment]
The latest version has another error message.
https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/lib/sessions/observatory.ts#L190-L193

Close this ticket to separate newer version's issue or old one (which should try out the latest one first)
