### ISSUE TITLE
multiplying durationMilliseconds by 1000

### ISSUE THREAD

**Issue by sirRimell** [appium-userland/appium-flutter-driver#319]
I (I say I, someone far smarter than I) had noted that the code (linked below) is just wrong:

https://github.com/appium-userland/appium-flutter-driver/blob/3eac68ffc7bf6f27cff0eeea11a6ceadfb2b9a81/driver/lib/commands/execute/wait.ts#L13

The documentation example as a result is also wrong:
https://github.com/appium-userland/appium-flutter-driver/blob/3eac68ffc7bf6f27cff0eeea11a6ceadfb2b9a81/example/nodejs/src/index.js#L147

example in test: 

I would expect to be able to pass duration in milliseconds as standard, however, as it's being given as milliseconds*1000 it cause breaks all expectations and results in my day ruined:

`driver.execute('flutter:waitFor', finder, 1);`

expected approach:
driver.execute('flutter:waitFor', finder, 100);

**Comment by sirRimell** [comment]
For those that are having issues with this:

the finder function we have:
:

```
  async function isPresent(finder) {
    try {
      console.log(`Waiting 100ms for ${ finder }...`);
      await driver.execute('flutter:waitFor', finder, 1);
      return true;
    } catch (e) {
      return false;
    }
```

How it looks in test:

```
if (await assertionCommands.isPresent(find.byValueKey())) {
      await inputCommands //do all the fancy things you want to do
    }
```

I hope this helps someone. sharing is caring

**Comment by KazuCocoa** [comment]
Thank you. So, the `* 1000` was redundant, correct?
I'm not the person who implemented it ordinally, so I just read https://github.com/flutter/flutter/blob/74cfc3db67dc89d617ebccd2763301777106c7fd/packages/flutter_driver/lib/src/common/message.dart#L18-L23 . I guess the endpoint to do flutter_driver command is expected milliseconds. then, actually `* 1000` could be redundant in https://github.com/appium-userland/appium-flutter-driver/blob/3eac68ffc7bf6f27cff0eeea11a6ceadfb2b9a81/driver/lib/commands/execute/wait.ts#L13

**Comment by sirRimell** [comment]
^ correct on what you said. 
The multiply here is completely redundant and can be removed. Soon as it is, I'll be able to pass through a normal millisecond parameter.

**Comment by KazuCocoa** [comment]
Personally, it makes sense to send `ms` as same as regular flutter driver side expectation. Let me create a draft pr.

**Comment by KazuCocoa** [comment]
https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/CHANGELOG.md#170
1.7.0 has the change.
