### ISSUE TITLE
driver.deleteSession doesn't close the app

### ISSUE THREAD

**Issue by DeanPack** [appium-userland/appium-flutter-driver#324]
I am using appiums flutter driver to automate my flutter apps testing. When my test conclues, I run driver.deleteSession() as the api says is the same as flutter.close(); Whenever I run my code though, I don't get any errors, but the app doesn't close, I simply get a 200 that says that everything is ok, but the app doesn't actually close. Here is my terminal for driver.deleteSession().

```
[debug] [FlutterDriver@376b (7998e2b5)] Calling AppiumDriver.deleteSession() with args: ["7998e2b5-7ff1-4a4e-ba32-0a564f4b84fd"]
[debug] [AppiumDriver@7ac3] Event 'quitSessionRequested' logged at 1661532829402 (10:53:49 GMT-0600 (Mountain Daylight Time))
[AppiumDriver@7ac3] Removing session 7998e2b5-7ff1-4a4e-ba32-0a564f4b84fd from our master session list
[debug] [FlutterDriver] Deleting Flutter Driver session
[debug] [XCUITestDriver@1df5 (8005f4fd)] Matched '/session/8005f4fd-80a8-4515-b62d-3d6947686576' to command name 'deleteSession'
[debug] [XCUITestDriver@1df5 (8005f4fd)] Proxying [DELETE /session/8005f4fd-80a8-4515-b62d-3d6947686576] to [DELETE http://127.0.0.1:8100/session/8C9842CB-1ADA-44A3-A73A-0811A174B76B] with no body
[debug] [XCUITestDriver@1df5 (8005f4fd)] Got response with status 200: {"value":null,"sessionId":null}
[DevCon Factory] Releasing connections for 14602CD8-810B-4D5E-89FF-B6BD48C0EBBA device on any port number
[DevCon Factory] Found cached connections to release: ["14602CD8-810B-4D5E-89FF-B6BD48C0EBBA:8100"]
[debug] [DevCon Factory] Cached connections count: 0
[debug] [XCUITestDriver@1df5 (8005f4fd)] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [IOSSimulatorLog] Stopping iOS log capture
[debug] [AppiumDriver@7ac3] Event 'quitSessionFinished' logged at 1661532829410 (10:53:49 GMT-0600 (Mountain Daylight Time))
[debug] [AppiumDriver@7ac3] Received response: null
[debug] [AppiumDriver@7ac3] But deleting session, so not returning
[debug] [AppiumDriver@7ac3] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /session/7998e2b5-7ff1-4a4e-ba32-0a564f4b84fd 200 9 ms - 14
```

This is especially annoying, because since the session isn't properly deleted whenever I try to run a test again, it fails because the session isn't properly setup and initialization of the new test fails because it can't .match(session) because session is undefined.

**Comment by KazuCocoa** [comment]
Appium terminates the app under test via https://developer.apple.com/documentation/xctest/xcuiapplication/1500637-terminate in
```
[debug] [XCUITestDriver@1df5 (8005f4fd)] Matched '/session/8005f4fd-80a8-4515-b62d-3d6947686576' to command name 'deleteSession'
[debug] [XCUITestDriver@1df5 (8005f4fd)] Proxying [DELETE /session/8005f4fd-80a8-4515-b62d-3d6947686576] to [DELETE http://127.0.0.1:8100/session/8C9842CB-1ADA-44A3-A73A-0811A174B76B] with no body
[debug] [XCUITestDriver@1df5 (8005f4fd)] Got response with status 200: {"value":null,"sessionId":null}
```
So, perhaps XCTest framework (by Apple) did not terminate your app process properly.

You could try out https://github.com/appium/appium-xcuitest-driver#mobile-killapp to kill the app process outside XCTest

**Comment by KazuCocoa** [comment]
It would be helpful to share the full appium server log to find possible issues

**Comment by KazuCocoa** [comment]
btw, I saw similar reports in the appium repo about Apple's terminate app did not kill their app process occasionally... The original reported issue also potentially the same. Then, my previous comment's one may help
