### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by 25385648** [appium-userland/appium-flutter-driver#327]
I am using the Flutter driver, but the error is reported:
Startup info:
    desired_caps = {}
     desired_caps['platformName'] = 'Android'
     desired_caps['platformVersion'] = '9.0'
     desired_caps['deviceName'] = 'ce10171a2a6f7d23047e'
     desired_caps['app'] = r'D:\sm.apk'
     desired_caps['automationName'] = 'flutter'
     driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
     finder = FlutterFinder()

Encountered internal error running command: TypeError: Cannot read property 'match' of undefined
[W3C]     at Object.exports.processLogToGetobservatory (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-flutter-driver\build\driver\lib\sessions\observatory.js:118:9)
[W3C]     at Object.exports.getObservatoryWsUri (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-flutter-driver\lib\sessions\android.ts:34:21)
[W3C]     at Object.exports.startAndroidSession (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-flutter-driver\lib\sessions\android.ts:25:28)
[W3C]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[W3C]     at FlutterDriver.exports.createSession (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-flutter-driver\lib\sessions\session.ts:18:47)
[W3C]     at AppiumDriver.createSession (C:\Program Files\Appium\resources\app\node_modules\appium\lib\appium.js:371:35)
[HTTP] <-- POST /wd/hub/session 500 72181 ms - 647

**Comment by arctouch-thiagowerner** [comment]
Same here. I am using the example from this repository.

**Comment by KazuCocoa** [comment]
Could you share the full appium server log as GIST?

**Comment by arctouch-thiagowerner** [comment]
I am not sure if that's what you're looking for. 
[appium-server-logs.txt](https://github.com/appium-userland/appium-flutter-driver/files/9537626/appium-server-logs.txt)

**Comment by KazuCocoa** [comment]
Please use the latest one with Appium 2 https://github.com/appium-userland/appium-flutter-driver#installation
```
[info] [35m[Appium][39m Appium v1.22.0 creating new FlutterDriver (v0.0.32) session
[debug] [35m[Appium][39m There are no active sessions for cleanup
```

**Comment by arctouch-thiagowerner** [comment]
Solved following these steps:

1. Run ```$ npm install -g appium@next```, so it will enable some additional features in your Appium;
2. Run ```$ appium driver install xcuitest``` we need to install the default drivers manually;
3. Run ```$ appium driver install uiautomator2``` we need to install the default drivers manually;
4. Run ```$ appium driver install flutter``` finally installing flutter driver;
5. Remove ```/wd/hub``` from Appium baseUrl.

**Comment by KazuCocoa** [comment]
hm, 2 and 3 are not necessary since 4 includes them in the package dependency
