### ISSUE TITLE
Package "appium_flutter_driver" does not exist while running CI/CD through maven commands 

### ISSUE THREAD

**Issue by MayadaAbdelsalam** [appium-userland/appium-flutter-driver#335]
when running the project through IDE (intellij) it works fine but when running the project through maven commands on CI/CD it didnt compile with this error "Package "appium_flutter_driver" does not exist "
i checked this below ticket but still not working with me ,,,,can anyone share with me the environments checks so that it works fine?
 https://github.com/appium-userland/appium-flutter-driver/issues/29

**Comment by ashwithpoojary98** [comment]
check here
https://github.com/ashwithpoojary98/javaflutterfinder

**Comment by MayadaAbdelsalam** [comment]
Hello ,

we managed to find the issue and updated it ,,,,it works fine now 
will mention the way we figured it out for anyone.

-Adding the appium flutter driver folder inside the project and and the below lines in the POM file 
 <configuration>
                        
                            <sourceDirs>
                                <sourceDir>${project.basedir}/src/test/java/appium_flutter_driver</sourceDir>
                                <sourceDir>${project.basedir}/src/test/java/appium_flutter_driver/finder</sourceDir>
                            
                            </sourceDirs>
                        </configuration>
