### ISSUE TITLE
Dart Observatory failing to connect on ios devices running on browserstack with wdio framework

### ISSUE THREAD

**Issue by IOnilearan** [appium-userland/appium-flutter-driver#342]
dart observatory cannot connect meaning the session closes and the automation tests cannot start

Environment
Appium 2

config.capabilities = [
platformName: 'iOS',
automationName: 'flutter',
observatoryWsUri: 'ws://127.0.0.1:8283/8283=ws'
device: "device",
app: "browserstackurl"
]

https://gist.github.com/IOnilearan/288b72b8058f53cde81517bb74a7e484

**Comment by IOnilearan** [comment]
Hello @KazuCocoa here is my issue, thanks

**Comment by IOnilearan** [comment]
@KazuCocoa your previous example was for android, is it similar in ios? Also do i need to run the dart observatory myself for this to work?

**Comment by KazuCocoa** [comment]
Both do the same thing, android is via adb command, ios is via appium-ios-device lib.
https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/lib/sessions/ios.ts

**Comment by IOnilearan** [comment]
@KazuCocoa hmm i see, i will need to add the observatoryWsUri as its not working at the moment. do you know if you are able to set the capability but at the same time keep the config/spec file format. As i do not see any examples with this scenario in this repo. 

scenario
ios.config has the capabilities and the listed spec files to run

**Comment by KazuCocoa** [comment]
Sorry, what do you mean...?

**Comment by KazuCocoa** [comment]
I haven't tested yet, but maybe https://github.com/appium-userland/appium-flutter-driver/pull/343 will work with the capability

**Comment by IOnilearan** [comment]
> Sorry, what do you mean...?

I mean will I be able to add the capability via a .config file like this https://webdriver.io/docs/organizingsuites/
instead of in index.js

**Comment by thuonglai** [comment]
@KazuCocoa . When i set capabilities.setCapability("observatoryWsUri","ws://127.0.0.1:8283/8283=ws"). It seem can't connect to Dart Observatory. 
My Appium log is : 
[FlutterDriver] Attempt #9
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:8283/8283=ws
[FlutterDriver] [object Object]
[FlutterDriver] Check Dart Observatory URI ws://127.0.0.1:8283/8283=ws
[FlutterDriver] Waiting 5 seconds before trying...
[HTTP] --> GET /session/fe2e9efb-a5ab-4c8b-b66f-bb02989a053d/timeouts
[HTTP] {}
[debug] [HTTP] No route found for /session/fe2e9efb-a5ab-4c8b-b66f-bb02989a053d/timeouts
[HTTP] <-- GET /session/fe2e9efb-a5ab-4c8b-b66f-bb02989a053d/timeouts 404 2 ms - 262
[HTTP] 
[FlutterDriver] Attempt #10
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:8283/8283=ws
[FlutterDriver] [object Object]
[FlutterDriver] Check Dart Observatory URI ws://127.0.0.1:8283/8283=ws
[FlutterDriver] Waiting 5 seconds before trying...
[HTTP] --> GET /session/fe2e9efb-a5ab-4c8b-b66f-bb02989a053d/timeouts
[HTTP] {}
[debug] [HTTP] No route found for /session/fe2e9efb-a5ab-4c8b-b66f-bb02989a053d/timeouts
[HTTP] <-- GET /session/fe2e9efb-a5ab-4c8b-b66f-bb02989a053d/timeouts 404 1 ms - 262
[HTTP] 
[FlutterDriver] Attempt #11
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:8283/8283=ws
[FlutterDriver] [object Object]
[FlutterDriver] Check Dart Observatory URI ws://127.0.0.1:8283/8283=ws
[FlutterDriver] Waiting 5 seconds before trying...
[HTTP] --> GET /session/fe2e9efb-a5ab-4c8b-b66f-bb02989a053d/timeouts
[HTTP] {}

**Comment by KazuCocoa** [comment]
As my last comment, https://github.com/appium-userland/appium-flutter-driver/pull/343 may handle the connection @thuonglai

@IOnilearan So, if you can add `observatoryWsUri` capability in the `.config` file? Then, it might be as a regular `capabilities` section

**Comment by IOnilearan** [comment]
Hello @KazuCocoa, Thanks for your help so far however it still doesnt seem to pick up the capability this way. I think its due to the fact it is only looking for Appium capabilities and not appium flutter driver

**Comment by KazuCocoa** [comment]
You used `2022-10-04 09:40:49:244 - [Appium] Appium v1.22.0 creating new FlutterDriver (v0.0.32) session`
I see, you used old version, which did not have the feature yet. Please try out appium 2 with the latest flutter driver

**Comment by IOnilearan** [comment]
@KazuCocoa Ahh I see, browserstack is not yet compatible with appium 2. I will try this locally

**Comment by IOnilearan** [comment]
@KazuCocoa is Appium 2 available on npm?

**Comment by thuonglai** [comment]
@KazuCocoa . I manual update appium-flutter-driver as you commited in [https://github.com/appium-userland/appium-flutter-driver/pull/343](#343 ). It still happen as

 [FlutterDriver] Attempt https://github.com/appium-userland/appium-flutter-driver/issues/11
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:8283/8283=ws
[FlutterDriver] [object Object]
[FlutterDriver] Check Dart Observatory URI ws://127.0.0.1:8283/8283=ws
[FlutterDriver] Waiting 5 seconds before trying...

**Comment by IOnilearan** [comment]
> > 2022-10-04 09:40:49:244 - [Appium] Appium v1.22.0 creating new FlutterDriver (v0.0.32) session
> 
> I see, you used the old version, which did not have the feature yet. Please try out appium 2 with the latest flutter driver



> Hello @KazuCocoa, Thanks for your help so far however it still doesnt seem to pick up the capability this way. I think its due to the fact it is only looking for Appium capabilities and not appium flutter driver

Hello @KazuCocoa I tried adding the capability observatoryWsUri but it fails to recognise it. I am on the latest

**Comment by KazuCocoa** [comment]
Could you share the full appium server log and the device log (or with `appium:showIOSLog` `true` capability)?


> Do I have to run it the standalone way or is there a way to use the wdio testrunner framework with appium flutter driver

It depends on how you'd like to manage the app under test (if I understand correctly...). The `observatoryWsUri` is designed to attach to the URL explicitly. So, the typical use case is when the app under test is managed outside appium. I guess the "standalone" way means this. (and I thought what you would have liked to do)

Usually appium flutter driver tries to find the URL by reading system log automatically. Then, you can use appum-flutter-driver as same as other appium drivers.

**Comment by thuonglai** [comment]
Hi @KazuCocoa . It is may appium log : https://gist.github.com/thuonglai/7434a67bfa444911a78c613b514cc308.
And following is fullter log 
Showing Android SDK built for arm64 logs:
D/FlutterGeolocator( 6505): Attaching Geolocator to activity
W/FlutterActivityAndFragmentDelegate( 6505): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
D/FlutterGeolocator( 6505): Creating service.
D/FlutterGeolocator( 6505): Binding to location service.
D/FlutterLocationService( 6505): Creating service.
D/FlutterLocationService( 6505): Binding to location service.
I/flutter ( 6505): The Dart VM service is listening on http://127.0.0.1:38717/oycPsuwWh_0=/
D/FlutterGeolocator( 6505): Geolocator foreground service connected
D/FlutterGeolocator( 6505): Initializing Geolocator services
I/flutter ( 6505): path axlmap: /data/user/0/com.axlehire.drive.staging/app_flutter/axlmap3.db
I/flutter ( 6505): Open maser db at axlmap3.db

**Comment by KazuCocoa** [comment]
Thank you. One question. Why did you set `appium:observatoryWsUri` as `ws://127.0.0.1:8283/8283=ws`? It seems like the attached logcat has `The Dart VM service is listening on http://127.0.0.1:38717/oycPsuwWh_0=/`. The appium driver driver will find it and attempt to attach to the URL if no `appium:observatoryWsUri` is given.

**Comment by thuonglai** [comment]
I set appium:observatoryWsUri random. Becauce i don't how set url before app lauch. "The Dart VM service is listening on http://127.0.0.1:38717/oycPsuwWh_0=/" only display when open app.

**Comment by KazuCocoa** [comment]
The URL is generated by Flutter internally. So, you do not need to set it as the most general example in https://github.com/appium-userland/appium-flutter-driver#example

**Comment by KazuCocoa** [comment]
I haven't tried, but you can customize the observatory port like https://github.com/flutter/flutter/blob/4cf60f7659cba379200b7d80ceb45d020dae560e/packages/flutter_tools/lib/src/tester/flutter_tester.dart#L176 with flutter command.

**Comment by thuonglai** [comment]
Hi @KazuCocoa . Now, i not set observatoryWsUri. But sometime, i test with device over wifi, it can't detect this url. So i think can use  observatoryWsUri. 
And i customize as below it error: 
fvm flutter build apk --dart-define=DEFAULT_ENVIRONMENT_NAME=staging --debug --flavor staging -t lib/main_test.dart --observatory-port 15434
Could not find an option named "observatory-port".

**Comment by KazuCocoa** [comment]
I haven't dug the flutter options. I just read flutter team's test code and found the option. So at least they used the option. Potentially the name is different in the flutter command, or they do not expose the option for users.

> _over wifi_

I'm not sure if the flutter team expected the usage since their system print the observatory URL as localhost. In your case, I guess this driver tries to connect to the device as localhost as the flutter logs to the system log.

In the use case, I guess you may need to implement reading observatory URL from the system and replace the localhost URL to the device's wifi address in your test code

**Comment by IOnilearan** [comment]
@KazuCocoa this works find for android but ios doesnt, I think it may have something to do with port forwarding or the observatory URI as seen in the logs

**Comment by KazuCocoa** [comment]
Appium does not provide over WiFi iOS devices with regular toolchains. I guess you can try something 3rd party's port forward by yourself like using iproxy. Then, `appium:skipPortForward` can skip handling portforward by this driver.

**Comment by KazuCocoa** [comment]
It seems like this issue has more topics from the initial title about browserstack. I'm not sure if they support this driver, but about the browserstack, please ask the support team. Close this ticket to not mix various topics here
