### ISSUE TITLE
Can tests written with appium-flutter-driver run on AWS device farm?

### ISSUE THREAD

**Issue by Bouqui** [appium-userland/appium-flutter-driver#345]
I will like to know if tests written with appium-flutter driver can be run on AWS device farm

**Comment by KazuCocoa** [comment]
I have no idea. You may need to ask the support team first.

**Comment by mbilbiesi** [comment]
Hello @Bouqui, 

Did you get a chance to contact the support team and confirm if they support Appium Flutter Driver? I am trying to look for this information, and no clear answer for that.

Regards,
Mazen
