### ISSUE TITLE
Flutter Appium tests crash on real iOS device with Appium 2

### ISSUE THREAD

**Issue by hudson-pierce** [appium-userland/appium-flutter-driver#348]
I have received the following error when running tests with the Flutter driver for iOS on the latest Appium 2 version:

<blockquote>
E   selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: A new session could not be created. Details: Cannot launch scanbot.sdk.ui.test.app.flutter application. Make sure the correct bundle identifier has been provided in capabilities and check the device log for possible crash report occurrences Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

E   Stacktrace:
E   UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: A new session could not be created. Details: Cannot launch scanbot.sdk.ui.test.app.flutter application. Make sure the correct bundle identifier has been provided in capabilities and check the device log for possible crash report occurrences Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
E       at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:956:9)
E       at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:435:35)
</blockquote>

On the iOS device the Flutter app attempts to load, but then quickly crashes. I recorded the following video to demonstrate what is happening...

https://user-images.githubusercontent.com/81746805/195052206-8ceaa6fa-3307-4efb-a154-8b5596476cfd.mov

Running the app normally in Flutter works perfectly fine. This issue only occurs when running Appium tests.

Also, this issue only occurs on real devices for me. I have no problems when running on an iOS Simulator or on Android devices. 

### Device Information: 
The issue has been reproduced on the following devices:
- iPhone 11 Pro, 15.6.1
- iPhone XR, 15.5

### Version Information:
- appium v2.0.0-beta.44
- flutter v3.3.4
- appium-flutter-driver v1.7.2
- Xcode 14.0.1

**Comment by KazuCocoa** [comment]
It seems like the app got something crashed. The app launch itself started from Apple's API, so maybe you may need to take a look the crash log and investigate the reason in your code.

```
default	08:48:06.964143+0200	ReportCrash	Formulating fatal 309 report for corpse[77884] Runner
default	08:48:06.965683+0200	ReportCrash	loadStoreInfo [platform 2] scanbot.sdk.ui.test.app.flutter from file:///private/var/containers/Bundle/Application/F2E6AF63-B8A4-4047-A258-E393597A1A3E/scanbot.sdk.ui.test.app.flutter.app/
default	08:48:06.967042+0200	ReportCrash	unable to retrieve storeCohort: <private>
default	08:48:06.971081+0200	ReportCrash	post-exception thread qos drop 21 -> 17
default	08:48:06.971978+0200	osanalyticshelper	starting prolongation transaction timer
default	08:48:06.972485+0200	osanalyticshelper	S1. helper service invoked for '<private>' report creation on behalf of <private>
default	08:48:06.975817+0200	osanalyticshelper	Received log event: <private>
default	08:48:06.976042+0200	osanalyticshelper	S2. helper service creating file
default	08:48:06.982728+0200	ReportCrash	C6. report request failed: <private>
default	08:48:06.982947+0200	ReportCrash	client log create type 309 result FAILED: Log limit exceeded
default	08:48:06.987234+0200	ReportCrash	scanbot.sdk.ui.test.app.flutter is not a MetricKit client
default	08:48:06.987406+0200	ReportCrash	Sending event: com.apple.stability.crash {"bundleID":"scanbot.sdk.ui.test.app.flutter","bundleVersion":"1","exceptionCodes":"0x0000000000000001, 0x0000000000000000(\n    1,\n    0\n)EXC_BAD_ACCESSSIGSEGVKERN_INVALID_ADDRESS at 0x0000000000000000","incidentID":"31D2572D-9DD4-4C1B-931F-C932BCE28143","logwritten":0,"process":"Runner","terminationReasonExceptionCode":"0xb","terminationReasonNamespace":"SIGNAL"}
default	08:48:06.987548+0200	ReportCrash	recordCrashEvent; isBeta 0, log: '(null)'
default	08:48:06.990274+0200	analyticsd	Received event: com.apple.stability.crash {"bundleID":"scanbot.sdk.ui.test.app.flutter","bundleVersion":"1","exceptionCodes":"0x0000000000000001, 0x0000000000000000(\n    1,\n    0\n)EXC_BAD_ACCESSSIGSEGVKERN_INVALID_ADDRESS at 0x0000000000000000","incidentID":"31D2572D-9DD4-4C1B-931F-C932BCE28143","logwritten":0,"process":"Runner","terminationReasonExceptionCode":"0xb","terminationReasonNamespace":"SIGNAL"}
default	08:48:06.991396+0200	analyticsd	Aggregated. Transform: StabilityCrashNumerator3WithBundleVersion Dirty: 1 Event: com.apple.stability.crash {"bundleID":"scanbot.sdk.ui.test.app.flutter","bundleVersion":"1","exceptionCodes":"0x0000000000000001, 0x0000000000000000(\n    1,\n    0\n)EXC_BAD_ACCESSSIGSEGVKERN_INVALID_ADDRESS at 0x0000000000000000","incidentID":"31D2572D-9DD4-4C1B-931F-C932BCE28143","logwritten":0,"process":"Runner","terminationReasonExceptionCode":"0xb","terminationReasonNamespace":"SIGNAL","timestamp":1665557286878499}
default	08:48:06.991559+0200	analyticsd	[TransformManager::checkpoint] Checkpoint initiated. Persistence time throttle expired. Additional info {eventsSeen: 4, eventsRequired: 100000}
default	08:48:06.998673+0200	analyticsd	Persisted Transform: StabilityCrashNumerator3WithBundleVersion Dirty: 1
default	08:48:07.020591+0200	analyticsd	Aggregated. Transform: StabilityCrashNumerator3WithIncidentID Dirty: 1 Event: com.apple.stability.crash {"bundleID":"scanbot.sdk.ui.test.app.flutter","bundleVersion":"1","exceptionCodes":"0x0000000000000001, 0x0000000000000000(\n    1,\n    0\n)EXC_BAD_ACCESSSIGSEGVKERN_INVALID_ADDRESS at 0x0000000000000000","incidentID":"31D2572D-9DD4-4C1B-931F-C932BCE28143","logwritten":0,"process":"Runner","terminationReasonExceptionCode":"0xb","terminationReasonNamespace":"SIGNAL","timestamp":1665557286878499}
default	08:48:07.022049+0200	analyticsd	[Daemon perf] Performance checks are disabled. Please update the daemon perf params in defaults if you wish to turn this on.
default	08:48:07.022700+0200	analyticsd	Aggregated. Transform: StabilityCrashNumerator3 Dirty: 1 Event: com.apple.stability.crash {"bundleID":"scanbot.sdk.ui.test.app.flutter","bundleVersion":"1","exceptionCodes":"0x0000000000000001, 0x0000000000000000(\n    1,\n    0\n)EXC_BAD_ACCESSSIGSEGVKERN_INVALID_ADDRESS at 0x0000000000000000","incidentID":"31D2572D-9DD4-4C1B-931F-C932BCE28143","logwritten":0,"process":"Runner","terminationReasonExceptionCode":"0xb","terminationReasonNamespace":"SIGNAL","timestamp":1665557286878499}
default	08:48:07.022929+0200	analyticsd	[TransformManager::checkpoint] Checkpoint initiated (forced)
error	08:48:07.057106+0200	kernel	Failed to read key 1195856451 from SMC with error code 84
default	08:48:07.099457+0200	fmflocatord	{"msg":"CLInternalGetAuthorizationStatus", "event":"activity"}
```

**Comment by KazuCocoa** [comment]
Close as not this driver's one

**Comment by hudson-pierce** [comment]
In case it helps someone else, I resolved this particular issue by using `flutter run --profile` instead of `flutter run --debug` to build the app. It seems related to this: https://stackoverflow.com/a/64211651
