### ISSUE TITLE
The 'flutter:waitFor' command doesn't work with '{durationMilliseconds: 100}' option

### ISSUE THREAD

**Issue by DKasianova** [appium-userland/appium-flutter-driver#349]
**First case**
Using the `flutter:waitFor` command with `{durationMilliseconds: 100}` as specified in the appium-flutter-driver [Commands](https://github.com/appium-userland/appium-flutter-driver#commands) returns an error:
```
 An unknown server-side error occurred while processing the command. Original error: durationMilliseconds is not a valid options.
```

Command example:
```
await driver.execute('flutter:waitFor', find.byValueKey('password'), {durationMilliseconds: 100});
```

**Second case**
If use the `flutter:waitFor` command with `milliseconds` as mentioned in one of the 'Issues' here, for example:
```
await driver.execute('flutter:waitFor', find.byValueKey('password'), 5000);
``` 
It works, the command waits for 5 seconds (with 3 tries, 15 seconds in total), BUT in case the element is not displayed within the specified time - it also returns an server-side error:
```
 An unknown server-side error occurred while processing the command. Original error: Cannot execute command waitFor, server reponse {
  "isError": true,
  "response": "Timeout while executing waitFor: TimeoutException after 0:00:05.000000: Future not completed\n",
  "type": "_extensionType",
  "method": "ext.flutter.driver"
}
```

I'm using WebdriverIO + appium 2.0.0-beta.44 + appium-flutter-driver 1.7.2 + appium-flutter-finder 0.1.0

So what is the correct way to use the `flutter:waitFor` command? Maybe there is some other alternative?

**Comment by thuonglai** [comment]
You can use function as following :
public static boolean isPresent(FlutterElement element, int timeout) {
        try {
            Object a = driver.executeScript("flutter:waitFor", element, timeout);
            return a != null;
        } catch (Exception ex) {
            return false;
        }
    }
If can wait element it return false. You can stop or continue test.

**Comment by KazuCocoa** [comment]
Thank you. I've modified the readme

**Comment by DKasianova** [comment]
@KazuCocoa thanks for updates!
But what about the error that is logged if the `flutter:waitFor` command didn't wait for an element? I assume that the error 
```
 An unknown server-side error occurred while processing the command. Original error: Cannot execute command waitFor, server reponse {
  "isError": true,
  "response": "Timeout while executing waitFor: TimeoutException after 0:00:05.000000: Future not completed\n",
  "type": "_extensionType",
  "method": "ext.flutter.driver"
}
```
isn't quite a suitable error for this case?

**Comment by KazuCocoa** [comment]
The error and the behavior itself come from Flutter/Dart VM. Appium flutter driver just sends commands defined in https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html to them. Thus, if something behavior seems weird, maybe you need to report it in the Flutter team. (but I guess they won't maintain the flutter_driver so much.)
