### ISSUE TITLE
Obervatoryurl was not found in device log

### ISSUE THREAD

**Issue by bqMoonlight** [appium-userland/appium-flutter-driver#366]
I am doing testing on android/ios real devices.

When using native driver i connect and have no issues using appium inspector. When using flutter driver, session starts, budleid provided gets opened but then i get error
"failed to create session. An unknown sercer side error.
Original error :no observatory url was found in the device log"
Since i have only acces to the apk or ipa files, i was wondering what would be best way to deal with this. 

Checking certificate on apk file i can see its signed, so it could be that app is not in debuging mode. 

Or am i making mistake somewhere else, coyld i somehow find out the observatoryurl myself, so i can manuelly add it to the desired capabilities

**Comment by KazuCocoa** [comment]
> Your Flutter app-under-test (AUT) must be compiled in debug or profile mode, because Flutter Driver does not support running in release mode.. Also, ensure that your Flutter AUT has enableFlutterDriverExtension() before runApp. Then, please make sure your app imported [flutter_driver](https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html) package as its devDependencies as well.

https://github.com/appium-userland/appium-flutter-driver#usage

So, to use this driver (via Flutter's testing logic), the app must be a debuggable one

**Comment by KazuCocoa** [comment]
It seems like the reported test target was not testable as the flutter framework as not a debuggable build
