### ISSUE TITLE
The "WaitFor" method does not work with 'Drawer' element

### ISSUE THREAD

**Issue by s-yarkinov** [appium-userland/appium-flutter-driver#368]
**When trying to find a driver element via waitFor, an exception is thrown, there may also be problems with other elements**

Code

`(FlutterElement) driver.executeScript("flutter:waitFor", finder.byValueKey("drawer_button"), 3000)`

Exeption
```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot execute command waitFor, server reponse {
  "isError": true,
  "response": "Timeout while executing waitFor: TimeoutException after 0:00:03.000000: Future not completed\n",
  "type": "_extensionType",
  "method": "ext.flutter.driver"
}
```

Stack:
```
Appium: 2.0.0-beta.46
Java: 11
appium-flutter-driver@1.9.1
appium_flutterfinder_java: 1.0.0


Flutter 3.3.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 52b3dc25f6 (8 days ago) • 2022-11-09 12:09:26 +0800
Engine • revision 857bd6b74c
Tools • Dart 2.18.4 • DevTools 2.15.0
```

[logAppium.txt](https://github.com/appium-userland/appium-flutter-driver/files/10028750/logAppium.txt)

Please help me, what can I do about it?

**Comment by thuonglai** [comment]
May be it is not enough time to wait or wrong key element. It still work with drawer in my project.

**Comment by s-yarkinov** [comment]
I set the wait to 30 seconds, it didn't help
```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot execute command waitFor, server reponse {
  "isError": true,
  "response": "Timeout while executing waitFor: TimeoutException after 0:00:30.000000: Future not completed\n",
  "type": "_extensionType",
  "method": "ext.flutter.driver"
}
```

The locator is exactly correct, I added it myself, the code example is below, maybe you can share how you assign a locator to an element in your project, I will be very grateful?

```
drawer: Drawer(
        key: const Key('drawer_button'),
        child: ListView(
          padding: EdgeInsets.zero,
          children: const <Widget>[
            DrawerHeader(
              key: Key('drawer_header'),
              decoration: BoxDecoration(
                color: Colors.blue,
              ),
              child: Text(
                'Drawer Header',
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 24,
                ),
              ),
            ),
            ListTile(
              key: Key('message_button'),
              leading: Icon(Icons.message),
              title: Text('Messages'),
            ),
            ListTile(
              key: Key('profile_button'),
              leading: Icon(Icons.account_circle),
              title: Text('Profile'),
            ),
            ListTile(
              key: Key('settings_button'),
              leading: Icon(Icons.settings),
              title: Text('Settings'),
            ),
          ],
        ),
      ),
```
[logAppium.txt](https://github.com/appium-userland/appium-flutter-driver/files/10030059/logAppium.txt)

**Comment by thuonglai** [comment]
Can you take screenshot when has drawer?

**Comment by s-yarkinov** [comment]
> Can you take screenshot when has drawer?

I didn't quite understand the question, if you mean can I take a screenshot through the driver, then yes.

If you mean that I showed on the screenshot that the 'drawer' is displayed, I attached a photo from below

![test png_screen](https://user-images.githubusercontent.com/61181657/202675810-fc560429-55a3-4ee0-bc01-8f5e12fa9489.png)

**Comment by thuonglai** [comment]
I think you must click icon to show menu "Drawer Header". As picture it not visible in page

**Comment by s-yarkinov** [comment]
> I think you must click icon to show menu "Drawer Header". As picture it not visible in page

![image](https://user-images.githubusercontent.com/61181657/202683366-55534b28-7bfa-473e-aa6a-1eaf6cc0685f.png)

**Comment by thuonglai** [comment]
Yes. Now i think it can waitFor "drawer_button". Do you still has this error ?

**Comment by s-yarkinov** [comment]
@thuonglai Yes, indeed, when the Drawer is open, I manage to find the element,  I need to figure out the structure of the driver, thanks for the help
