### ISSUE TITLE
Set timeout on flutter:scrollUntilVisible

### ISSUE THREAD

**Issue by MatteoAntolini** [appium-userland/appium-flutter-driver#372]
When `flutter:scrollUntilVisible` can't find the item, it goes on an infinite loop of waiting. It retries 3 times with a frequency of 60 and a timeout of 100000 milliseconds and after that, no other action is performed.  

Flutter code
```dart
void main() {
  enableFlutterDriverExtension();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(
        key: const Key("list"),
        children: List.generate(
            18,
            (index) => Container(
                  key: Key(index.toString()),
                  height: 100,
                  color: Colors.primaries[index],
                )),
      ),
    );
  }
}
```

Appium Code Node.js
```javascript
  const driver = await wdio.remote(opts);

  const list = find.byValueKey('list');

  index = 0;

  while (true) {
    console.log(index);
    var visible = true;

    const item = find.byValueKey(index + "");

    await driver.execute(
      "flutter:scrollUntilVisible",
      list,
      { "item": item, "dxScroll": 0, "dyScroll": -100}
    ).catch((_) => visible = false);

    if (!visible) {
      break;
    }

    await new Promise(resolve => setTimeout(resolve, 1000));

    index += 1;
  }

  //Scroll back to the first. This is visible in the log, but never executed
  await driver.execute(
    "flutter:scrollUntilVisible",
    list,
    { "item": find.byValueKey("0"), "dxScroll": 0, "dyScroll": 100 }
  );

  await new Promise(resolve => setTimeout(resolve, 10000));

  driver.deleteSession();
```

Appium version: 2.0.0-beta.46
Flutter driver version: flutter@1.10.0

**Comment by KazuCocoa** [comment]
What about using `flutter_driver` directly instead of via Appium?
https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/scrollUntilVisible.html

Appium Flutter driver calls the method, but how it works depends on Flutter/Dart VM, it is out of Appium Flutter driver. You could ensure that it works via flutter_driver directly.

**Comment by MatteoAntolini** [comment]
Yes, with flutter_driver it works as expected, but I need Appium for testing a webview of the app.

**Comment by KazuCocoa** [comment]
sorry, i was wrong. it continued scrolling til https://github.com/appium-userland/appium-flutter-driver/blob/868cab2a460dc63445172826cd2bb72f56cd1501/driver/lib/commands/execute/scroll.ts#L72

What about using `scrollUntilTapable`?

**Comment by MatteoAntolini** [comment]
The first time the app crashed
```
{"command":"scroll","finderType":"ByValueKey","keyValueString":"locals","keyValueType":"String","dx":-250,"dy":0,"duration":100000,"frequency":60}
[FlutterDriver] Connection to ws://127.0.0.1:33433/gJHvO9IaUkU=/ws closed
```

The second and third time it behave as `flutter:scrollUntilVisible` so it retried 3 times to find the element and then it threw an error (as expected)

This exception is correct, it would be useful to set the timeout and not wait for 120000ms * 3
```
Request failed with status undefined due to TimeoutError: Timeout awaiting 'request' for 120000ms when running "execute/sync" with method "POST" and args "flutter:scrollUntilTapable"
```

The problem is that after this, appium goes on a timeout loop on the next commands

Client-side:
```
Request timed out! Consider increasing the "connectionRetryTimeout" option.
```

Server-side:
 ```
{"command":"scroll","finderType":"ByValueKey","keyValueString":"locals","keyValueType":"String","dx":-250,"dy":0,"duration":100000,"frequency":60}
[debug] [FlutterDriver] <<< {"isError":false,"response":{},"type":"_extensionType","method":"ext.flutter.driver"} | previous command scroll
```
After 3 retries the client closes the connection, but the server keeps on logging the line above

`scrollUntilTapable` is wrapped inside a try-catch to handle when appium scrolls to the last item. 


I tested it on another app, but the error is the same of the given example

**Comment by MatteoAntolini** [comment]
I solved the problem with this function.

```typescript
export const scrollUntilVisible = async (
  self: FlutterDriver,
  elementBase64: string,
  opts: {
    item: string;
    alignment: number;
    dxScroll: number;
    dyScroll: number;
    frequency?: number;
    timeout?: number;
  },
) => {
  const { item, alignment = 0.0, dxScroll = 0, dyScroll = 0, timeout = 1000, frequency = 60 } = opts;

  if (
    typeof alignment !== `number` ||
    typeof dxScroll !== `number` ||
    typeof dyScroll !== `number`
  ) {
    // @todo BaseDriver's errors.InvalidArgumentError();
    throw new Error(`${opts} is not a valid options`);
  }

  if (dxScroll === 0 && dyScroll === 0) {
    // @todo BaseDriver's errors.InvalidArgumentError();
    throw new Error(`${opts} is not a valid options`);
  }

  // Call waitFor function before the loop
  let isVisible = false;
  try {
    await waitFor(self, item, timeout);
    isVisible = true;
  } catch (error) {
    // log.error(`Item ${item} is not visible`);
  }

  // Use a countdown timer for the loop control mechanism
  let countdown = frequency;
  while (!isVisible && countdown > 0) {
    await scroll(self, elementBase64, {
      dx: dxScroll,
      dy: dyScroll,
      durationMilliseconds: 100,
    });
    try {
      await waitFor(self, item, timeout);
      isVisible = true;
    } catch (error) {
      // log.error(`Item ${item} is not visible`);
    }
    countdown--;
  }

  // Return the result of the scrollIntoView function
  if (isVisible) {
    return scrollIntoView(self, item, { alignment, timeout });
  } else {
    throw new Error(`Item ${item} was not made visible within the specified timeout`);
  }
};
```

**Comment by arctouch-thiagowerner** [comment]
@KazuCocoa do you feel it is easy to implement a timeout for this function? I am trying to implement something outside the driver, but the scroll command keep firing forever. If there is any other way to set this timeout, could you please give us an example?

**Comment by KazuCocoa** [comment]
what about https://github.com/appium-userland/appium-flutter-driver/pull/408 ?

**Comment by arctouch-thiagowerner** [comment]
Looks suitable! I made a workaround in my code to check if the element exists before calling scrollUntilVisible. Otherwise the driver was flooding Appium with repeatedly scrolling calls.

**Comment by KazuCocoa** [comment]
I haven't tested as no good example I have. It is appreciated to try the pr.
https://github.com/appium-userland/appium-flutter-driver/issues/372#issuecomment-1356792600 is also maybe good(?)

**Comment by arctouch-thiagowerner** [comment]
From the top of my head, I don't really know how I can use the driver from a specific branch... maybe I can edit the code inside my local lib?

**Comment by KazuCocoa** [comment]
The easiest is: 1) git clone the branch https://github.com/appium-userland/appium-flutter-driver/pull/408
2) Then build it
```
cd appium-flutter-driver/driver
npm run install
```
3) Then, copy `build` directly into `~/.appium/node_modules/appium-flutter-driver/build`

You can keep the old `build` somewhere.

**Comment by arctouch-thiagowerner** [comment]
Let me test it now, I didn't have time enough to do this in the past few days.

**Comment by MatteoAntolini** [comment]
@arctouch-thiagowerner Did you try my version? You can replace the function `scrollUntilVisible` with mine and run the test.
When the driver will not find the item, you will see three error messages as this `Item ${item} was not made visible within the specified timeout`. 
Remeber that you need to have a try catch when you do  `driver.execute("flutter:scrollUntilVisible"...)` as this example https://github.com/appium-userland/appium-flutter-driver/issues/372#issue-1464551183

**Comment by arctouch-thiagowerner** [comment]
@MatteoAntolini I tried your solution, but for any reason it did not work here.

@KazuCocoa I am not sure if the problem of closing the session after throwing the error is something related to development environment.

**Comment by MatteoAntolini** [comment]
@arctouch-thiagowerner What you mean? It doesn't compile, It gives you an error or it crash?

**Comment by arctouch-thiagowerner** [comment]
I added a try/catch as you mentioned, and used the script using the timeout argument. But the code is still flooding the script in the command line.

**Comment by KazuCocoa** [comment]
Modified https://github.com/appium-userland/appium-flutter-driver/pull/408 to handle loop. (I misunderstood some this driver's behavior)

**Comment by arctouch-thiagowerner** [comment]
Let me test it again.

**Comment by arctouch-thiagowerner** [comment]
@KazuCocoa worked as expected. We're good to go.

**Comment by KazuCocoa** [comment]
Thank you. The CI is not happy right now, so once I've fix it, I'll push a new version

**Comment by KazuCocoa** [comment]
1.13.0 has the change. The timeout name changed as `waitTimeoutMilliseconds` (changed the naming a bit)
https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/lib/commands/execute/scroll.ts
