### ISSUE TITLE
Unable to reconnect to server after the NewCommandTimeOut is executed and the session is ending

### ISSUE THREAD

**Issue by MayadaAbdelsalam** [appium-userland/appium-flutter-driver#377]
**Issue:**
unable to create new remote session after NewCommandTimeOut is executed (Running suite of sequential scenarios )once there is  timeout happens the driver closed and unable to run the next  scenario 

**Environment :**

java : 17.0.2
Appium: appium V2 
appium flutter driver  :V1.11
platform : Android
Framework : java +TestNG+ Cucumber

**Capabilities:**

    flutterCapabilities.setCapability("automationName", "Flutter");
    flutterCapabilities.setCapability("newCommandTimeout", "120");
    
**HooksHandler:**
@before
activateAPP

@After
TerminateApp

@MayadaAbdelsalam
Logs:
[AndroidUiautomator2Driver@c4b7 (75fb0147)] Shutting down because we waited 120 seconds for a command
[debug] [AndroidUiautomator2Driver@c4b7 (75fb0147)] Deleting UiAutomator2 session
[debug] [AndroidUiautomator2Driver@c4b7 (75fb0147)] Deleting UiAutomator2 server session
[debug] [AndroidUiautomator2Driver@c4b7 (75fb0147)] Matched '/' to command name 'deleteSession'
[debug] [AndroidUiautomator2Driver@c4b7 (75fb0147)] Proxying [DELETE /] to [DELETE http://127.0.0.1:8202/session/a2a69198-1637-4b79-8572-e026b7edec2f] with no body
[debug] [AndroidUiautomator2Driver@c4b7 (75fb0147)] Got response with status 200: {"sessionId":"a2a69198-1637-4b79-8572-e026b7edec2f","value":null}
[debug] [ADB] Running '/Users/mayadaabdelsalam/Library/Android/sdk/platform-tools/adb -P 5037 -s 2ASVB21B05018897 shell dumpsys activity services io.appium.settings/.recorder.RecorderService'
[debug] [ADB] Running '/Users/mayadaabdelsalam/Library/Android/sdk/platform-tools/adb -P 5037 -s 2ASVB21B05018897 shell am force-stop com.rabbit.mart.staging'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8202 
[debug] [ADB] Running '/Users/mayadaabdelsalam/Library/Android/sdk/platform-tools/adb -P 5037 -s 2ASVB21B05018897 forward --remove tcp:8202'
[AndroidUiautomator2Driver@c4b7 (75fb0147)] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/mayadaabdelsalam/Library/Android/sdk/platform-tools/adb -P 5037 -s 2ASVB21B05018897 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[FlutterDriver] Connection to ws://127.0.0.1:41913/uNacTeebO68=/ws closed
[debug] [Instrumentation] .
[debug] [Instrumentation] Time: 129.063
[debug] [Instrumentation] 
[debug] [Instrumentation] OK (1 test)
[debug] [Instrumentation] The process has exited with code 0
[HTTP] <-- POST /session/760e1a01-4c64-4a8d-809d-f7d823b267ea/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoicHJvZHVjdFRpbGVfMCJ9/click - - ms - -
[HTTP]

**Comment by KazuCocoa** [comment]
Oh, does this mean the newCommandTimeout in UIA2/XCUITest worked unexpectedly while the  Flutter context got requests in the timeout time?

Actually, the NATIVE_APP part (UIA2/XCUITest drivers) does not get any command, so I guess this newCommandTimeuot stuff happens in these drivers instead of this Flutter context itself. This could be this issue

**Comment by MayadaAbdelsalam** [comment]
Actually, the newCommandTimeout in UIA2/XCUITest worked expectedly as in this running case (server was asking for keyvalue(ID) that really doesn't exist ,as this happens alot while running our suites so we where trying to handle all failure cases ) .
My Question is there workaround to handle this case while running group of scenarios sequentially ( as once this case happens everything is shut down )?
like: reload session/connection for the next scenario

**Comment by KazuCocoa** [comment]
New session creation and activateApp in the Flutter context can establish the observatory URL connection. So after terminating the session by timeout, you need to re-create a new session, or activateApp in the flutter context

**Comment by KazuCocoa** [comment]
I have added `activateApp` in 1.11.0, which can attach to the new launched websocket. It will help this case
https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/CHANGELOG.md#1110
