### ISSUE TITLE
Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by saravanakumarQA** [appium-userland/appium-flutter-driver#382]
Try to automate flutter  app with appium flutter driver ,when run the test ,  App is launched but  session is terminated immediately  stating below exception.
"Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'match')"

 Environment 
Appium v1.22.3
node v18.12.1 

Details 

const opts = {
  path: '/wd/hub/',
  port: 4723,
  capabilities: {
    
    'appium:platformName': 'Android',
    'appium:platformVersion': '10',
    'appium:deviceName": "Galaxy M20',
   ' appium :udid': '340XXXXXXXXX', 
    "appium:appPackage": "com.example.test_app",
    "appium:appActivity": "com.example.test_app.MainActivity",
    'appium:automationName': 'Flutter',
    'appium:retryBackoffTime': 500
  }
![Screenshot (17)](https://user-images.githubusercontent.com/121163364/208890159-45851a76-b7e6-4467-b717-95564032f64a.png)
![Screenshot (18)](https://user-images.githubusercontent.com/121163364/208892036-628d6b56-a54a-49c5-b12a-1a64d8e9f74f.png)

**Comment by KazuCocoa** [comment]
Please use the latest version, especially if you used flutter v3+
https://github.com/appium-userland/appium-flutter-driver#installation
