### ISSUE TITLE
Request failed with status 404 due to The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource 

### ISSUE THREAD

**Issue by saravanakumarQA** [appium-userland/appium-flutter-driver#390]
hello , i am  trying  to automate a flutter app using the  appium flutter driver on a mac machine  , but when i run the code i received the below error message 
"Request failed with status 404 due to The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource
2023-01-05T02:53:07.699Z INFO webdriver: Retrying 1/3"

Environment
Appium v2.0.0-beta.48
node v18.12.1
xcode 14

Details 
const opts = {
  port: 4723,
  capabilities: {
    'platformName': 'iOS',
  'appium:platformVersion': '15.4.1',
  'appium:deviceName': 'iPhone 6s Plus',
  'appium:noReset': true,
    'appium:automationName': 'Flutter',
    'appium:bundleId':'com.example.hello_world.MainActivity',
    'appium:retryBackoffTime': 500
  }
};
![Screen Shot 2023-01-05 at 8 39 48 am](https://user-images.githubusercontent.com/121163364/210695622-a478c25c-319f-4a4c-9c93-ac0307d8e7c1.png)

![Screen Shot 2023-01-05 at 9 06 19 am](https://user-images.githubusercontent.com/121163364/210696292-ecc1f529-2518-4d3d-a745-1b9e0b807d49.png)

**Comment by KazuCocoa** [comment]
What is the full appium server log? I wonder if you specified `/wd/hub` to start an appium server

**Comment by saravanakumarQA** [comment]
> What is the full appium server log? I wonder if you specified `/wd/hub` to start an appium server

I got the same error in the windows environment for android, so I used to start the appium server like this: "appium --base-path /wd/hub " 
![Screen Shot 2023-01-06 at 11 03 54 am](https://user-images.githubusercontent.com/121163364/210942743-3164431b-5262-4e15-894e-2f9bd1f28ace.png)

when the Appium server started normally 




![Screen Shot 2023-01-06 at 1 27 23 pm](https://user-images.githubusercontent.com/121163364/210966671-3cc45155-9de5-44ca-bc35-0f5ef729ccae.png)


when the Appium server started in  "appium --base-path /wd/hub"



![Screen Shot 2023-01-06 at 12 32 44 pm](https://user-images.githubusercontent.com/121163364/210967144-3065123b-8d46-486d-aba1-6f54b5519f20.png)
