### ISSUE TITLE
Connecting to Dart Observatory fails

### ISSUE THREAD

**Issue by pprettytony** [appium-userland/appium-flutter-driver#402]
```
Java: 11
OS: MacOS 13
Appium: 2.0.0-beta.52
Device: Android emulator 12.0
Appium Flutter driver: 1.9.1
```
I tried you setup an automation framework for a Flutter-based app. I tried to follow the description from Appium-flutter-driver repo but all my tries were unsuccessful. 

The simplest way for me right now is to run flutter command to setup debug build on my active device, get the Observatory debugger URL from response and paste it in my code for `appium:observatoryWsUri` capability, then I run my code with tests. I got this code to setup driver:
```
        AndroidDriver<MobileElement> driver;
        DesiredCapabilities desiredCaps = new DesiredCapabilities();
        desiredCaps.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "com.ex.pack");
        desiredCaps.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
        desiredCaps.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, ".MainActivity");
        desiredCaps.setCapability(MobileCapabilityType.AUTOMATION_NAME, "Flutter");
        desiredCaps.setCapability(MobileCapabilityType.NO_RESET, true);
        desiredCaps.setCapability("appium:observatoryWsUri", "http://127.0.0.1:50014/Rn9a21nUzUM=/ws");
        desiredCaps.setCapability("autoLaunch", false);

        try {
            driver = new AndroidDriver<>(new URL("http://localhost:4723"), desiredCaps);
            driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
            return driver;
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
```
As a result I got response from Appium:
`[debug] [AppiumDriver@f85f] Calling AppiumDriver.createSession() with args: [{"appActivity":"com.ex.pack.MainActivity","appPackage":"com.ex.pack","appium:observatoryWsUri":"http://127.0.0.1:50014/Rn9a21nUzUM=/ws","noReset":true,"autoLaunch":false,"automationName":"Flutter","platformName":"Android"},null,{"firstMatch":[{"appium:appActivity":"com.ex.pack.MainActivity","appium:appPackage":"com.ex.pack","appium:observatoryWsUri":"http://127.0.0.1:50014/Rn9a21nUzUM=/ws","appium:autoLaunch":false,"appium:automationName":"Flutter","appium:noReset":true,"platformName":"android"}]}]
[debug] [AppiumDriver@f85f] Event 'newSessionRequested' logged at 1674205431961 (11:03:51 GMT+0200 (Eastern European Standard Time))
[Appium] Attempting to find matching driver for automationName 'Flutter' and platformName 'android'
[Appium] The 'flutter' driver was installed and matched caps.
[Appium] Will require it at /Users/user/.appium/node_modules/appium-flutter-driver
[debug] [Appium] Requiring driver at /Users/user/.appium/node_modules/appium-flutter-driver
[AppiumDriver@f85f] Appium v2.0.0-beta.52 creating new FlutterDriver (v1.9.1) session
[AppiumDriver@f85f] Checking BaseDriver versions for Appium and FlutterDriver
[AppiumDriver@f85f] Appium's BaseDriver version is 9.2.3
[AppiumDriver@f85f] FlutterDriver's BaseDriver version is 9.2.3
[debug] [FlutterDriver@f80b] Creating session with W3C capabilities: {
[debug] [FlutterDriver@f80b]   "alwaysMatch": {
[debug] [FlutterDriver@f80b]     "platformName": "android",
[debug] [FlutterDriver@f80b]     "appium:appActivity": "com.ex.pack.MainActivity",
[debug] [FlutterDriver@f80b]     "appium:appPackage": "com.ex.pack",
[debug] [FlutterDriver@f80b]     "appium:observatoryWsUri": "http://127.0.0.1:50014/Rn9a21nUzUM=/ws",
[debug] [FlutterDriver@f80b]     "appium:autoLaunch": false,
[debug] [FlutterDriver@f80b]     "appium:automationName": "Flutter",
[debug] [FlutterDriver@f80b]     "appium:noReset": true
[debug] [FlutterDriver@f80b]   },
[debug] [FlutterDriver@f80b]   "firstMatch": [
[debug] [FlutterDriver@f80b]     {}
[debug] [FlutterDriver@f80b]   ]
[debug] [FlutterDriver@f80b] }
[FlutterDriver@f80b] The following capabilities were provided, but are not recognized by Appium:
[FlutterDriver@f80b]   appActivity
[FlutterDriver@f80b]   appPackage
[FlutterDriver@f80b]   observatoryWsUri
[FlutterDriver@f80b (4c3e3988)] Session created with session id: 4c3e3988-bbc6-40d4-ac6e-226b6fda6e26
[FlutterDriver] Starting an Android proxy session
[debug] [AndroidUiautomator2Driver@c651] Creating session with W3C capabilities: {
[debug] [AndroidUiautomator2Driver@c651]   "alwaysMatch": {
[debug] [AndroidUiautomator2Driver@c651]     "platformName": "android",
[debug] [AndroidUiautomator2Driver@c651]     "appium:appActivity": "com.ex.pack.MainActivity",
[debug] [AndroidUiautomator2Driver@c651]     "appium:appPackage": "com.ex.pack",
[debug] [AndroidUiautomator2Driver@c651]     "appium:observatoryWsUri": "http://127.0.0.1:50014/Rn9a21nUzUM=/ws",
[debug] [AndroidUiautomator2Driver@c651]     "appium:autoLaunch": false,
[debug] [AndroidUiautomator2Driver@c651]     "appium:automationName": "Flutter",
[debug] [AndroidUiautomator2Driver@c651]     "appium:noReset": true
[debug] [AndroidUiautomator2Driver@c651]   },
[debug] [AndroidUiautomator2Driver@c651]   "firstMatch": [
[debug] [AndroidUiautomator2Driver@c651]     {}
[debug] [AndroidUiautomator2Driver@c651]   ]
[debug] [AndroidUiautomator2Driver@c651] }
[AndroidUiautomator2Driver@c651] The following capabilities were provided, but are not recognized by Appium:
[AndroidUiautomator2Driver@c651]   observatoryWsUri
[AndroidUiautomator2Driver@c651 (7f5d1c95)] Session created with session id: 7f5d1c95-c6ab-47e5-9537-ecfe50db38de
[AndroidUiautomator2Driver@c651 (7f5d1c95)] Starting 'com.ex.pack' directly on the device
[ADB] Found 2 'build-tools' folders under '/Users/user/Library/Android/sdk' (newest first):
[ADB]     /Users/user/Library/Android/sdk/build-tools/33.0.0
[ADB]     /Users/user/Library/Android/sdk/build-tools/30.0.3
[ADB] Using 'adb' from '/Users/user/Library/Android/sdk/platform-tools/adb'
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 start-server'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices
[debug] [ADB] Connected devices: [{"udid":"emulator-5554","state":"device"}]
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb' from '/Users/user/Library/Android/sdk/platform-tools/adb'
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 start-server'
[debug] [ADB] Setting device id to emulator-5554
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 31
[ADB] Getting device platform version
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 12
[debug] [ADB] Device API level: 31
[AndroidUiautomator2Driver@c651 (7f5d1c95)] Relaxing hidden api policy
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'settings put global hidden_api_policy_pre_p_apps 1;settings put global hidden_api_policy_p_apps 1;settings put global hidden_api_policy 1''
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 wait-for-device'
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[debug] [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('4.2.2' >= '4.2.2')
[debug] [ADB] There is no need to install/upgrade '/Users/user/.appium/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'pgrep --help; echo $?''
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f \(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)'
[debug] [AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[debug] [Logcat] Starting logs capture with command: /Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 logcat -v threadtime
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Forwarding UiAutomator2 Server port 6790 to local port 8201
[debug] [ADB] Forwarding system: 8201 to device: 6790
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp:8201 tcp:6790'
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] 'io.appium.uiautomator2.server' is installed
[debug] [ADB] Getting package info for 'io.appium.uiautomator2.server'
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('5.7.2' >= '5.7.2')
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] io.appium.uiautomator2.server installation state: sameVersionInstalled
[debug] [ADB] Checking app cert for /Users/user/.appium/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v5.7.2.apk
[ADB] Using 'apksigner.jar' from '/Users/user/Library/Android/sdk/build-tools/33.0.0/lib/apksigner.jar'
[debug] [ADB] Starting apksigner: /usr/bin/java -Xmx1024M -Xss1m -jar /Users/user/Library/Android/sdk/build-tools/33.0.0/lib/apksigner.jar verify --print-certs /Users/user/.appium/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v5.7.2.apk
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [ADB] 
[debug] [ADB] sha256 hash did match for 'appium-uiautomator2-server-v5.7.2.apk'
[ADB] '/Users/user/.appium/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v5.7.2.apk' is signed with the default certificate
[debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server.test'
[debug] [ADB] 'io.appium.uiautomator2.server.test' is installed
[debug] [ADB] Checking app cert for /Users/user/.appium/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk
[debug] [ADB] Starting apksigner: /usr/bin/java -Xmx1024M -Xss1m -jar /Users/user/Library/Android/sdk/build-tools/33.0.0/lib/apksigner.jar verify --print-certs /Users/user/.appium/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [ADB] 
[debug] [ADB] sha256 hash did match for 'appium-uiautomator2-server-debug-androidTest.apk'
[ADB] '/Users/user/.appium/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is signed with the default certificate
[AndroidUiautomator2Driver@c651 (7f5d1c95)] Server packages are not going to be (re)installed
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Waiting up to 30000ms for services to be available
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm list instrumentation'
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Instrumentation target 'io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner' is available
[ADB] Adding packages ["io.appium.settings","io.appium.uiautomator2.server","io.appium.uiautomator2.server.test"] to Doze whitelist
[debug] [ADB] Got the following command chunks to execute: [["dumpsys","deviceidle","whitelist","+io.appium.settings",";","dumpsys","deviceidle","whitelist","+io.appium.uiautomator2.server",";","dumpsys","deviceidle","whitelist","+io.appium.uiautomator2.server.test",";"]]
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys deviceidle whitelist +io.appium.settings ; dumpsys deviceidle whitelist +io.appium.uiautomator2.server ; dumpsys deviceidle whitelist +io.appium.uiautomator2.server.test ;'
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] No app capability. Assuming it is already on the device
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Performing shallow cleanup of automation leftovers
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] The following obsolete sessions are still running: ["77bac888-e98f-4ac3-8f02-c59e36e3bf4c"]
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Cleaning up 1 obsolete session
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.uiautomator2.server.test'
[AndroidUiautomator2Driver@c651 (7f5d1c95)] Starting UIAutomator2 server 5.7.2
[AndroidUiautomator2Driver@c651 (7f5d1c95)] Using UIAutomator2 server from '/Users/user/.appium/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v5.7.2.apk' and test from '/Users/user/.appium/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk'
[AndroidUiautomator2Driver@c651 (7f5d1c95)] Waiting up to 30000ms for UiAutomator2 to be online...
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","am","instrument","-w","-e","disableAnalytics",true,"io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Matched '/status' to command name 'getStatus'
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Proxying [GET /status] to [GET http://127.0.0.1:8201/status] with no body
[AndroidUiautomator2Driver@c651 (7f5d1c95)] socket hang up
[debug] [Instrumentation] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Matched '/status' to command name 'getStatus'
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Proxying [GET /status] to [GET http://127.0.0.1:8201/status] with no body
[AndroidUiautomator2Driver@c651 (7f5d1c95)] socket hang up
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Matched '/status' to command name 'getStatus'
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Proxying [GET /status] to [GET http://127.0.0.1:8201/status] with no body
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Got response with status 200: {"sessionId":"None","value":{"message":"UiAutomator2 Server is ready to accept commands","ready":true}}
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] The initialization of the instrumentation process took 2078ms
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Matched '/session' to command name 'createSession'
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Proxying [POST /session] to [POST http://127.0.0.1:8201/session] with body: {"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"android","appActivity":"com.ex.pack.MainActivity","appPackage":"com.ex.pack","observatoryWsUri":"http://127.0.0.1:50014/Rn9a21nUzUM=/ws","autoLaunch":false,"automationName":"Flutter","noReset":true},"platformName":"android","appActivity":"com.ex.pack.MainActivity","appPackage":"com.ex.pack","observatoryWsUri":"http://127.0.0.1:50014/Rn9a21nUzUM=/ws","autoLaunch":false,"automationName":"Flutter","noReset":true,"deviceName":"emulator-5554","deviceUDID":"emulator-5554"}],"alwaysMatch":{}}}
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Got response with status 200: {"sessionId":"de0a915e-1f80-4174-a0b3-15b6e1b30ee7","value":{"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"android","appActivity":"com.ex.pack.MainActivity","appPackage":"com.ex.pack","observatoryWsUri":"http://127.0.0.1:50014/Rn9a21nUzUM=/ws","autoLaunch":false,"automationName":"Flutter","noReset":true},"platformName":"android","appActivity":"com.ex.pack.MainActivity","appPackage":"com.ex.pack","observatoryWsUri":"http://127.0.0.1:50014/Rn9a21nUzUM=/ws","autoLaunch":false,"automationName":"Flutter","noReset":true,"deviceName":"emulator-5554","deviceUDID":"emulator-5554"}],"alwaysMatch":{}},"sessionId":"de0a915e-1f80-4174-a0b3-15b6e1b30ee7"}}
[AndroidUiautomator2Driver@c651 (7f5d1c95)] Determined the downstream protocol as 'W3C'
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Proxying [GET /appium/device/info] to [GET http://127.0.0.1:8201/session/de0a915e-1f80-4174-a0b3-15b6e1b30ee7/appium/device/info] with no body
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Got response with status 200: {"sessionId":"de0a915e-1f80-4174-a0b3-15b6e1b30ee7","value":{"androidId":"2f85c404d2639e27","apiVersion":"31","bluetooth":{"state":"ON"},"brand":"google","carrierName":"T-Mobile","displayDensity":320,"locale":"en_US","manufacturer":"Google","model":"sdk_gphone64_arm64","networks":[{"capabilities":{"SSID":null,"linkDownBandwidthKbps":30000,"linkUpstreamBandwidthKbps":12000,"networkCapabilities":"NET_CAPABILITY_NOT_METERED,NET_CAPABILITY_INTERNET,NET_CAPABILITY_NOT_RESTRICTED,NET_CAPABILITY_TRUSTED,NET_CAPABILITY_NOT_VPN,NET_CAPABILITY_VALIDATED,NET_CAPABILITY_NOT_ROAMING,NET_CAPABILITY_FOREGROUND,NET_CAPABILITY_NOT_CONGESTED,NET_CAPABILITY_NOT_SUSPENDED","signalStrength":-50,"transportTypes":"TRANSPORT_WIFI"},"detailedState":"CONNECTED","extraInfo":"","isAvailable":true,"isConnected":true,"isFailover":false,"isRoaming":false,"state":"CONNECTED","subtype":-1,"subtypeName":"","type":1,"typeName":"WIFI"},{"capabilities":{"SSID":null,"linkDownBandwidthKbps":4300,"linkUpstreamBandwidthKbps":1800,"networkCapabili...
[debug] [ADB] Running '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window'
[AndroidDriver] Screen already unlocked, doing nothing
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Proxying [GET /appium/device/pixel_ratio] to [GET http://127.0.0.1:8201/session/de0a915e-1f80-4174-a0b3-15b6e1b30ee7/appium/device/pixel_ratio] with no body
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Got response with status 200: {"sessionId":"de0a915e-1f80-4174-a0b3-15b6e1b30ee7","value":2}
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Matched '/appium/device/system_bars' to command name 'getSystemBars'
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Proxying [GET /appium/device/system_bars] to [GET http://127.0.0.1:8201/session/de0a915e-1f80-4174-a0b3-15b6e1b30ee7/appium/device/system_bars] with no body
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Got response with status 200: {"sessionId":"de0a915e-1f80-4174-a0b3-15b6e1b30ee7","value":{"statusBar":48}}
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Matched '/window/current/size' to command name 'getWindowSize'
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Proxying [GET /window/current/size] to [GET http://127.0.0.1:8201/session/de0a915e-1f80-4174-a0b3-15b6e1b30ee7/window/current/size] with no body
[debug] [AndroidUiautomator2Driver@c651 (7f5d1c95)] Got response with status 200: {"sessionId":"de0a915e-1f80-4174-a0b3-15b6e1b30ee7","value":{"height":1504,"width":2560}}
[FlutterDriver] Attempt #1
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:50014/Rn9a21nUzUM=/ws
[FlutterDriver] Connecting to ws://127.0.0.1:50014/Rn9a21nUzUM=/ws
[FlutterDriver] {"code":-32600,"message":"Request params must be an Array or an Object, but was null.","data":{"request":{"jsonrpc":"2.0","method":"getVM","params":null,"id":1}}}
uncaughtException: {"code":-32600,"message":"Request params must be an Array or an Object, but was null.","data":{"request":{"jsonrpc":"2.0","method":"getVM","params":null,"id":1}}}
Error: {"code":-32600,"message":"Request params must be an Array or an Object, but was null.","data":{"request":{"jsonrpc":"2.0","method":"getVM","params":null,"id":1}}}
    at Object.wrappedLogger.errorAndThrow (/Users/user/.appium/node_modules/appium-flutter-driver/node_modules/@appium/support/lib/logging.js:115:34)
    at IsolateSocket.socket.call (/Users/user/.appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:75:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at IsolateSocket.onOpenListener (/Users/user/.appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:79:20)`
The FlutterDriver error points me to a few links with answers how to resolve this issue suggesting to restart the machine. This suggestion doesn't work in my case, I still have this issue even after restart. Flutter command works correctly, I can connect to the flutter debugging server and the app is still running on the device.

I also tried some alternative scenarios like run flutter command from Java internally, get the observatory url from response and paste this url to capabilities by code but suddenly somehow flutter command lose connection to the device and the observatory url becomes invalid (the app disconnects in this case).

**Question:** what this error related to and how can I fix it? 
And more question, maybe it's related to this exact issue. I also noticed that there are some notes about port forwarding. Could someone explain what exact ports I need to forward?

UPD
Also noticed that if I don't set `appium:observatoryWsUri` in capabilities - appium tries to connect to unknown but seems to be valid url (matches the pattern `ws://127.0.0.1:60992/aaaaaaaaaaa=/ws`). I don't know where it takes from.

**Comment by KazuCocoa** [comment]
This driver tries to find a url matched with https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/lib/sessions/observatory.ts#L188 by reading the device log, logcat for Android and systemlog for iOS. Usually the observaotry url should be in the logs when it launches. The URL could change every flutter app launching process.

The url does not in the log when the flutter app is alive like background to foreground, so you may need to ensure the application process is stopped before the start.

`observatoryWsUri` is an advanced way to manage flutter applications outside Appium, and attach to the application in the middle via this driver. So I'd recommend you to not add the capabilities first.

**Comment by pprettytony** [comment]
@KazuCocoa Thanks for your answer. 
Everything is clear now, flutter driver starts as expected. This problem was related to build's configuration.
After build had been fixed, I ran it in my project and appium received a correct observatory url.
