### ISSUE TITLE
How to change driver context using java_client 8+ from "FLUTTER" to "NATIVE_APP"? 

### ISSUE THREAD

**Issue by hananmalka** [appium-userland/appium-flutter-driver#409]
appium version: 2.0.0-52-beta
appium-flutter-driver: 1.12
appium java_client: 8.3.0

`driver.context("CONTEXT_NAME")` is not available in java_client 8+.

How can I change the context (trying to locate element in camera app which is system app)?

**Comment by KazuCocoa** [comment]
What driver did you use? You may need to set `AndroidDriver`/`iOSDriver` with `flutter` automation name with uia2 options and xcuitest options.

**Comment by denysord88** [comment]
I'm using this:
// IOSDriver driver = new IOSDriver(service.getUrl(), capabilities);
...
driver.context("NATIVE_APP");
driver.context("FLUTTER");

Working fine.

**Comment by hananmalka** [comment]
@KazuCocoa - I'm using AppiumDriver with FLUTTER automation name but without uia2 options and xcuitest options.
Can I use this way?

**Comment by KazuCocoa** [comment]
It depends on how much the base AppiumDriver itself supports what kind of methods. The context stuff is Android/iOS related so basically other appium drivers do not need it. Thus I guess Java client implements the availability only in Android/iOS driver classes. Then, no
