### ISSUE TITLE
In new appium flutter driver scroll isn't working in java code

### ISSUE THREAD

**Issue by bikashmoneynmore** [appium-userland/appium-flutter-driver#422]
Appium flutter driver version : flutter@1.13.0 
Appium version : 2.0.0-beta.55
Language : java 
This code isnt working 
      getDriver().executeScript("flutter:scrollUntillVisible", locateElement(fromPageElement), new HashMap<String, Object>() {{
        put("item", locateElement(toPageElement));
        put("dxScroll", 90);
        put("dyScroll", -400);
        put("durationMilliseconds", 20000);
      }});
Getting error as 👍 

[debug] [FlutterDriver@b1cd (b2c8723a)] Encountered internal error running command: Error: Stop scrolling as timeout undefined
[debug] [FlutterDriver@b1cd (b2c8723a)]     at scrollUntilVisible (/Users/Narayan/node_modules/appium-flutter-driver/lib/commands/execute/scroll.ts:144:11)

**Comment by KazuCocoa** [comment]
The error message can be improved, but the error itself is expected. 
https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/lib/commands/execute/scroll.ts#L123-L143 after the scroll, still the element could be unvisible

**Comment by KazuCocoa** [comment]
oh, maybe it has one missed condition check

**Comment by bikashmoneynmore** [comment]
Then what attribute i have to add in hash map..?

**Comment by bikashmoneynmore** [comment]
@KazuCocoa After adding this "        put("waitTimeoutMilliseconds", 20000);
" it works thanks @KazuCocoa . Thank you soo much. The full java code
      getDriver().executeScript("flutter:scrollUntilVisible", locateElement(fromPageElement), new HashMap<String, Object>() {{
        put("item", locateElement(toPageElement));
        put("dxScroll", 90);
        put("dyScroll", -400);
        put("waitTimeoutMilliseconds", 20000);
      }});
