### ISSUE TITLE
Question: Is possible test a Native App that has Flutter module integrated?

### ISSUE THREAD

**Issue by idd-tmaciel** [appium-userland/appium-flutter-driver#427]
I need professional help, I have a scenario that is: a native application that has some modules (screens) in a flutter.
When the application starts the context is NATIVE_APP and after some native screens, I arrive at a flutter screen. The driver context list has only the 'NATIVE_APP'. In this scenario, I'm using the applicationName as 'UiAutomato2'. So I did a workaround, I made my application starts with a flutter session behind the curtains, so I started with the applicationName as 'Flutter' and I got 2 contexts in the list, FLUTTER, and NATIVE_APP. But when I'm in the flutter screen and I do a click action, the command doesn't throw any error, looks like the command click keeps trying without success.

Capabilities:

```
`DesiredCapabilities().apply {
                    setCapability(MobileCapabilityType.DEVICE_NAME, utils.getDeviceName())
                    setCapability(MobileCapabilityType.PLATFORM_NAME, platform)
                    setCapability(MobileCapabilityType.AUTOMATION_NAME, "flutter")
                    setCapability(MobileCapabilityType.APP, "$path$libPath/app-debug.apk")
                    setCapability("autoGrantPermissions", true)
                    setCapability("newCommandTimeout", 280)
                }.also {
                    driver = AndroidDriver(url, it)
                }`
```
Main question: Is possible to start the native application with capability set to: "UiAutomator2" and get the "FLUTTER" context when arrives at the flutter screen? If not, there is a solution to this scenario?

**Comment by KazuCocoa** [comment]
Could you share the full appium log when the issue occurs?

In Flutter case, appium-flutter-driver sends flutter_driver commands by Flutter team to the DartVM. How the command work depends on the Dart VM/Flutter side. Thus, as this driver, the answer is yes, but the behavior depends on the Flutter internal.

In the log, we can check if an expected flutter commands reached the Dart VM, and probably can see the response (or no response). Once we confirm the fact, the behavior depends on Flutter. If the possible cause is inside flutter, this driver cannot help.

**Comment by idd-tmaciel** [comment]
@KazuCocoa thank you for answering, follow the full appium log.

`mar. 13, 2023 11:15:58 AM br.com.pagseguro.mobile.commons.core.AppiumServer startAppiumServer
INFO: Starting appium local server
mar. 13, 2023 11:16:01 AM br.com.pagseguro.mobile.commons.core.AppiumServer startAppiumServer
INFO: Appium local server is running
mar. 13, 2023 11:16:01 AM br.com.pagseguro.mobile.commons.core.Utils startDeviceLocal
INFO: Starting device local - Pixel_3_API_29
[Appium] Welcome to Appium v2.0.0-beta.56
[Appium] Non-default server args:
[Appium] { loglevel: 'info:error' }
[Appium] Attempting to load driver uiautomator2...
[Appium] Attempting to load driver xcuitest...
[Appium] Attempting to load driver flutter...
(node:59844) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - uiautomator2@2.12.6 (automationName 'UiAutomator2')
[Appium]   - xcuitest@4.18.4 (automationName 'XCUITest')
[Appium]   - flutter@1.13.0 (automationName 'Flutter')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
mar. 13, 2023 11:16:26 AM br.com.pagseguro.mobile.commons.core.Utils startDeviceLocal
INFO: Device Pixel_3_API_29 is loaded
[HTTP] --> POST /session
[HTTP] {"desiredCapabilities":{"appActivity":".CardsSampleActivity","appPackage":"br.com.uol.ps.myaccount.cards.sample","newCommandTimeout":280,"automationName":"flutter","autoGrantPermissions":true,"platformName":"android","deviceName":"EMULATOR32X1X11X0"},"capabilities":{"firstMatch":[{"appium:appActivity":".CardsSampleActivity","appium:appPackage":"br.com.uol.ps.myaccount.cards.sample","appium:autoGrantPermissions":true,"appium:automationName":"flutter","appium:deviceName":"EMULATOR32X1X11X0","appium:newCommandTimeout":280,"platformName":"android"}]}}
[Appium] Attempting to find matching driver for automationName 'flutter' and platformName 'android'
[Appium] The 'flutter' driver was installed and matched caps.
[Appium] Will require it at /Users/idd_tmaciel/node_modules/appium-flutter-driver
[AppiumDriver@439c] Appium v2.0.0-beta.56 creating new FlutterDriver (v1.13.0) session
[AppiumDriver@439c] Checking BaseDriver versions for Appium and FlutterDriver
[AppiumDriver@439c] Appium's BaseDriver version is 9.3.2
[AppiumDriver@439c] FlutterDriver's BaseDriver version is 9.3.2
[FlutterDriver@35b0] The following capabilities were provided, but are not recognized by Appium:
[FlutterDriver@35b0]   appActivity
[FlutterDriver@35b0]   appPackage
[FlutterDriver@35b0]   autoGrantPermissions
[FlutterDriver@35b0 (59eca822)] Session created with session id: 59eca822-690b-4760-aa10-67675a5b8b40
[FlutterDriver] Starting an Android proxy session
[AndroidUiautomator2Driver@b2f5 (5fc79a9a)] Session created with session id: 5fc79a9a-2a91-4ad6-a9bd-a79c4be9faaa
[AndroidUiautomator2Driver@b2f5 (5fc79a9a)] Starting 'br.com.uol.ps.myaccount.cards.sample' directly on the device
[ADB] Found 5 'build-tools' folders under '/Users/idd_tmaciel/Library/Android/sdk' (newest first):
[ADB]     /Users/idd_tmaciel/Library/Android/sdk/build-tools/31.0.0
[ADB]     /Users/idd_tmaciel/Library/Android/sdk/build-tools/30.0.3
[ADB]     /Users/idd_tmaciel/Library/Android/sdk/build-tools/29.0.3
[ADB]     /Users/idd_tmaciel/Library/Android/sdk/build-tools/29.0.2
[ADB]     /Users/idd_tmaciel/Library/Android/sdk/build-tools/28.0.3
[ADB] Using 'adb' from '/Users/idd_tmaciel/Library/Android/sdk/platform-tools/adb'
[AndroidDriver] Retrieving device list
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb' from '/Users/idd_tmaciel/Library/Android/sdk/platform-tools/adb'
[ADB] Getting device platform version
[AndroidUiautomator2Driver@b2f5 (5fc79a9a)] Relaxing hidden api policy
[AndroidDriver] No app sent in, not parsing package/activity
[AndroidUiautomator2Driver@b2f5 (5fc79a9a)] Server package at '/Users/idd_tmaciel/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v5.7.8.apk' is not writeable. Will copy it into the temporary location at '/var/folders/dg/0ftygxlx1v5716tdr8qjhh_xnw1vbs/T/2023213-59844-1kf0vq5.7x9z' as a workaround. Consider making this file writeable manually in order to improve the performance of session startup.
[AndroidUiautomator2Driver@b2f5 (5fc79a9a)] Server package at '/Users/idd_tmaciel/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is not writeable. Will copy it into the temporary location at '/var/folders/dg/0ftygxlx1v5716tdr8qjhh_xnw1vbs/T/2023213-59844-1kf0vq5.7x9z' as a workaround. Consider making this file writeable manually in order to improve the performance of session startup.
[ADB] Using 'apksigner.jar' from '/Users/idd_tmaciel/Library/Android/sdk/build-tools/31.0.0/lib/apksigner.jar'
[ADB] '/var/folders/dg/0ftygxlx1v5716tdr8qjhh_xnw1vbs/T/2023213-59844-1kf0vq5.7x9z/appium-uiautomator2-server-v5.7.8.apk' is signed with the default certificate
[ADB] '/var/folders/dg/0ftygxlx1v5716tdr8qjhh_xnw1vbs/T/2023213-59844-1kf0vq5.7x9z/appium-uiautomator2-server-debug-androidTest.apk' is signed with the default certificate
[AndroidUiautomator2Driver@b2f5 (5fc79a9a)] Server packages are not going to be (re)installed
[ADB] Adding packages ["io.appium.settings","io.appium.uiautomator2.server","io.appium.uiautomator2.server.test"] to Doze whitelist
[AndroidUiautomator2Driver@b2f5 (5fc79a9a)] Starting UIAutomator2 server 5.7.8
[AndroidUiautomator2Driver@b2f5 (5fc79a9a)] Using UIAutomator2 server from '/Users/idd_tmaciel/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v5.7.8.apk' and test from '/Users/idd_tmaciel/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk'
[AndroidUiautomator2Driver@b2f5 (5fc79a9a)] Waiting up to 30000ms for UiAutomator2 to be online...
[AndroidUiautomator2Driver@b2f5 (5fc79a9a)] socket hang up
[AndroidUiautomator2Driver@b2f5 (5fc79a9a)] socket hang up
[AndroidUiautomator2Driver@b2f5 (5fc79a9a)] socket hang up
[AndroidUiautomator2Driver@b2f5 (5fc79a9a)] Determined the downstream protocol as 'W3C'
[AndroidDriver] Screen already unlocked, doing nothing
[AndroidUiautomator2Driver@b2f5 (5fc79a9a)] Starting 'br.com.uol.ps.myaccount.cards.sample/.CardsSampleActivity and waiting for 'br.com.uol.ps.myaccount.cards.sample/.CardsSampleActivity'
[FlutterDriver] Attempt #1
[ADB] Found 5 'build-tools' folders under '/Users/idd_tmaciel/Library/Android/sdk' (newest first):
[ADB]     /Users/idd_tmaciel/Library/Android/sdk/build-tools/31.0.0
[ADB]     /Users/idd_tmaciel/Library/Android/sdk/build-tools/30.0.3
[ADB]     /Users/idd_tmaciel/Library/Android/sdk/build-tools/29.0.3
[ADB]     /Users/idd_tmaciel/Library/Android/sdk/build-tools/29.0.2
[ADB]     /Users/idd_tmaciel/Library/Android/sdk/build-tools/28.0.3
[ADB] Using 'adb' from '/Users/idd_tmaciel/Library/Android/sdk/platform-tools/adb'
[AndroidDriver] Retrieving device list
[AndroidDriver] Using device: emulator-5554
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:32841/B4paYIJYmck=/ws
[FlutterDriver] Connecting to ws://127.0.0.1:32841/B4paYIJYmck=/ws
[FlutterDriver] Listing all isolates: [{"type":"@Isolate","id":"isolates/3625612902441627","name":"main","number":"3625612902441627","isSystemIsolate":false},{"type":"@Isolate","id":"isolates/3292573598824223","name":"main","number":"3292573598824223","isSystemIsolate":false}]
[AppiumDriver@439c] New FlutterDriver session created successfully, session 59eca822-690b-4760-aa10-67675a5b8b40 added to master session list
[HTTP] <-- POST /session 200 10380 ms - 889
[HTTP] 
mar. 13, 2023 11:16:37 AM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
[HTTP] --> GET /session/59eca822-690b-4760-aa10-67675a5b8b40/context
[HTTP] {}
[HTTP] <-- GET /session/59eca822-690b-4760-aa10-67675a5b8b40/context 200 6 ms - 19
[HTTP] 
[HTTP] --> GET /session/59eca822-690b-4760-aa10-67675a5b8b40/contexts
[HTTP] {}
[HTTP] <-- GET /session/59eca822-690b-4760-aa10-67675a5b8b40/contexts 200 93 ms - 34
[HTTP] 
[HTTP] --> POST /session/59eca822-690b-4760-aa10-67675a5b8b40/context
[HTTP] {"name":"FLUTTER"}
[HTTP] <-- POST /session/59eca822-690b-4760-aa10-67675a5b8b40/context 200 1 ms - 14
[HTTP] 
[HTTP] --> POST /session/59eca822-690b-4760-aa10-67675a5b8b40/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiYnRuX3ByaW1hcnlfYnV0dG9uX2tleSJ9/click
[HTTP] {"id":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiYnRuX3ByaW1hcnlfYnV0dG9uX2tleSJ9"}`

**Comment by KazuCocoa** [comment]
Could you set the log level as debug to show more logs?
I guess no response by the Dart VM.



> Is possible to start the native application with capability set to: "UiAutomator2" and get the "FLUTTER" context when arrives at the flutter screen? If not, there is a solution to this scenario?

No, because this driver tries to establish a session with DartVM when the app under test process starts. After the new session request, you could switch the context with native app, which is UIA2 in Android, though.

Was your app not able to start a new session without the workaround below?

> I did a workaround, I made my application starts with a flutter session behind the curtains, so I started with the applicationName as 'Flutter' and

**Comment by idd-tmaciel** [comment]
Reading all the documentation, I realized the way that I'm trying the implementation is not possible, I'll keep trying the workaround starting the application with automationName as Flutter and in the native screens switch the context.
Thanks for answering @KazuCocoa.
