### ISSUE TITLE
No Chromedriver found that can automate Chrome '111.0.5563'.

### ISSUE THREAD

**Issue by thuonglai** [appium-userland/appium-flutter-driver#438]
Hi @KazuCocoa . Chrome has new version is 111.0.5563.
But when i switch to webview has error as following 
`io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '111.0.5563'.`

Can you check help me why it happen. Seem appium-chromedriver of appium-uiautomator2-driver not update new version.
Thank you.

**Comment by KazuCocoa** [comment]
Did you run with `appium server --allow-insecure chromedriver_autodownload`?
https://github.com/appium/appium-uiautomator2-driver/#automatic-discovery-of-compatible-chromedriver

**Comment by thuonglai** [comment]
Yes. I have run appium with chromedriver_autodownload, but it still error.
This is my appium log. https://gist.github.com/thuonglai/c2ce0062cd26d129cd419bbab35b825e

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/18368 is maybe the same one. A new uia2 driver will fix the regression. then I'll create a new version for this driver. Then please try it out. I'll leave a comment when a new version is ready.

**Comment by KazuCocoa** [comment]
Could you try out 1.14.1?

**Comment by thuonglai** [comment]
It is working with 1.14.1. Thanks you.
