### ISSUE TITLE
Connecting to Dart Observatory: undefined

### ISSUE THREAD

**Issue by MummanaSubramanya** [appium-userland/appium-flutter-driver#439]
Im unable to run the tests on Android device please help...
I am using the app downloaded from here https://github.com/appium-userland/appium-flutter-driver/tree/main/example/sample2

Capabilities:
`{app=C:\Users\subramanya.mummana\Documents\Projects\RandomProjects\untitled\app-debug.apk, appPackage=com.example.flutter_example_app, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, deviceName=2C081JEGR01385, fullReset=true, platform=LINUX, deviceUDID=2C081JEGR01385, desired={platformName=android, app=C:\Users\subramanya.mummana\Documents\Projects\RandomProjects\untitled\app-debug.apk, autoGrantPermissions=true, automationName=Flutter, deviceName=2C081JEGR01385, fullReset=true, udid=2C081JEGR01385}, webStorageEnabled=false, locationContextEnabled=false, automationName=Flutter, takesScreenshot=true, autoGrantPermissions=true, javascriptEnabled=true, platformName=android, udid=2C081JEGR01385}`

Appium logs:

```
`[debug] [FlutterDriver] C:\Program Files\Android\SDK\platform-tools\adb.exe -s 2C081JEGR01385 forward tcp:44499 tcp:44499
[FlutterDriver] Connecting to Dart Observatory: undefined
[FlutterDriver] {}
[FlutterDriver] Check Dart Observatory URI no URI found in the device log
[FlutterDriver] Waiting 3 seconds before trying...
[FlutterDriver] Attempt #29
[ADB] Using 'adb.exe' from 'C:\Program Files\Android\SDK\platform-tools\adb.exe'
[debug] [ADB] Running 'C:\Program Files\Android\SDK\platform-tools\adb.exe -P 5037 start-server'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices
[debug] [ADB] Connected devices: [{"udid":"2C081JEGR01385","state":"device"}]
[AndroidDriver] Using device: 2C081JEGR01385
[debug] [FlutterDriver] C:\Program Files\Android\SDK\platform-tools\adb.exe -s 2C081JEGR01385 forward tcp:44499 tcp:44499
[FlutterDriver] Connecting to Dart Observatory: undefined
[FlutterDriver] {}
[FlutterDriver] Check Dart Observatory URI no URI found in the device log
[FlutterDriver] Failed to connect 30 times. Aborting.
[debug] [FlutterDriver] Deleting Flutter Driver session
[debug] [AppiumDriver@75d0] Event 'newSessionStarted' logged at 1679845960685 (17:52:40 GMT+0200 (Central European Summ`

```
Device logs 
Below you can see in logs had the observatory ui :  http://127.0.0.1:39645/zYkk7ryudsA=/
```

03-26 17:35:56.320 W/ter_example_app(29418): type=1400 audit(0.0:10773): avc: denied { read } for name="max_map_count" dev="proc" ino=1426818 scontext=u:r:untrusted_app:s0:c53,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=com.example.flutter_example_app
03-26 17:35:56.368 W/OnBackInvokedCallback(29418): OnBackInvokedCallback is not enabled for the application.
03-26 17:35:56.368 W/OnBackInvokedCallback(29418): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
03-26 17:35:56.379 I/flutter (29418): The Dart VM service is listening on http://127.0.0.1:39645/zYkk7ryudsA=/
03-26 17:35:56.384 W/ter_example_app(29418): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (unsupported,test-api, reflection, allowed)
03-26 17:35:56.384 W/ter_example_app(29418): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (unsupported, reflection, allowed)
03-26 17:35:56.384 W/ter_example_app(29418): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (unsupported, reflection, allowed)
03-26 17:35:56.384 W/ter_example_app(29418): Accessing hidden method Landroid/util/LongArray;->get(I)J (unsupported, reflection, allowed)
03-26 17:35:56.405 D/CoreBackPreview( 1695): Window{5e8a7c6 u0 com.example.flutter_example_app/com.example.flutter_example_app.MainActivity}:
```

**Comment by KazuCocoa** [comment]
Could you share the entire appium log?

**Comment by MummanaSubramanya** [comment]
@KazuCocoa Thanks for replying. Ater 2 days of debugging the library I found that it was throwing exception at this line https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/lib/sessions/observatory.ts#L33
when I printed the exception, I found that it was the issue with the spaces in the SDK path "C:\Program Files\Android\SDK\platform-tools\adb.exe ". I would be great if you could log/print the stacktrace instead of ignoring the exception at line https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/lib/sessions/observatory.ts#L35

**Comment by KazuCocoa** [comment]
Added https://github.com/appium-userland/appium-flutter-driver/pull/441. It is appreciated to create a pr (since you already know the exact place to add logs) as this is a voluntary based project
