### ISSUE TITLE
Get Attributes from Element in Python

### ISSUE THREAD

**Issue by Takrem1** [appium-userland/appium-flutter-driver#443]
Hey I am checking if the Appium Flutter Driver is suitable for our app.
The tests are written in **Python**.
Is there a possibility to read the attributes of an element? In the `NATIVE_APP` context you can use the method `get_attributes`, but this is not possible in the `FLUTTER` context. Is there another possibility?

I am looking for something like this:
```
finder = FlutterFinder()
switch_finder = finder.by_semantics_label("switch_semantics_lable")
switch_element = FlutterElement(driver, switch_finder)
if switch_element.get_attribute("checked"):
    ...
```

**Comment by KazuCocoa** [comment]
Maybe no. if such get attribute thing was not available via https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html, this driver cannot do it
