### ISSUE TITLE
Webview still work in progress?

### ISSUE THREAD

**Issue by jagradang** [appium-userland/appium-flutter-driver#45]
I noticed that swtiching views are still on the todo list as not being done. Is there any timeline as to when these features may become available.  I have a flutter app i'm trying to write tests for but the login page uses keycloak and therefore navigates into a webview to navigate to a website, login and retrieve the token.  I was hoping to be able to automate the flow but in order to do so i need to be able to switch views.  Is there any way i can use appium commands to switch the view or would i have to wait until its developed under this project?

**Comment by shibupanda** [comment]
@jagradang This is on hold. As the dependent API is not yet provided from Flutter community.
@truongsinh has already raised the issue there please refer below link.
https://github.com/flutter/flutter/issues/36259

**Comment by MikeBenitez1** [comment]
Hi @shibupanda  @truongsinh  @KazuCocoa  , is there an ETA to integrate/support this feature or any help we can do? I am facing issues with this also and most of our scenarios needs to interact with a webview embedded in a Flutter app 😞 .

Thanks in advance 🙏

**Comment by KazuCocoa** [comment]
Did the app enable debugging feature to access to the WebView?
https://pub.dev/documentation/webview_flutter/latest/webview_flutter/WebView/debuggingEnabled.html

I guess if the flag is enabled, then probably getContexts will return WebView.
https://github.com/appium-flutter-driver/appium-flutter-driver/blob/ce2315acf28a3b92386779ecb9e7a45d62a3eca9/driver/lib/commands/context.ts#L13

---

I haven't dug in the flutter webview well yet, but the above flag is general webview preference for Android and iOS.

**Comment by MikeBenitez1** [comment]
Hi @KazuCocoa thanks for the answer, yes the app has the webView debugging flag enabled, the thing is that while using the Appium-Flutter-Driver (Ruby) I am able to get all the available contexts (WebView included) also I am able to set the WebView context but not able to find any WebView element (tried all the web element location approaches), even I added these capabilities `enableWebviewDetailsCollection: true,
      ensureWebviewsHavePages: true`
but Appium does not recognize them while using appium-flutter-driver (I saw that in Appium logs) 😢 .

I tried to set WebView context and find that particular element (from attached logs) on Appium Inspector (**but with AutomationName: UiAutomator2**) and everything works fine, So I assumed that it may be something related to the appium-flutter-driver when dealing with webviews 😞 .

![2021-08-23_17-26-18](https://user-images.githubusercontent.com/59778782/130533556-522d9dae-9edd-46c1-8bc6-0fa866a24cb4.png)

**Comment by KazuCocoa** [comment]
I see.
Do you know a good example of Flutter x WebView I can try out as a test app?
So, probably this issue eventually should handle WebView context by UIA2/XCUITest as same as native/flutter contexts.

I'll try to dig the cause in when I have a chance, but it is welcome to add this feature by someone.

**Comment by MikeBenitez1** [comment]
Hi @KazuCocoa  here's a Flutter application with a WebView, its ready to compile _`(with WebContentsDebugging and flutter_driver enabled)`_ https://github.com/MikeBenitez1/flutter_browser_app or if you prefer the apk you can find it here: https://drive.google.com/drive/folders/1tVnBIndCzA9Tjq-cXUWvzxDyYrVYzUx1?usp=sharing

We really appreciate your support on this.

**Comment by KazuCocoa** [comment]
I haven't tested, but probably like https://github.com/appium-userland/appium-flutter-driver/pull/178 may be the cause

**Comment by KazuCocoa** [comment]
Probably https://github.com/appium-userland/appium-flutter-driver/pull/178 works.
I checked some WebView contexts by https://github.com/appium-userland/appium-flutter-driver/issues/45#issuecomment-905179992 (thanks).

When you provide `--relaxed-security` or `--allow-insecure=chromedriver_autodownload`, autodownloading a proper cheomedriver also worked.

**Comment by KazuCocoa** [comment]
I've pushed the change as https://www.npmjs.com/package/appium-flutter-driver/v/0.0.32 
You can apply the change on your local, or you could try the version with `appium@beta` (then, please make sure to re-install appium)

**Comment by KazuCocoa** [comment]
I only tested on Android briefly, so it is appreciated to try out on iOS... (If something issue happens, please create a new issue.)

**Comment by MikeBenitez1** [comment]
> Probably #178 works.
> I checked some WebView contexts by [#45 (comment)](https://github.com/appium-userland/appium-flutter-driver/issues/45#issuecomment-905179992) (thanks).
> 
> When you provide `--relaxed-security` or `--allow-insecure=chromedriver_autodownload`, autodownloading a proper cheomedriver should also work.

I tried to run Appium (1.21) with this args but still is the same behavior.

**Comment by KazuCocoa** [comment]
No, `appium@beta` is required to get the latest change.

> You can apply the change on your local, or you could try the version with appium@beta (then, please make sure to re-install appium)

It does not in appium 1.21.0 since it bundles 0.0.29.

**Comment by MikeBenitez1** [comment]
> I've pushed the change as https://www.npmjs.com/package/appium-flutter-driver/v/0.0.32
> You can apply the change on your local, or you could try the version with `appium@beta` (then, please make sure to re-install appium)

The good thing is I tested the webview context switching with the last Appium Beta 1.22.0 ( and the fix is working fine 🎉 , thanks @KazuCocoa , I hope the release for 1.22 will happen soon 😉.

**Comment by MikeBenitez1** [comment]
> No, `appium@beta` is required to get the latest change.
> 
> > You can apply the change on your local, or you could try the version with appium@beta (then, please make sure to re-install appium)
> 
> It does not in appium 1.21.0 since it bundles 0.0.29.

I was just writing my previous comment that I tested with the appium@beta and it was cool, hehe thanks @KazuCocoa
