### ISSUE TITLE
Cannot figure out how to tap text with gesture detector in Python with no tap (elementClick - touchAction) for python

### ISSUE THREAD

**Issue by AradhyaNepal** [appium-userland/appium-flutter-driver#450]
![image](https://user-images.githubusercontent.com/66102711/233562808-c260df73-2754-4c0e-9659-663154847449.png)

I cannot find above implementation for python.

I needs those implementation because:
` FlutterElement(self.driver, self.finder.by_text("Skip")).click()` 

OR

`FlutterElement(self.driver, self.finder.by_semantics_label("SkipButton")).click()` 

This code is not working.

Where My Flutter Code is like this: 
![image](https://user-images.githubusercontent.com/66102711/233563271-9558d1f6-f745-407c-8d37-96aad60e1211.png)
![image](https://user-images.githubusercontent.com/66102711/233563341-15c5b6af-9b38-4a4d-8d74-3fa8dfaedb9d.png)

Two placement, none working.

Server shows this:
![image](https://user-images.githubusercontent.com/66102711/233563989-b04db6fa-e27e-4e2c-83a1-d6493b4c33c5.png)

And the test freeze. 

Also can we set a timeout, that if in x duration if click action didn't happen instead of freezing, throw timeout error. I need to close the client terminal everytime the test freeze.

**Comment by AradhyaNepal** [comment]
**I tried in a Isolated project with below setup:**
```
Semantics(
      label: "TextPressOne",
      child: GestureDetector(
        key: ValueKey("text_press"),
        onTap: () {
          showDialog(
              context: context,
              builder: (context) => const AlertDialog(
                    title: Text("Hello"),
                    content: Text("Bello"),
                  ));
        },
        child: Semantics(
          label: "TextPressTwo",
          child: const Text(
            "Text To Be Pressed",
            semanticsLabel: "TextPressTree",
          ),
        ),
      ),
    )
```

Here are the logs, it worked with id in gesture detector on isolated project.
```
        # Works
        TouchAction(self.driver).tap(FlutterElement(self.driver,self.finder.by_value_key("text_press"))).perform()
        # Or Simply
        FlutterElement(self.driver, self.finder.by_value_key("text_press")).click()

        # Don't Work
        TouchAction(self.driver).tap(FlutterElement(self.driver,self.finder.by_semantics_label("TextPressOne"))).perform()

        # Don't Work
        TouchAction(self.driver).tap(FlutterElement(self.driver,self.finder.by_semantics_label("TextPressTwo"))).perform()

        # Don't Work
        TouchAction(self.driver).tap(FlutterElement(self.driver,self.finder.by_semantics_label("TextPressTree"))).perform()
```


**But when I tried same thing in main project, the tap didn't worked:**

```
        TouchAction(self.driver).tap(FlutterElement(self.driver,self.finder.by_value_key("skip_button"))).perform()
```

With This code:
```
                         GestureDetector(
                            key: ValueKey("skip_button"),
                            onTap: () {
                              provider.introDone(context);
                            },
                            child: Text(
                              "Skip",
                              semanticsLabel: "SkipButton",
                            ),
                          )
```

In the same main project's screen, there is:
```
     FloatingActionButton(
          backgroundColor: Color(GeneralColorUtils.getPrimaryColor()),
          onPressed: () {
            provider.nextPage(context);
          },
          child: Semantics(
            label: "NextButton",
            child: const Icon(
              Icons.arrow_forward_ios,
            ),
          ),
        )
```
The Tap is working here, If tap is working in Floating action button it must also work in Gesture detector's text because they are on the same page, so loading and other effects does same impact on them both: 
```
        TouchAction(self.driver).tap(FlutterElement(self.driver,self.finder.by_semantics_label("NextButton"))).perform()
        # OR Simply
        # FlutterElement(self.driver,self.finder.by_semantics_label("NextButton")).click()
```

Just the difference between Floating and Gesture is that there is a stack in the page inside which there is the Skip Text with Gesture Detector.
![image](https://user-images.githubusercontent.com/66102711/233758533-5102fc06-7a47-49ad-b0fb-5676cec5fbbc.png)


So in Isolated project, I did the same setup, and its working there in isolation.
`TouchAction(self.driver).tap(FlutterElement(self.driver,self.finder.by_value_key("text_press"))).perform()`

```
Stack(
      children: [
        Container(
          child: Column(
            children: [
              SizedBox(
                child: Row(
                  children: [
                    Container(
                      child: GestureDetector(
                        key: ValueKey("text_press"),
                        onTap: () {
                          showDialog(
                              context: context,
                              builder: (context) => const AlertDialog(
                                    title: Text("Hello"),
                                    content: Text("Bello"),
                                  ));
                        },
                        child: const Text(
                          "Text To Be Pressed",
                          semanticsLabel: "TextPressTree",
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    )
```



Do you got any idea what external thing is causing the problem? I tried alot but cannot figure out.

**Comment by AradhyaNepal** [comment]
Previously the widget was like this:
```
    # Scaffold wrapped with AnnotatedRegion ( ...SystemUiOverlayStyle ...
      Scaffold(
#...... other codes
        body: SafeArea(
          child: Stack(
            children: [
              Container(
                color: Theme.of(context).canvasColor,
                width: double.infinity,
                child: Column(
                  children: <Widget>[
                    SizedBox(
                      height: 4.h,  # <------------Here
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.end,
                      children: [
                        GestureDetector(
                          key: ValueKey("skip_button"),
                          onTap: () {
                            provider.introDone(context);
                          },
                          child: Text(
                            "Skip",
                            semanticsLabel: "SkipButton",
                          ),
                        ),
                      ],
                    ),
                    //.... Other Codes below
```


I Increased the height of the sized box to 14.h (Doing less than 14.h in integers is not being pressed)

And now its being pressed. Although previously too the element was displaced in the screen, it was not able to be clicked, may be due to other codes interface.

With this my issue is solved, and I learned about a new class TouchAction(), (Although now with extra padding, code will work simply by .click(), but TouchAction class seems interesting.)


**But before closing the issue can you answer me few things:**

1.  TouchAction sends a warning that its deprecated, our project is long running project, so should be use it,  or there are better alternative which provide all functionality as TouchAction.
2. Is this Repo issue is right place to ask my confusion, like this regarding tap, because in our company we are implementing automation integration test for first time and our codebase is really big. So we might need fast feedback loop, even small help makes big difference to us.  Also creating issue might promote your repo on google search engine for others who faced same issue. Or sometime some of our confusion might not be confusion, it might be a real issue to be solved??
3. If its not you might give me better alternative..

**Comment by KazuCocoa** [comment]
Glad to hear it. As this driver, all Flutter related commands are via https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html. so everything basically depends on how Flutter works. Unfortunately, this driver itself does not have so much to do Flutter/DartVM directly, but happy to hear you figured out the solution, and learned more.


> 1. 

The method itself (as vanilla Appium/Selenium client) is actually deprecated since it is not in W3C WebDriver protocol definition. Generally, the alternative is W3C Actions, but as for this project, maybe we could add `flutter:tap` or similar command which does the same thing in the backend. https://github.com/appium-userland/appium-flutter-driver/blob/fa7f03a822f6b7040dfbb12def45f1e3e5be17b0/driver/lib/commands/gesture.ts#L20-L67 is what this driver sends to the Dart VM. This is not actual TouchAction in vanilla appium/selenium term. (This could confuse if you're not familiar with W3C protocol thing, but in short, it depends on command definition dependent, not an actual issue)


> 2. and 3

As this README, this project is volunteer/community based, mostly by me right now, and my personal time. So I'd recommend you to find paid service/consultation to get more fast feedback if needed. My knowledge for the Flutter application implementation is also limited.
Leaving your findings in this repository, or https://discuss.appium.io/ may help to someone who has similar issues, in general. It is appreciated to contribute Appium community.
