### ISSUE TITLE
running on appium:automationName": "Flutter" stuck

### ISSUE THREAD

**Issue by amiravisar89** [appium-userland/appium-flutter-driver#454]
I am trying to detect element like `Text` and `MaterialButton` (Flutter Widgets) on appium inspector.
I am setting a Key param like` Key("example")` on a Widget and trying to find the element by id ("example").
running with appium inspector hangs when using "Flutter".

Of course, the app has build with --debug.

this is my json:
{
  "appium:deviceName": "iPhone 14 Pro",
  "appium:automationName": "Flutter",
  "appium:platformVersion": "16.2",
  "platformName": "iOS",
  "appium:app": "Desktop/Runner.zip",
  "appium:wdaLocalPort": "8100"
}
when using so, appium inspector run but hangs a second before presenting the app on this state:
Both buttons are MaterialButton like so:
```
MaterialButton(
              key: const Key("example"),
              onPressed: () {
                context.pushNamed(loginScreen.name);
              },
              color: Theme.of(context).primaryColor,
              child: Text(context.localization.go_to_login_page)
)
```

![Screenshot 2023-04-27 at 13 30 03](https://user-images.githubusercontent.com/18641468/234836625-25ef05b6-8078-4007-886a-ff43aad09d0b.png)

this is my appium:
![Screenshot 2023-04-27 at 13 22 02](https://user-images.githubusercontent.com/18641468/234836699-8c338c7f-c629-4b7f-ad2e-1eea9deedd2c.png)

appium version is : 2.0.0-beta.57

this is my Flutter:
Flutter 3.7.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ad6cd72c0 (7 weeks ago) • 2023-03-08 09:41:59 -0800
Engine • revision 1837b5be5f
Tools • Dart 2.19.4 • DevTools 2.20.1

appium driver Logs:
![Screenshot 2023-04-27 at 13 33 04](https://user-images.githubusercontent.com/18641468/234837295-0f0e1dcc-7510-48a9-a56f-1721c76de113.png)

FYI: I know i can use `Semantics` Object by Dart native, but i don't want to wrap all my elements in `Semantics`. and this is what this package aim to prevent right?

**Comment by Stephane99** [comment]
Hi,
`Appium Inspector` does not support the `Flutter` session for now.
You can use the `Flutter Inspector` from Android Studio to see the Flutter widgets.

**Comment by KazuCocoa** [comment]
Correct, this driver does not work with the appium inspector since the `/source` endpoint does not work in Flutter context
