### ISSUE TITLE
MobileElement cant resolve on java-client 8.3

### ISSUE THREAD

**Issue by amiravisar89** [appium-userland/appium-flutter-driver#455]
The main issue is that `java-client` 8.3 does not have `MobileElement`. this is a conflict.

this is my dependencies:
![image (2)](https://user-images.githubusercontent.com/18641468/235353811-9bfe40ec-22ac-4d9e-8116-29bbf567780d.png)

![image (3)](https://user-images.githubusercontent.com/18641468/235353813-918e8924-eec0-4742-9541-36b1aad7b376.png)
![image (4)](https://user-images.githubusercontent.com/18641468/235353817-a8df87bc-8d51-423d-bea9-996f46f9583b.png)

this is my drivers:
![Screenshot 2023-04-30 at 15 48 27](https://user-images.githubusercontent.com/18641468/235353821-d5578ab6-8073-425b-aeda-fb1e8711e51a.png)

`appium_flutterfinder_java` doest not have `MobileElement`.

this is the erros in the SDK:
![image](https://user-images.githubusercontent.com/18641468/235353925-54ada92a-6a29-4716-ba8d-a8bfc92886ab.png)

appium : 2.0.0-beta.52
Flutter: 3.3.9

what should i do?

**Comment by pothurajtharun** [comment]
FYI: https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md#mobileelement

**Comment by ashwithpoojary98** [comment]
Hey @amiravisar89, please update your Maven latest Java client updated.

**Comment by ashwithpoojary98** [comment]
@KazuCocoa please close this issue.
