### ISSUE TITLE
Is there a way to switch the capabilities between "Flutter" and "UiAutomator2" in a single app while running tests ?

### ISSUE THREAD

**Issue by BavithiranOneMindIndia** [appium-userland/appium-flutter-driver#457]
Used 
driver.context('Flutter')

still in appium only uiAutomator driver is working but it is not changing to flutter driver

**Comment by KazuCocoa** [comment]
Could you share the full log?

**Comment by BavithiranOneMindIndia** [comment]
`[debug] [AndroidUiautomator2Driver@dea6 (b53f6d80)] Calling AppiumDriver.getCurrentContext() with args: ["b53f6d80-e237-4708-ad1c-1e1b1a59ffc6"]
[debug] [AndroidUiautomator2Driver@dea6 (b53f6d80)] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/b53f6d80-e237-4708-ad1c-1e1b1a59ffc6/context 200 12 ms - 22`



above log in appium server console


and in vs code

driver = context.driver_UiAutomator.context('Flutter')
TypeError: 'str' object is not callable


Thanks

**Comment by KazuCocoa** [comment]
Could you give the full log to see various information?
The shared log only see it returned 200 ok, but nothing others.

**Comment by KazuCocoa** [comment]
Close as not full log attached
