### ISSUE TITLE
Flutter_driver deprecated causing this error: "ext.flutter.driver" is not found in "extensionRPCs"

### ISSUE THREAD

**Issue by nejham** [appium-userland/appium-flutter-driver#472]
Hi there. Since `flutter_driver` is being deprecated in favor of `integration_test` and  `enableFlutterDriverExtension()` is not in that module. ¿Is there any other way to solve this issue?

<img width="1587" alt="image" src="https://github.com/appium-userland/appium-flutter-driver/assets/19480451/4c5cc4b4-c748-44d7-9350-1a0fb8031b61">

**Comment by KazuCocoa** [comment]
Do you mean even after adding `flutter_driver` dependencies in your deps, no the module found error happens?
https://github.com/appium-userland/appium-flutter-driver/blob/e57bd279bdda85e504406830f5c443f281241786/example/flutter_app_under_test/pubspec.yaml#L18
