### ISSUE TITLE
What iOS driver version does appium-flutter-driver uses under the hood?

### ISSUE THREAD

**Issue by Ernst-D** [appium-userland/appium-flutter-driver#485]
Hi! 

I wonder what version of [appium-xcuitest-driver](https://appium.github.io/appium-xcuitest-driver/latest) is used internally in this driver? 

I'm asking this question since every new version of XCode has a specific support for each driver and it would nice to know whether appium-flutter-driver uses xcuitest-driver under the hood, which could be potentially unsupported by new versions of XCode.

Thanks in advance!

**Comment by KazuCocoa** [comment]
You can check the version stored in https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/npm-shrinkwrap.json, thus current latest driver has:

```
    "node_modules/appium-xcuitest-driver": {
      "version": "4.29.2",
      "license": "Apache-2.0",
```

**Comment by KazuCocoa** [comment]
You also could check the dependency file from `npm` installed module

**Comment by Ernst-D** [comment]
Thank you for the answer!
