### ISSUE TITLE
Blank screen when the app enters the Flutter page

### ISSUE THREAD

**Issue by Ryaningli** [appium-userland/appium-flutter-driver#487]
I am trying to add flutter-driver to a hybrid development app (iOS native+Flutter or Android native+Flutter), after adding the code `enableFlutterDriverExtension(),` when the app enters the Flutter page, the entire page is blank and white, using appium inspector to view this page also has no any elements. What is the reason for this? Both Android and iOS are the same. Thanks!

**Comment by ashwithpoojary98** [comment]
@Ryaningli try to build the app in profile mode and use the latest Appium driver

**Comment by Ryaningli** [comment]
> @Ryaningli try to build the app in profile mode and use the latest Appium driver

Thanks and that's exactly what I did. The problem has been solved, because flutterboost dependency is used, refer https://github.com/alibaba/flutter_boost/issues/1286
