### ISSUE TITLE
Click element with timeout

### ISSUE THREAD

**Issue by thuonglai** [appium-userland/appium-flutter-driver#488]
Hi @KazuCocoa . 
Sometime i run test, when click element and app has popup and clickElement not have response return. 
Can we have timeout for event "tap"? Thanks

**Comment by KazuCocoa** [comment]
I haven't tested, but probably https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/lib/sessions/isolate_socket.ts#L5-L13 could have `timeout` in `call(method, params, timeout, ws_opts) {` https://github.com/elpheria/rpc-websockets/blob/46b0190bc0ecdce4236b7ccbe93b5e687a5aaf09/build-ts/lib/client.js#L68

**Comment by thuonglai** [comment]
Hi @KazuCocoa . I saw it. But I am using java to test. I must using command "clickElement" of Appium => It auto call 'tap' function without timeout.
So i create new flutter command in pull request [490](https://github.com/appium-userland/appium-flutter-driver/pull/490). Can you check it for me. Thank you very much.

**Comment by Ryaningli** [comment]
Not just click，It seems like all the actions are like this, such as `click` `send_keys` `set_text`. Why not use appium's implicit wait? 
e.g. (python)
`# When executing click(), use the implicit wait, throw an error after 3 seconds. If no implicit wait, immediately throw an error`
`driver.implicitly_wait(3)`
`FlutterElement(driver, FlutterFinder().by_value_key('none_element')).click()`
