### ISSUE TITLE
Why not close application by appium sever 2.0?

### ISSUE THREAD

**Issue by kulrachat** [appium-userland/appium-flutter-driver#491]
I'm having trouble using the 'close application' keyword when running automation from Robot Framework using Appium server version 2.0. Is there a way to address this issue? I'm using the robotframework-appiumflutterlibrary version 1.0.0.

**Comment by KazuCocoa** [comment]
Could you share the full Appium log? Does "close" mean kill the app process? Then, usually `terminate_app` Python method may help. I'm not so  familiar with the robot framework's specific keyword though

**Comment by kulrachat** [comment]
**last keyword is close application**
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] The initialization of the instrumentation process took 6350ms
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Matched '/session' to command name 'createSession'
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Proxying [POST /session] to [POST http://127.0.0.1:8200/session] with body: {"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","platformVersion":"9","deviceName":"68796095","appPackage":"com.ais.mimo.eservice.inhouse1","appActivity":"com.adl.mfaf.MainActivity","noReset":true,"unicodeKeyboard":true,"automationName":"flutter","newCommandTimeout":5000},"platformName":"Android","platformVersion":"9","deviceName":"68796095","appPackage":"com.ais.mimo.eservice.inhouse1","appActivity":"com.adl.mfaf.MainActivity","noReset":true,"unicodeKeyboard":true,"automationName":"flutter","newCommandTimeout":5000,"deviceUDID":"68796095"}],"alwaysMatch":{}}}
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Got response with status 200: {"sessionId":"e3b5f902-66c3-4d9a-962a-75506ebecd61","value":{"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","platformVersion":"9","deviceName":"68796095","appPackage":"com.ais.mimo.eservice.inhouse1","appActivity":"com.adl.mfaf.MainActivity","noReset":true,"unicodeKeyboard":true,"automationName":"flutter","newCommandTimeout":5000},"platformName":"Android","platformVersion":"9","deviceName":"68796095","appPackage":"com.ais.mimo.eservice.inhouse1","appActivity":"com.adl.mfaf.MainActivity","noReset":true,"unicodeKeyboard":true,"automationName":"flutter","newCommandTimeout":5000,"deviceUDID":"68796095"}],"alwaysMatch":{}},"sessionId":"e3b5f902-66c3-4d9a-962a-75506ebecd61"}}
[AndroidUiautomator2Driver@a0f1 (c56ee35f)] Determined the downstream protocol as 'W3C'
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Proxying [GET /appium/device/info] to [GET http://127.0.0.1:8200/session/e3b5f902-66c3-4d9a-962a-75506ebecd61/appium/device/info] with no body
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Got response with status 200: {"sessionId":"e3b5f902-66c3-4d9a-962a-75506ebecd61","value":{"androidId":"31e8298807a22547","apiVersion":"28","bluetooth":{"state":"OFF"},"brand":"samsung","carrierName":"","displayDensity":320,"locale":"th_TH","manufacturer":"samsung","model":"SM-T825Y","networks":[{"capabilities":{"SSID":null,"linkDownBandwidthKbps":1048576,"linkUpstreamBandwidthKbps":1048576,"networkCapabilities":"NET_CAPABILITY_WIFI_P2P,NET_CAPABILITY_NOT_RESTRICTED,NET_CAPABILITY_TRUSTED,NET_CAPABILITY_NOT_VPN,NET_CAPABILITY_FOREGROUND,NET_CAPABILITY_NOT_SUSPENDED","signalStrength":-2147483648,"transportTypes":"TRANSPORT_WIFI"},"detailedState":"IDLE","extraInfo":null,"isAvailable":true,"isConnected":false,"isFailover":false,"isRoaming":false,"state":"UNKNOWN","subtype":0,"subtypeName":"","type":13,"typeName":"WIFI_P2P"},{"capabilities":{"SSID":null,"linkDownBandwidthKbps":1048576,"linkUpstreamBandwidthKbps":1048576,"networkCapabilities":"NET_CAPABILITY_NOT_METERED,NET_CAPABILITY_INTERNET,NET_CAPABILITY_NOT_RESTRICTED,NET_CAPABILITY_TR...
[debug] [ADB] Running 'C:\Users\QA1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 68796095 shell dumpsys window'
[AndroidDriver] Screen already unlocked, doing nothing
[AndroidUiautomator2Driver@a0f1 (c56ee35f)] Starting 'com.ais.mimo.eservice.inhouse1/com.adl.mfaf.MainActivity and waiting for 'com.ais.mimo.eservice.inhouse1/com.adl.mfaf.MainActivity'
[debug] [ADB] Getting IDs of all 'com.ais.mimo.eservice.inhouse1' processes
[debug] [ADB] Running 'C:\Users\QA1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 68796095 shell pgrep -f \(\[\[:blank:\]\]\|\^\)com\.ais\.mimo\.eservice\.inhouse1\(\[\[:blank:\]\]\|\$\)'
[debug] [ADB] Running 'C:\Users\QA1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 68796095 shell am start -W -n com.ais.mimo.eservice.inhouse1/com.adl.mfaf.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Proxying [GET /appium/device/pixel_ratio] to [GET http://127.0.0.1:8200/session/e3b5f902-66c3-4d9a-962a-75506ebecd61/appium/device/pixel_ratio] with no body
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Got response with status 200: {"sessionId":"e3b5f902-66c3-4d9a-962a-75506ebecd61","value":2}
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Matched '/appium/device/system_bars' to command name 'getSystemBars'
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Proxying [GET /appium/device/system_bars] to [GET http://127.0.0.1:8200/session/e3b5f902-66c3-4d9a-962a-75506ebecd61/appium/device/system_bars] with no body
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Got response with status 200: {"sessionId":"e3b5f902-66c3-4d9a-962a-75506ebecd61","value":{"statusBar":48}}
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Matched '/window/current/size' to command name 'getWindowSize'
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Proxying [GET /window/current/size] to [GET http://127.0.0.1:8200/session/e3b5f902-66c3-4d9a-962a-75506ebecd61/window/current/size] with no body
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Got response with status 200: {"sessionId":"e3b5f902-66c3-4d9a-962a-75506ebecd61","value":{"height":2048,"width":1536}}
[FlutterDriver] Attempt #1
[ADB] Found 4 'build-tools' folders under 'C:\Users\QA1\AppData\Local\Android\Sdk' (newest first):
[ADB]     C:/Users/QA1/AppData/Local/Android/Sdk/build-tools/34.0.0-rc1
[ADB]     C:/Users/QA1/AppData/Local/Android/Sdk/build-tools/32.1.0-rc1
[ADB]     C:/Users/QA1/AppData/Local/Android/Sdk/build-tools/32.0.0
[ADB]     C:/Users/QA1/AppData/Local/Android/Sdk/build-tools/30.0.3
[ADB] Using 'adb.exe' from 'C:\Users\QA1\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[debug] [ADB] Running 'C:\Users\QA1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices
[debug] [ADB] Connected devices: [{"udid":"68796095","state":"device"}]
[AndroidDriver] Looking for a device with Android '9.0.0'
[debug] [ADB] Setting device id to 68796095
[ADB] Getting device platform version
[debug] [ADB] Running 'C:\Users\QA1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 68796095 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 9
[AndroidDriver] Using device: 68796095
[debug] [FlutterDriver] C:\Users\QA1\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 68796095 forward tcp:41459 tcp:41459
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:41459/w3BPR8vROUI=/ws
[FlutterDriver] Connecting to ws://127.0.0.1:41459/w3BPR8vROUI=/ws
[FlutterDriver] Listing all isolates: [{"type":"@Isolate","id":"isolates/1901716032791387","name":"main","number":"1901716032791387","isSystemIsolate":false,"isolateGroupId":"isolateGroups/8735614044323390214"}]
[AppiumDriver@112d] New FlutterDriver session created successfully, session 7c2ba3a9-ce38-4759-a18f-3b6eb23eb374 added to master session list
[debug] [AppiumDriver@112d] Event 'newSessionStarted' logged at 1688977171647 (15:19:31 GMT+0700 (Indochina Time))
[debug] [FlutterDriver@d015 (7c2ba3a9)] Cached the protocol value 'W3C' for the new session 7c2ba3a9-ce38-4759-a18f-3b6eb23eb374
[debug] [FlutterDriver@d015 (7c2ba3a9)] Responding to client with driver.createSession() result: {"capabilities":{"subcommand":"server","address":"127.0.0.1","basePath":"/wd/hub","port":4723,"extraArgs":[],"allowCors":false,"allowInsecure":[],"callbackPort":4723,"debugLogSpacing":false,"denyInsecure":[],"keepAliveTimeout":600,"localTimezone":false,"loglevel":"debug","logNoColors":false,"logTimestamp":false,"longStacktrace":false,"noPermsCheck":false,"relaxedSecurityEnabled":false,"sessionOverride":false,"strictCaps":false,"useDrivers":[],"usePlugins":[],"driver":{"xcuitest":{"wdaLocalPort":8100}},"tmpDir":"C:\\Users\\QA1\\AppData\\Local\\Temp","platformName":"Android","platformVersion":"9","deviceName":"68796095","appPackage":"com.ais.mimo.eservice.inhouse1","appActivity":"com.adl.mfaf.MainActivity","noReset":true,"unicodeKeyboard":"true","automationName":"flutter","newCommandTimeout":5000,"fullReset":false,"fastReset":false,"skipUninstall":true}}
[HTTP] <-- POST /wd/hub/session 200 39062 ms - 925
[HTTP]
[HTTP] --> DELETE /wd/hub/session/7c2ba3a9-ce38-4759-a18f-3b6eb23eb374
[HTTP] {}
[debug] [FlutterDriver@d015 (7c2ba3a9)] Calling AppiumDriver.deleteSession() with args: ["7c2ba3a9-ce38-4759-a18f-3b6eb23eb374"]
[debug] [AppiumDriver@112d] Event 'quitSessionRequested' logged at 1688977171681 (15:19:31 GMT+0700 (Indochina Time))
[AppiumDriver@112d] Removing session 7c2ba3a9-ce38-4759-a18f-3b6eb23eb374 from our master session list
[debug] [FlutterDriver] Deleting Flutter Driver session
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Deleting UiAutomator2 session
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Deleting UiAutomator2 server session
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Matched '/' to command name 'deleteSession'
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Proxying [DELETE /] to [DELETE http://127.0.0.1:8200/session/e3b5f902-66c3-4d9a-962a-75506ebecd61] with no body
[debug] [AndroidUiautomator2Driver@a0f1 (c56ee35f)] Got response with status 200: {"sessionId":"e3b5f902-66c3-4d9a-962a-75506ebecd61","value":null}
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running 'C:\Users\QA1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 68796095 forward --remove tcp:8200'
[AndroidUiautomator2Driver@a0f1 (c56ee35f)] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running 'C:\Users\QA1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 68796095 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[debug] [AppiumDriver@112d] Event 'quitSessionFinished' logged at 1688977171965 (15:19:31 GMT+0700 (Indochina Time))
[debug] [AppiumDriver@112d] Received response: null
[debug] [AppiumDriver@112d] But deleting session, so not returning
[debug] [AppiumDriver@112d] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/7c2ba3a9-ce38-4759-a18f-3b6eb23eb374 200 293 ms - 14
[HTTP]
[debug] [Instrumentation] .
[debug] [Instrumentation] Time: 15.074
[debug] [Instrumentation]
[debug] [Instrumentation] OK (1 test)
[debug] [Instrumentation] The process has exited with code 0

**Comment by kulrachat** [comment]
![image](https://github.com/appium-userland/appium-flutter-driver/assets/139092998/3a55caa9-b758-4301-a8d4-13f0433ca07a)

**Comment by KazuCocoa** [comment]
`"noReset":true,`

Maybe it was because you set `"noReset":true,`. 

Appium UIA2 driver added below capability to control the behavior in https://github.com/appium/appium-uiautomator2-driver/blob/master/CHANGELOG.md#2140-2023-04-04. Maybe it affected the behavior.

> appium:shouldTerminateApp
> Set it to true if you want the application under test to be always terminated on session end even if appium:noReset is true. If noReset is falsy, then the app under test is going to be terminated if appium:dontStopAppOnReset is also falsy (the default behavior). false by default

**Comment by KazuCocoa** [comment]
Did you try out “appium:shouldTerminateApp” in the above?

**Comment by kulrachat** [comment]
Example how to use shouldTerminateApp?

**Comment by KazuCocoa** [comment]
Set it as capabilities
