### ISSUE TITLE
'getTimeouts' error appium server

### ISSUE THREAD

**Issue by gitemre** [appium-userland/appium-flutter-driver#515]
Hello, I am encountering an error like this when starting the application with Appium inspector. My app is in debug mode.

Any ideas on what I'm doing wrong?

[FlutterDriver@3cc8 (04bfc84e)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[debug] [FlutterDriver@3cc8 (04bfc84e)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /session/04bfc84e-c5ae-42df-ab09-2fce3945c3a5/timeouts 304 2 ms - -

![Screenshot_1](https://github.com/appium-userland/appium-flutter-driver/assets/71561095/50e114c2-90a4-4df5-97f5-68597431a05b)
![Screenshot_2](https://github.com/appium-userland/appium-flutter-driver/assets/71561095/10f30028-97bb-4bdb-a217-c32b4e524662)

**Comment by KazuCocoa** [comment]
As the error message, appium-flutter-driver's FLUTTER context does not support the page_source.
https://github.com/appium-userland/appium-flutter-driver#note
