### ISSUE TITLE
Appium Session Connection Issue: Failed to connect 30 times. Aborting || Flutter Driver

### ISSUE THREAD

**Issue by baselalali** [appium-userland/appium-flutter-driver#516]
I encountered an issue while trying to establish an Appium session to automate my Flutter app on an Android device  with Android version 10. The Appium session starts successfully, and the app is launched, but the connection to the app fails with the error message "Failed to connect 30 times. Aborting."

**Steps to Reproduce:**

Start the Appium server using the appium command in the terminal.
Attempt to create an Appium session with the following configuration:

```
{
  "platformName": "android",
  "appium:deviceName": "Device123",
  "appium:PlatformVersion": "10",
  "appium:automationName": "Flutter",
  "appium:app": "/Flutter-App/namer_app/build/app/outputs/flutter-apk/app-release.apk",
  "appium:retryBackoffTime": "500"
}
```
_Observe the error message "Failed to connect 30 times. Aborting."_
**Expected Behavior:**
I expected the Appium session to be successfully established, and the Flutter app to be automated without any connection issues.

**Actual Behavior:**
`The Appium session fails to establish a connection to the app, resulting in the error "Failed to connect 30 times. Aborting."
`
Additional Information:

Flutter Version: [e.g., 2.5.0]
Appium Version: [e.g., 2.3.0]
Appium Logs: [Attach any relevant Appium logs or error messages]
Flutter App Source Code: [If possible, provide a link to the repository or the relevant parts of the source code]

NOTE: The issue is not present when using UiAutomator2 as the automation name.
If needed, I can provide more information or logs to assist in troubleshooting the issue.

**Comment by KazuCocoa** [comment]
Could you share the full appium log?

**Comment by KazuCocoa** [comment]
Could you share the full appium log?
Maybe it is `/source` endpoint that is addressed in https://github.com/appium-userland/appium-flutter-driver#note

**Comment by baselalali** [comment]
Since Flutter context does not support page source, How can I effectively use the Appium Flutter Inspector to inspect UI elements within a Flutter application? Are there any specific steps or best practices to follow?

**Comment by KazuCocoa** [comment]
https://docs.flutter.dev/tools/devtools/overview or `getRenderTree` is, I assume. `getRenderTree` returns the source tree by the Flutter VM as-is.
Or you could do it via uia2 driver https://github.com/appium-userland/appium-flutter-driver#appium-flutter-driver-or-appium-uiautomator2xcuitest-driver
