### ISSUE TITLE
"ext.flutter.driver" is not found in "extensionRPCs"

### ISSUE THREAD

**Issue by joan94k** [appium-userland/appium-flutter-driver#519]
this issue still persist while trying

**Comment by KazuCocoa** [comment]
It means the flutter application did not have the `ext.flutter.driver` module. You may need to add flutter_driver package into your build dependency

**Comment by KazuCocoa** [comment]
I have added one additional node in https://github.com/appium-userland/appium-flutter-driver#usage to ensure the flutter_driver usage meaning. hope it will help.
