### ISSUE TITLE
Connecting to Dart Observatory: undefined Check Dart Observatory URI no URI found in the device log

### ISSUE THREAD

**Issue by Rahul1970** [appium-userland/appium-flutter-driver#522]
Hi Team i am working on mobile automation of flutter application using appium 2.0.1 eclipse java 8 Android studio Flamingo Flutter Version 3.7.12 while running my automation script i am getting the message "2023-08-10 11:54:49:925 [FlutterDriver] Connecting to Dart Observatory: undefined
2023-08-10 11:54:49:927 [FlutterDriver] {}
2023-08-10 11:54:49:927 [FlutterDriver] Check Dart Observatory URI no URI found in the device log "

The appium logs are mentioned here in this gist link for your reference : https://gist.github.com/Rahul1970/7f6d18164de022c14bb5199a4950ce0c

**Comment by KazuCocoa** [comment]
it was because your path had a space. Perhaps https://github.com/appium-userland/appium-flutter-driver/pull/521 will also fix the path issue

**Comment by Rahul1970** [comment]
Hi KazuCocoa Thanks a lot for your help. I did what you asked me to do. After installing the new android studio giraffe version and resolving the path issue. When i tried to run my script i got this message in logs. 
[38;5;96m[ADB][0m Using 'adb.exe' from 'C:\Users\Rahul.singh2\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[debug] [38;5;96m[ADB][0m Running 'C:\Users\Rahul.singh2\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[38;5;112m[AndroidDriver][0m Retrieving device list
[debug] [38;5;96m[ADB][0m Trying to find a connected android device
[debug] [38;5;96m[ADB][0m Getting connected devices
[debug] [38;5;96m[ADB][0m Connected devices: [{"udid":"emulator-5554","state":"device"}]
[38;5;112m[AndroidDriver][0m Using device: emulator-5554
[debug] [38;5;48m[FlutterDriver][0m C:\Users\Rahul.singh2\AppData\Local\Android\Sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:37321 tcp:37321
[38;5;48m[FlutterDriver][0m Connecting to Dart Observatory: ws://127.0.0.1:37321/OqF_h8Hitok=/ws
[38;5;48m[FlutterDriver][0m Connecting to ws://127.0.0.1:37321/OqF_h8Hitok=/ws
[38;5;48m[FlutterDriver][0m Listing all isolates: [{"type":"@Isolate","id":"isolates/3786413217850423","name":"main","number":"3786413217850423","isSystemIsolate":false,"isolateGroupId":"isolateGroups/71440323103841136"},{"type":"@Isolate","id":"isolates/2161907833140491","name":"main","number":"2161907833140491","isSystemIsolate":false,"isolateGroupId":"isolateGroups/11532544244002972411"}]
[38;5;48m[FlutterDriver][0m "ext.flutter.driver" is not found in "extensionRPCs" ["ext.ui.window.scheduleFrame","ext.ui.window.reinitializeShader","ext.ui.window.impellerEnabled","ext.dart.io.getHttpEnableTimelineLogging","ext.dart.io.setHttpEnableTimelineLogging","ext.dart.io.httpEnableTimelineLogging","ext.dart.io.getSocketProfile","ext.dart.io.startSocketProfiling","ext.dart.io.pauseSocketProfiling","ext.dart.io.socketProfilingEnabled","ext.dart.io.clearSocketProfile","ext.dart.io.getVersion","ext.dart.io.getHttpProfile","ext.dart.io.getHttpProfileRequest","ext.dart.io.clearHttpProfile","ext.flutter.reassemble","ext.flutter.exit","ext.flutter.connectedVmServiceUri","ext.flutter.activeDevToolsServerAddress","ext.flutter.platformOverride","ext.flutter.brightnessOverride","ext.flutter.timeDilation","ext.flutter.evict","ext.flutter.invertOversizedImages","ext.flutter.debugPaint","ext.flutter.debugPaintBaselinesEnabled","ext.flutter.repaintRainbow","ext.flutter.debugDumpLayerTree","ext.flutter.debugDisableClipLayers","ext.flutter.debugDisablePhysicalShapeLayers","ext.flutter.debugDisableOpacityLayers","ext.flutter.debugDumpRenderTree","ext.flutter.debugDumpSemanticsTreeInTraversalOrder","ext.flutter.debugDumpSemanticsTreeInInverseHitTestOrder","ext.flutter.profileRenderObjectPaints","ext.flutter.profileRenderObjectLayouts","ext.flutter.debugDumpApp","ext.flutter.showPerformanceOverlay","ext.flutter.didSendFirstFrameEvent","ext.flutter.didSendFirstFrameRasterizedEvent","ext.flutter.fastReassemble","ext.flutter.profileWidgetBuilds","ext.flutter.profileUserWidgetBuilds","ext.flutter.debugAllowBanner","ext.flutter.inspector.structuredErrors","ext.flutter.inspector.show","ext.flutter.inspector.trackRebuildDirtyWidgets","ext.flutter.inspector.trackRepaintWidgets","ext.flutter.inspector.disposeAllGroups","ext.flutter.inspector.disposeGroup","ext.flutter.inspector.isWidgetTreeReady","ext.flutter.inspector.disposeId","ext.flutter.inspector.setPubRootDirectories","ext.flutter.inspector.addPubRootDirectories","ext.flutter.inspector.removePubRootDirectories","ext.flutter.inspector.getPubRootDirectories","ext.flutter.inspector.setSelectionById","ext.flutter.inspector.getParentChain","ext.flutter.inspector.getProperties","ext.flutter.inspector.getChildren","ext.flutter.inspector.getChildrenSummaryTree","ext.flutter.inspector.getChildrenDetailsSubtree","ext.flutter.inspector.getRootWidget","ext.flutter.inspector.getRootRenderObject","ext.flutter.inspector.getRootWidgetSummaryTree","ext.flutter.inspector.getRootWidgetSummaryTreeWithPreviews","ext.flutter.inspector.getDetailsSubtree","ext.flutter.inspector.getSelectedRenderObject","ext.flutter.inspector.getSelectedWidget","ext.flutter.inspector.getSelectedSummaryWidget","ext.flutter.inspector.isWidgetCreationTracked","ext.flutter.inspector.screenshot","ext.flutter.inspector.getLayoutExplorerNode","ext.flutter.inspector.setFlexFit","ext.flutter.inspector.setFlexFactor","ext.flutter.inspector.setFlexProperties"]
[38;5;48m[FlutterDriver][0m Failed to connect 30 times. Aborting.

**Comment by KazuCocoa** [comment]
Did you complete https://github.com/appium-userland/appium-flutter-driver#usage ?
I wondered if you did not add flutter_driver dependency

**Comment by Rahul1970** [comment]
Hi  Thanks a lot your suggestion did solve the problem. However facing the issue of not able to run appium server from console getting this message  io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException:
The local appium server has not been started. 
The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments:
[C:\Users\Rahul.singh2\AppData\Roaming\npm\node_modules\appium\build\lib\main.js , --port, 4723, --address, 127.0.0.1, --log,
 D:\APPIUM\Automation\target\resources\appium_server_logs47231, --base-path, /wd/, --session-override] 
The node executable being present in nodejs program files  and flutter driver being present at C:\Users\Rahul.singh2\.appium\node_modules\appium-flutter-driver

**Comment by KazuCocoa** [comment]
What happened when you run the command via CLI directly?
(closing this issue as the flutter driver itself has been resolved)
