### ISSUE TITLE
Problem get text (getText command) from element (Kotlin)

### ISSUE THREAD

**Issue by sashkir7** [appium-userland/appium-flutter-driver#527]
Hi all! Thank you for flutter appium driver!

**I have a problem:** can't get text from element (Kotlin).

**Description:** I write code in Kotlin (in tests use AndroidDriver from appium, since FlitterDriver is not available).
In code I handle with some flutter elements. For example waitFor command:
`androidDriver.executeScript("flutter:waitFor", id, 10_000)`

But in a similar way, I can't execute the get text command - I get an exception that the command is not supported
https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/lib/commands/execute.ts#L84

Also found that the getText command needs to be sent from a flitterDriver instance, which I don't have. 
That is, I cannot execute the command `driver.getElementText(counterTextFinder)`

Can you please tell me how can I get the text from an element in current situation?

**Comment by sashkir7** [comment]
@KazuCocoa can you help me, please

**Comment by KazuCocoa** [comment]
Please attach the full Appium server log

**Comment by sashkir7** [comment]
@KazuCocoa Yes, of course.

The logs show a clear error that the getText() method is not supported. 
That's right - here I threw off the driver code that handles this: 
https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/lib/commands/execute.ts#L84

The question is a different. In the _driver.getElementText(counterTextFinder)_ example, we are calling a command from a **flutter driver instance**. **There is no driver for Java/Kotlin Flutter** so I use 
https://mvnrepository.com/artifact/io.appium/java-client 
which provides _AndroidDriver_ and _IosDriver_. They don't have a driver.getElementText() (or driver.getText()) method. 
And I don't know how to get around it...

I'm trying to get the text by analogy with other commands - `driver.executeScript("flutter:getText", element, timeout)`
For example, by analogy with a click - `driver.executeScript("flutter:clickElement", element, timeout)`

**That is, how can I get the text from an element in Java/Kotlin?**

**Comment by sashkir7** [comment]
**Appium logs** 
```
[HTTP] --> POST /session/d9e99a6b-3fc7-4406-9656-815decf6c1ab/execute/sync
[HTTP] {"script":"flutter:getText","args":["eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiTmV4dEJ0bktleSJ9",10000]}
[debug] [FlutterDriver@4a22 (d9e99a6b)] Calling AppiumDriver.execute() with args: ["flutter:getText",["eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiTmV4dEJ0bktleSJ9",10000],"d9e99a6b-3fc7-4406-9656-815decf6c1ab"]
[debug] [FlutterDriver] Executing Flutter driver command 'execute'
[debug] [FlutterDriver@4a22 (d9e99a6b)] Encountered internal error running command: Error: Command not support: "flutter:getText"
[debug] [FlutterDriver@4a22 (d9e99a6b)]     at FlutterDriver.execute (/Users/alx.krw/.appium/node_modules/appium-flutter-driver/lib/commands/execute.ts:84:13)
[debug] [FlutterDriver@4a22 (d9e99a6b)]     at commandExecutor (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:126:9)
[debug] [FlutterDriver@4a22 (d9e99a6b)]     at /opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:154:12
[debug] [FlutterDriver@4a22 (d9e99a6b)]     at AsyncLock._promiseTry (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:287:31)
[debug] [FlutterDriver@4a22 (d9e99a6b)]     at exec (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:153:9)
[debug] [FlutterDriver@4a22 (d9e99a6b)]     at AsyncLock.acquire (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:170:3)
[debug] [FlutterDriver@4a22 (d9e99a6b)]     at FlutterDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:142:39)
[debug] [FlutterDriver@4a22 (d9e99a6b)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [FlutterDriver@4a22 (d9e99a6b)]     at FlutterDriver.executeCommand (/Users/alx.krw/.appium/node_modules/appium-flutter-driver/lib/driver.ts:184:16)
[debug] [FlutterDriver@4a22 (d9e99a6b)]     at defaultBehavior (/opt/homebrew/lib/node_modules/appium/lib/appium.js:672:14)
[debug] [FlutterDriver@4a22 (d9e99a6b)]     at AppiumDriver.executeWrappedCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:762:16)
[debug] [FlutterDriver@4a22 (d9e99a6b)]     at AppiumDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:684:17)
[debug] [FlutterDriver@4a22 (d9e99a6b)]     at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:346:19)
[HTTP] <-- POST /session/d9e99a6b-3fc7-4406-9656-815decf6c1ab/execute/sync 500 5 ms - 585
[HTTP] 
```

**Comment by KazuCocoa** [comment]
Perhaps https://github.com/appium-userland/appium-flutter-driver/blob/main/example/java/src/test/java/example/appium/FlutterTest.java#L66 ?

**Comment by sashkir7** [comment]
Yes, it worked! 
Thank you!
