### ISSUE TITLE
Scrolling doesn't work for the Text keyValue

### ISSUE THREAD

**Issue by ahashmi24** [appium-userland/appium-flutter-driver#67]
**Appium version :** v1.17.0-beta.1

**Appium logs:**
https://gist.github.com/ahashmi24/62e7638996d5da6b0d6bca02a5ae7f89

**Using below code snippet to perform scrolling:**
driver.executeScript("flutter:scrollUntilVisible", find.byKey("uniqueListView"), new HashMap<String, Object>() {{
      put("item", find.byKey("uniqueKeyForVisibleTextOnScreen"));
      put("dxScroll", 90);
      put("dyScroll", -400);
    }});

    driver.executeScript("flutter:scroll", find.byKey("uniqueListView"), new HashMap<String, Object>() {{
      put("item", find.byKey("uniqueKeyForVisibleTextOnScreen"));
      put("dx", 50);
      put("dy", 100);
      put("durationMilliseconds", 200);
      put("frequency", 30);
    }});
    
    driver.executeScript("flutter:scrollIntoView", find.byKey("uniqueListView"), new HashMap<String, Object>() {{
      put("alignment", 0.1);
    }});

_Using key for ListView and visible text. I also tried with the different offset (dx & dy) to perform vertical scrolling._

**Note: It is working if I use the key of any button in place of Text.**

**Comment by KazuCocoa** [comment]
According to this code, flutter-driver simply sends flutter_driver API to the DartVM. So I assume this issue is in the Flutter side rather than flutter-driver specific.
