### ISSUE TITLE
How do you get firstMatchOnly with appium-flutter-finder

### ISSUE THREAD

**Issue by chinloyal** [appium-userland/appium-flutter-driver#88]
For example on the flutter_driver api for the [descendant](https://api.flutter.dev/flutter/flutter_driver/CommonFinders/descendant.html) method has a firstMatchOnly option. 
```dart
SerializableFinder descendant ({
    @required SerializableFinder of,
    @required SerializableFinder matching,
    bool matchRoot: false,
    bool firstMatchOnly: false
})
```

Is there some way I can get this functionality with the existing appium features. Or will this be added soon

**Comment by shibupanda** [comment]
@chinloyal 
Thanks for the update. I will try to add this to finders.
