### ISSUE TITLE
Unable to connect to Dart Observatory when interacting with animated elements

### ISSUE THREAD

**Issue by paolaguajardo** [appium-userland/appium-flutter-driver#89]
### Connecting to Dart Observatory (Error: socket hang up)

The application we are testing render the flutter widgets through a JSON received from a service, and when we try to interact with flutter commands we get stuck on the error below:

[FlutterDriver] Attempt #4
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:42607/gkBx8RFNCJc=/ws
[FlutterDriver] Error: socket hang up
[FlutterDriver]     at connResetException (internal/errors.js:608:14)
[FlutterDriver]     at Socket.socketOnEnd (_http_client.js:453:23)
[FlutterDriver]     at Socket.emit (events.js:322:22)
[FlutterDriver]     at endReadableNT (_stream_readable.js:1187:12)
[FlutterDriver]     at processTicksAndRejections (internal/process/task_queues.js:84:21)
[FlutterDriver] Check Dart Observatory URI ws://127.0.0.1:42607/gkBx8RFNCJc=/ws
[FlutterDriver] Waiting 300 seconds before trying...

We think the driver doesn't recognize the elements when they render after the initial instantiation of the driver because if we set the widgets statically we don't have any problem.

**Edit**:
We found out this is happening because the application has animated elements and flutter driver can't continue with the execution until everything on the page is loaded, which is not happening since the animations are on loop.
Have you faced a similar issue? Is there an existing known workaround?

**Environment**
Appium version: 1.16.0
node js: 12.16.3

**Comment by shibupanda** [comment]
@paolaguajardo 
Could you please help me with the application so I may help you on it.
And please send the complete Appium Server logs using GIST.

**Comment by KazuCocoa** [comment]
> We found out this is happening because the application has animated elements and flutter driver can't continue with the execution until everything on the page is loaded, which is not happening since the animations are on loop.
Have you faced a similar issue? Is there an existing known workaround?

Then, I guess only Flutter team can fix it. Afaik, this driver sends flutter_driver commands to the Dart VM. The behavior depends on the Flutter itself.
