### ISSUE TITLE
Add desired capabilities ability to support the processArguments

### ISSUE THREAD

**Issue by arturk** [appium-userland/appium-flutter-driver#97]
I want to be able to pass the launch parameters to the flutter process. In my case I want to be able to trigger flutter application with next parameteres:
```
"processArguments": {
    "args": ["--observatory-port=8181", "--disable-service-auth-codes"]
  },
```
so it would be possible to run flutter app on a permanent observatory address

**Comment by KazuCocoa** [comment]
`appium:processArguments` is now available for iOS.
